"use client";

import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";

import { requestJson } from "@/lib/api/client";

type Analytics = {
  scope:{preset:string;start_date:string;end_date:string;timezone:string};
  definitions:Record<string,string>;
  kpis:Record<string,number|string|null>;
  appointments:{completion_rate:number;cancellation_rate:number;statuses:Record<string,number>;request_statuses:Record<string,number>};
  growth:Array<{date:string;bookings:number;completed:number;booked_value:string;customers:number}>;
  practitioner_payments:Record<string,{count:number;amount:string}>;
  therapies:Array<{id:string;name:string;bookings:number;completed:number;booked_value:string;average_rating:number|null}>;
  commercial_performance:Array<{kind:string;name:string;bookings:number;booked_value:string;discounts:string;average_discount:string;completed:number;completion_rate:number}>;
  customers:{total:number;new:number;repeat:number;repeat_rate:number;self_bookings:number;family_bookings:number;average_completed_per_returning_customer:number};
  therapists:Array<{id:string;name:string;assigned:number;accepted:number;rejected:number;completed:number;active_workload:number;acceptance_rate:number;completion_rate:number;average_rating:number|null;review_count:number}>;
  reviews:{average:number|null;count:number;distribution:Record<string,number>;trend:Array<{date:string;average:number;count:number}>;recent:Array<{stars:number;comment:string;created_at:string;therapy:string}>};
  attention:Record<string,number>;
};

const labels:Record<string,string>={total_requests:"Appointment requests",total_scheduled:"Scheduled appointments",pending:"Pending assignment",confirmed:"Confirmed",in_progress:"In progress",completed:"Completed",cancelled:"Cancelled",customers:"Customers",repeat_customers:"Repeat customers",active_therapists:"Active therapists",average_approved_rating:"Approved rating",booked_value:"Booked value",completed_service_value:"Completed service value",total_discounts:"Discounts granted"};
const moneyKeys=new Set(["booked_value","completed_service_value","total_discounts"]);
const money=(value:string|number|null)=>`₹${Number(value??0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const title=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());

function TrendChart({rows}:{rows:Analytics["growth"]}){
  const visible=rows.slice(-31);const peak=Math.max(1,...visible.map(row=>Math.max(row.bookings,row.completed)));
  return <div><div className="flex h-52 items-end gap-1" aria-label="Booking and completion trend">{visible.map(row=><div key={row.date} className="group relative flex min-w-0 flex-1 items-end gap-px" title={`${row.date}: ${row.bookings} bookings, ${row.completed} completed`}><span className="w-1/2 rounded-t bg-emerald-600" style={{height:`${Math.max(3,row.bookings/peak*100)}%`}}/><span className="w-1/2 rounded-t bg-amber-500" style={{height:`${Math.max(3,row.completed/peak*100)}%`}}/></div>)}</div><div className="mt-3 flex flex-wrap gap-4 text-xs"><span><i className="mr-1 inline-block h-2 w-2 bg-emerald-600"/>Bookings</span><span><i className="mr-1 inline-block h-2 w-2 bg-amber-500"/>Completed</span></div></div>;
}

function Table({headers,rows}:{headers:string[];rows:Array<Array<React.ReactNode>>}){return <div className="max-w-full overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b bg-slate-50">{headers.map(item=><th key={item} className="p-3 font-semibold">{item}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} className="border-b last:border-0">{row.map((cell,cellIndex)=><td key={cellIndex} className="p-3">{cell}</td>)}</tr>)}</tbody></table></div>}

export function OwnerAnalyticsDashboard(){
  const [preset,setPreset]=useState("last_30_days");const [start,setStart]=useState("");const [end,setEnd]=useState("");
  const params=new URLSearchParams({preset});if(preset==="custom"&&start&&end){params.set("start",start);params.set("end",end)}
  const query=useQuery({queryKey:["owner-analytics",params.toString()],enabled:preset!=="custom"||Boolean(start&&end),queryFn:()=>requestJson<Analytics>(`/api/owner/analytics?${params}`)});
  const data=query.data;
  return <section className="min-w-0" aria-labelledby="business-analytics-title"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">Strategic overview</p><h2 id="business-analytics-title" className="text-3xl font-bold text-slate-950">Business analytics</h2>{data&&<p className="mt-1 text-sm text-slate-600">{data.scope.start_date} to {data.scope.end_date} · {data.scope.timezone}</p>}</div><a href={`/api/owner/analytics/export?${params}`} className="min-h-11 rounded-xl border border-emerald-700 px-4 py-2.5 font-bold text-emerald-800">Export summary CSV</a></div>
  <div className="mt-5 flex flex-wrap gap-3 rounded-2xl border bg-white p-4"><label className="min-w-0 flex-1 sm:max-w-56">Date range<select value={preset} onChange={event=>setPreset(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3"><option value="today">Today</option><option value="last_7_days">Last 7 days</option><option value="last_30_days">Last 30 days</option><option value="this_month">This month</option><option value="previous_month">Previous month</option><option value="custom">Custom range</option></select></label>{preset==="custom"&&<><label>Start<input type="date" value={start} onChange={event=>setStart(event.target.value)} className="mt-1 block min-h-11 rounded-xl border px-3"/></label><label>End<input type="date" value={end} onChange={event=>setEnd(event.target.value)} className="mt-1 block min-h-11 rounded-xl border px-3"/></label></>}</div>
  {query.isPending&&<p className="mt-6">Loading owner analytics…</p>}{query.isError&&<p className="mt-6 text-red-700">Analytics could not be loaded for this range.</p>}{data&&<div className="min-w-0">
    <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-7">{Object.entries(data.kpis).map(([key,value])=><article key={key} className="min-w-0 rounded-2xl border bg-white p-4"><p className="break-words text-xs font-bold uppercase tracking-wide text-slate-500">{labels[key]??title(key)}</p><p className="mt-2 break-words text-2xl font-bold text-slate-950">{value===null?"—":moneyKeys.has(key)?money(value):key==="average_approved_rating"?`${value} ★`:value}</p></article>)}</div>
    <div className="mt-6 grid min-w-0 gap-5 xl:grid-cols-[2fr_1fr]"><article className="min-w-0 rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Business growth</h3><TrendChart rows={data.growth}/></article><article className="min-w-0 rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Appointment performance</h3><dl className="mt-4 grid grid-cols-2 gap-3"><div><dt>Completion rate</dt><dd className="text-2xl font-bold">{data.appointments.completion_rate}%</dd></div><div><dt>Cancellation rate</dt><dd className="text-2xl font-bold">{data.appointments.cancellation_rate}%</dd></div></dl><div className="mt-5 space-y-2 text-sm">{Object.entries(data.appointments.statuses).map(([key,value])=><p key={key} className="flex justify-between"><span>{title(key)}</span><strong>{value}</strong></p>)}</div></article></div>
    <div className="mt-6 grid min-w-0 gap-5 xl:grid-cols-2"><article className="min-w-0 rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Therapy performance</h3><Table headers={["Therapy","Bookings","Completed","Booked value","Rating"]} rows={data.therapies.map(row=>[row.name,row.bookings,row.completed,money(row.booked_value),row.average_rating?`${row.average_rating} ★`:"—"])}/></article><article className="min-w-0 rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Packages &amp; offers</h3><Table headers={["Benefit","Type","Bookings","Booked value","Discounts","Completion"]} rows={data.commercial_performance.map(row=>[row.name,title(row.kind),row.bookings,money(row.booked_value),money(row.discounts),`${row.completion_rate}%`])}/></article></div>
    <div className="mt-6 grid min-w-0 gap-5 xl:grid-cols-3"><article className="rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Customer mix</h3><dl className="mt-4 grid grid-cols-2 gap-3">{Object.entries(data.customers).map(([key,value])=><div key={key}><dt className="text-xs text-slate-500">{title(key)}</dt><dd className="text-xl font-bold">{key.endsWith("rate")?`${value}%`:value}</dd></div>)}</dl></article><article className="rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Practitioner payout position</h3><p className="mt-1 text-xs text-slate-500">Operational payout records, not customer collections.</p><div className="mt-4 space-y-3">{Object.entries(data.practitioner_payments).map(([key,value])=><p key={key} className="flex justify-between gap-3"><span>{title(key)} ({value.count})</span><strong>{money(value.amount)}</strong></p>)}</div></article><article className="rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Customer satisfaction</h3><p className="mt-3 text-3xl font-bold">{data.reviews.average??"—"} ★</p><p>{data.reviews.count} approved reviews</p><div className="mt-4 space-y-2">{[5,4,3,2,1].map(star=><div key={star} className="flex items-center gap-2 text-sm"><span>{star}★</span><div className="h-2 flex-1 rounded bg-slate-100"><div className="h-2 rounded bg-amber-500" style={{width:`${data.reviews.count?data.reviews.distribution[String(star)]/data.reviews.count*100:0}%`}}/></div><strong>{data.reviews.distribution[String(star)]}</strong></div>)}</div></article></div>
    <article className="mt-6 min-w-0 rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Therapist operations</h3><Table headers={["Therapist","Assigned","Accepted","Rejected","Completed","Active","Acceptance","Rating"]} rows={data.therapists.map(row=>[row.name,row.assigned,row.accepted,row.rejected,row.completed,row.active_workload,`${row.acceptance_rate}%`,row.average_rating?`${row.average_rating} ★ (${row.review_count})`:"—"])}/></article>
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h3 className="text-xl font-bold">Operational attention</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(data.attention).map(([key,value])=><Link key={key} href={key.includes("practitioner_application")?"/owner#practitioner-review":"/owner#operations"} className="rounded-xl bg-white p-3"><span className="block text-sm">{title(key)}</span><strong className="text-2xl">{value}</strong></Link>)}</div></article><article className="rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Recent approved reviews</h3><div className="mt-4 space-y-4">{data.reviews.recent.map((review,index)=><blockquote key={index} className="border-l-4 border-emerald-600 pl-3"><p>{review.stars} ★ · {review.therapy}</p><p className="break-words text-sm text-slate-600">{review.comment||"Rating submitted without a comment."}</p></blockquote>)}{data.reviews.recent.length===0&&<p className="text-slate-600">No approved reviews in this range.</p>}</div></article></div>
    <p className="mt-5 text-xs text-slate-500">Booked value is not revenue. {data.definitions.booked_value} {data.definitions.repeat_customer}</p>
  </div>}</section>;
}
