import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import { PublicReviews } from "@/components/appointments/review-panels";
import { BookingEntry } from "@/components/public/booking-entry";
import { CommercialOffers,TherapyGrid } from "@/components/public/therapy-grid";
import { PublicShell } from "@/components/public/public-shell";
import { Reveal } from "@/components/public/reveal";
import { SectionHeading } from "@/components/public/section-heading";
import { contact } from "@/lib/public-site/content";

export const metadata:Metadata={title:"Home Physiotherapy & Wellness Care in Meerut",description:"Book professional home physiotherapy and wellness services in Meerut with secure mobile verification, transparent therapy pricing, and Manager-coordinated visits.",openGraph:{title:"JeevaSetu | Professional Care at Your Home",description:"Professional physiotherapy and wellness care coordinated for your home in Meerut.",type:"website"}};

const steps=[
  ["01","Choose therapy or plan","Browse current therapies, session plans, and eligible offers."],
  ["02","Select date and time","Share a preferred visit slot within available service hours."],
  ["03","Verify mobile and book","Use the secure OTP step to submit your appointment request."],
  ["04","Manager confirms therapist","The JeevaSetu team reviews the request and coordinates an available professional."],
  ["05","Professional visits your home","Prepare a comfortable space and follow the confirmed visit guidance."],
  ["06","Verify and complete service","A service OTP helps confirm the visit before completion is recorded."],
] as const;
const trust=[
  ["Verified practitioner workflow","Professional applications, qualifications, and documents move through a Manager review process."],
  ["Secure appointment process","Mobile verification and protected customer access support a clear booking journey."],
  ["Care coordinated at home","JeevaSetu schedules services around your confirmed address and visit window."],
  ["Transparent information","Current therapy prices, 45-minute duration, plans, and active offers come from the managed catalog."],
  ["Service verification","Visit verification helps connect the scheduled appointment with the service delivered."],
  ["Customer history","Signed-in customers can review appointments, family bookings, and eligible completed-service actions."],
] as const;

export default function Home(){return <PublicShell><main>
  <section className="premium-hero relative isolate overflow-hidden"><Image src="/images/ayurveda-hero.png" alt="JeevaSetu home wellness service preparation" fill priority className="object-cover object-[72%_center]" sizes="100vw"/><div className="premium-hero-scrim absolute inset-0"/><div className="site-container relative flex min-h-[min(820px,calc(100svh-4.75rem))] items-center py-20"><div className="max-w-3xl"><p className="eyebrow hero-reveal">Professional home care · Meerut</p><h1 className="hero-reveal mt-5 max-w-[13ch] font-serif text-[clamp(3.1rem,7vw,6.6rem)] leading-[.94] tracking-[-.045em] text-[#103c27]">Physiotherapy &amp; wellness care, <em className="font-normal text-[#0b6b3a]">at your home.</em></h1><p className="hero-reveal mt-7 max-w-2xl text-lg leading-8 text-[#405f4f]">Choose an available therapy or plan, request a convenient time, and let JeevaSetu coordinate a professional home visit through a secure booking process.</p><div className="hero-reveal mt-9 flex flex-wrap gap-3"><Link href="/book-appointment" className="button-primary">Book Appointment <span aria-hidden="true">→</span></Link><Link href="/therapies" className="button-secondary">Explore Therapies</Link></div><ul className="hero-reveal mt-8 grid max-w-2xl gap-3 text-sm font-semibold text-[#294d3a] sm:grid-cols-2"><li>✓ Reviewed professional workflow</li><li>✓ Home-service coordination</li><li>✓ Secure mobile booking</li><li>✓ Transparent therapy plans</li></ul><p className="mt-6 max-w-xl text-xs leading-5 text-[#68786f]">JeevaSetu wellness services do not replace medical diagnosis, emergency care, or treatment prescribed by your clinician.</p></div></div><div className="site-container relative -mb-20"><BookingEntry/></div></section>

  <Reveal><section id="how-it-works" className="section scroll-mt-24 pt-32"><div className="site-container"><SectionHeading eyebrow="How it works" title="From your first choice to a verified home visit" copy="A straightforward journey built on the booking, scheduling, and service-verification tools already used by JeevaSetu." center/><ol className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{steps.map(([number,title,copy])=><li key={number} className="process-card"><span className="process-number">{number}</span><h3 className="mt-5 font-serif text-2xl text-[#103c27]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#5b6c63]">{copy}</p></li>)}</ol></div></section></Reveal>

  <Reveal><section className="section bg-[#f7f3e9]"><div className="site-container"><div className="flex flex-wrap items-end justify-between gap-5"><SectionHeading eyebrow="Available therapies" title="Clear choices for care at home" copy="Current services, prices, and availability are published directly from the JeevaSetu therapy catalog."/><Link href="/therapies" className="button-secondary">View all therapies</Link></div><div className="mt-10"><TherapyGrid limit={6} compact/></div></div></section></Reveal>

  <Reveal><section className="section"><div className="site-container"><div className="flex flex-wrap items-end justify-between gap-5"><SectionHeading eyebrow="Plans & offers" title="Choose the option that fits your care journey" copy="Only currently active, publicly available plans and offers appear here—never fabricated promotions."/><Link href="/packages" className="button-secondary">See plans &amp; offers</Link></div><div className="mt-10"><CommercialOffers limit={6}/></div></div></section></Reveal>

  <Reveal><section className="section overflow-hidden bg-[#073d25] text-white"><div className="site-container grid items-center gap-12 lg:grid-cols-[1fr_.9fr]"><div><p className="eyebrow !text-[#e2c679]">Why JeevaSetu</p><h2 className="mt-4 max-w-xl font-serif text-4xl leading-tight sm:text-5xl">Trust comes from a clear process—not unsupported promises.</h2><div className="mt-9 grid gap-4 sm:grid-cols-2">{trust.map(([title,copy])=><article key={title} className="rounded-2xl border border-white/15 p-5"><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-white/70">{copy}</p></article>)}</div></div><div className="relative aspect-[4/5] overflow-hidden rounded-[2.5rem]"><Image src="/images/ayurveda-home-service.png" alt="Prepared space for a JeevaSetu home service" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 42vw"/></div></div></section></Reveal>

  <div id="reviews" className="scroll-mt-24"><PublicReviews/></div>

  <Reveal><section className="section"><div className="site-container grid gap-6 lg:grid-cols-2"><article className="join-panel"><p className="eyebrow !text-[#e2c679]">For practitioners</p><h2 className="mt-4 font-serif text-4xl leading-tight text-white">Join JeevaSetu as a Professional</h2><p className="mt-4 max-w-xl leading-7 text-white/75">Apply online, submit your professional details and documents, and follow the Manager review process. Approval may provide access to appointment opportunities; it is not a promise of employment or guaranteed assignments.</p><ol className="mt-6 grid gap-2 text-sm text-white/85 sm:grid-cols-2"><li>1. Create your application</li><li>2. Submit professional details</li><li>3. Manager reviews documents</li><li>4. Approved profile can receive opportunities</li></ol><Link href="/work-with-us" className="button-gold mt-7">Join With Us</Link></article><article className="contact-panel"><p className="eyebrow">Contact JeevaSetu</p><h2 className="mt-4 font-serif text-4xl leading-tight text-[#103c27]">Questions before you book?</h2><p className="mt-4 leading-7 text-[#5b6c63]">Speak with the JeevaSetu team about service availability in and around Meerut, preparation, or the next step.</p><address className="mt-6 space-y-3 not-italic"><p><span className="contact-label">Phone</span><a className="text-xl font-bold text-[#0b6b3a]" href={contact.phoneHref}>{contact.phone}</a></p><p><span className="contact-label">Email</span><a href={`mailto:${contact.email}`}>{contact.email}</a></p><p><span className="contact-label">Service location</span>{contact.address}</p><p><span className="contact-label">Booking hours</span>Appointment slots are coordinated between 9 AM and 6 PM.</p></address><div className="mt-7 flex flex-wrap gap-3"><a href={contact.phoneHref} className="button-primary">Call JeevaSetu</a><Link href="/contact" className="button-secondary">Contact Us</Link></div></article></div></section></Reveal>

  <section className="section pt-0"><div className="site-container rounded-[2.5rem] bg-[#f0e8d8] px-6 py-14 text-center sm:px-12"><p className="eyebrow">Care, closer to home</p><h2 className="mx-auto mt-4 max-w-3xl font-serif text-4xl text-[#103c27] sm:text-5xl">Ready to request your JeevaSetu home visit?</h2><p className="mx-auto mt-4 max-w-2xl text-[#5b6c63]">New customers can begin with secure booking. Existing customers can sign in to view their dashboard and appointment history.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/book-appointment" className="button-primary">Book Appointment</Link><Link href="/customer-login" className="button-secondary">Customer Login</Link></div></div></section>
</main></PublicShell>}
