import Image from "next/image";
import Link from "next/link";
import { FaqList } from "@/components/public/faq-list";
import { PublicShell } from "@/components/public/public-shell";
import { SectionHeading } from "@/components/public/section-heading";
import { TherapyGrid } from "@/components/public/therapy-grid";
import { contact, strengths } from "@/lib/public-site/content";

export default function Home() { return <PublicShell><main>
  <section className="relative isolate min-h-[720px] overflow-hidden bg-[#f5efe2]"><Image src="/images/ayurveda-hero.png" alt="Ayurvedic therapist preparing herbal oil for a JeevaSetu home service" fill priority className="object-cover object-[68%_center]" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-[#f8f2e7] via-[#f8f2e7]/95 to-transparent"/><div className="site-container relative flex min-h-[720px] items-center py-24"><div className="max-w-2xl"><p className="eyebrow">Ayurvedic home service · Meerut</p><h1 className="mt-5 font-serif text-6xl leading-[.95] tracking-tight text-[#103c27] sm:text-7xl">Healing naturally.<br/><em className="font-normal text-[#0b6b3a]">Living better.</em></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#466254]">Premium Ayurvedic wellness therapies delivered with warmth, privacy, and professional care—right where you feel most at ease.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/book-appointment" className="button-primary">Book appointment</Link><a href={contact.whatsapp} className="button-secondary" target="_blank" rel="noreferrer">WhatsApp</a><a href={contact.phoneHref} className="button-quiet">Call now</a></div><p className="mt-8 text-xs text-[#68786f]">Wellness services are not a substitute for medical diagnosis or treatment.</p></div></div></section>
  <section className="section"><div className="site-container"><SectionHeading eyebrow="Why JeevaSetu" title="Ayurveda, thoughtfully brought home" copy="A calm, considered experience built around trust, traditional care, and the realities of modern life."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{strengths.map(([title, copy], i) => <article key={title} className="feature-card"><span className="feature-number">0{i + 1}</span><h3 className="mt-6 font-serif text-2xl text-[#103c27]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#5b6c63]">{copy}</p></article>)}</div></div></section>
  <section className="section bg-[#f7f3e9]"><div className="site-container"><SectionHeading eyebrow="Our therapies" title="Traditional care, tailored to you" copy="Explore the ten therapies currently offered by JeevaSetu Wellness."/><TherapyGrid limit={6}/><div className="mt-10 text-center"><Link href="/therapies" className="button-secondary">Explore all therapies</Link></div></div></section>
  <section className="section"><div className="site-container grid items-center gap-12 lg:grid-cols-2"><div className="relative aspect-[4/3] overflow-hidden rounded-[2.5rem]"><Image src="/images/ayurveda-home-service.png" alt="Prepared JeevaSetu home therapy room" fill className="object-cover" sizes="50vw"/></div><div><SectionHeading eyebrow="Wellness packages" title="A consistent rhythm for your wellbeing" copy="Choose a 5, 7, or 10-session plan, explore a combo, or speak with us about a customized package."/><div className="grid grid-cols-2 gap-3">{["5 Sessions", "7 Sessions", "10 Sessions", "Combo Packages"].map(item => <div className="rounded-2xl border border-[#0b6b3a]/15 p-5 font-semibold text-[#0b6b3a]" key={item}>{item}<span className="mt-1 block text-xs font-normal text-[#68786f]">Validity confirmed at booking</span></div>)}</div><Link href="/packages" className="button-primary mt-7">View packages</Link></div></div></section>
  <section className="section bg-[#0b6b3a] text-white"><div className="site-container"><SectionHeading eyebrow="Why choose us" title="Quiet confidence in every visit" copy="Professional conduct, careful preparation, and care that respects your home."/><div className="grid gap-6 md:grid-cols-3">{strengths.slice(0,3).map(([title, copy]) => <div key={title} className="rounded-3xl border border-white/15 p-7"><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 text-sm leading-7 text-white/70">{copy}</p></div>)}</div></div></section>
  <section className="section"><div className="site-container"><SectionHeading eyebrow="Kind words" title="Care remembered for how it feels" center/><div className="grid gap-5 md:grid-cols-3">{[["AS","A calm and well-organized home visit. Everything was explained clearly and handled with care."],["RK","The therapist was punctual, respectful, and attentive to comfort throughout the session."],["NM","Booking by phone was simple, and the home-service experience felt thoughtful and private."]].map(([initials,quote]) => <figure className="card p-7" key={initials}><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-[#edf7ef] font-bold text-[#0b6b3a]" aria-label="Patient photo placeholder">{initials}</span><span className="text-[#c89b3c]" aria-label="5 out of 5 stars">★★★★★</span></div><blockquote className="mt-5 leading-7 text-[#466254]">“{quote}”</blockquote><figcaption className="mt-4 text-xs font-bold tracking-widest text-[#0b6b3a] uppercase">Verified wellness client</figcaption></figure>)}</div></div></section>
  <section className="section bg-[#f7f3e9]"><div className="site-container"><SectionHeading eyebrow="Questions, answered" title="Know what to expect" center/><FaqList limit={4}/><div className="mt-8 text-center"><Link href="/faq" className="button-quiet">Read all FAQs</Link></div></div></section>
  <section className="section"><div className="site-container rounded-[2.5rem] bg-[#173d2a] px-7 py-14 text-center text-white sm:px-14"><p className="eyebrow text-[#e2c679]">Your wellness, closer to home</p><h2 className="mx-auto mt-4 max-w-3xl font-serif text-4xl sm:text-5xl">Ready to begin a more thoughtful care routine?</h2><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/book-appointment" className="button-gold">Book appointment</Link><a href={contact.whatsapp} className="button-light" target="_blank" rel="noreferrer">WhatsApp</a><a href={contact.phoneHref} className="button-light">Call now</a></div></div></section>
</main></PublicShell>; }
