"use client";

import Image from "next/image";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { requestJson } from "@/lib/api/client";
import type { CommercialCatalog } from "@/lib/appointments/contracts";

const money=(value:string|undefined)=>`₹${Number(value??0).toLocaleString("en-IN")}`;
const catalogQuery=()=>requestJson<CommercialCatalog>("/api/commercial/public");

export function TherapyGrid({limit,compact=false}:{limit?:number;compact?:boolean}){
  const query=useQuery({queryKey:["commercial-public"],queryFn:catalogQuery});
  const therapies=(query.data?.therapies??[]).slice(0,limit);
  if(query.isPending)return <p className="py-8 text-center text-[#5b6c63]">Loading current therapies…</p>;
  if(query.isError)return <p className="py-8 text-center text-red-700">Current therapies could not be loaded.</p>;
  if(!therapies.length)return <p className="rounded-3xl border border-dashed border-[#0b6b3a]/25 p-8 text-center text-[#5b6c63]">No therapies are publicly available right now. Please contact JeevaSetu for availability.</p>;
  return <div className={`grid gap-5 ${compact?"sm:grid-cols-2 lg:grid-cols-3":"md:grid-cols-2 xl:grid-cols-3"}`}>{therapies.map((therapy,index)=><article key={therapy.id} id={therapy.slug} className="card group min-w-0 overflow-hidden">{!compact&&<div className="relative aspect-[16/9] overflow-hidden"><Image src={index%3===0?"/images/ayurveda-home-service.png":index%3===1?"/images/ayurveda-essentials.png":"/images/ayurveda-hero.png"} alt="" fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 33vw"/></div>}<div className={compact?"p-5":"p-6"}><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#9b7427]">Home service · 45 min</p><h3 className="mt-2 break-words font-serif text-2xl text-[#103c27]">{therapy.name}</h3></div><strong className="shrink-0 rounded-full bg-[#edf7ef] px-3 py-1.5 text-[#0b6b3a]">{money(therapy.base_price)}<span className="sr-only"> per session</span></strong></div><p className="mt-3 line-clamp-3 break-words text-sm leading-6 text-[#5b6c63]">{therapy.short_description||therapy.detailed_description||"Professional home-service care coordinated by JeevaSetu."}</p>{!compact&&therapy.benefits?.length?<ul className="mt-4 flex flex-wrap gap-2">{therapy.benefits.slice(0,4).map(item=><li key={item} className="rounded-full bg-[#f7f3e9] px-3 py-1 text-xs text-[#405f4f]">{item}</li>)}</ul>:null}<div className="mt-5 flex flex-wrap items-center gap-2"><Link href={`/book-appointment?therapy=${therapy.id}`} className="button-primary !min-h-11 !px-4">Book</Link><Link href={`/therapies#${therapy.slug}`} className="button-quiet !min-h-11 !px-3">View details</Link></div></div></article>)}</div>;
}

export function CommercialOffers({limit}:{limit?:number}){
  const query=useQuery({queryKey:["commercial-public"],queryFn:catalogQuery});const catalog=query.data;
  const packages=(catalog?.packages??[]).slice(0,limit);const offers=(catalog?.offers??[]).slice(0,limit);
  if(query.isPending)return <p className="py-8 text-center text-[#5b6c63]">Loading current plans and offers…</p>;
  if(query.isError)return <p className="py-8 text-center text-red-700">Plans and offers could not be loaded.</p>;
  if(!catalog||(!packages.length&&!offers.length))return <div className="rounded-3xl border border-dashed border-[#0b6b3a]/25 bg-white/60 p-8 text-center"><h3 className="font-serif text-2xl text-[#103c27]">Simple, transparent session pricing</h3><p className="mt-2 text-sm text-[#5b6c63]">There are no active public promotions right now. You can still book any available therapy at its current session price.</p><Link href="/therapies" className="button-secondary mt-5">View therapies</Link></div>;
  return <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{packages.map(item=><article key={item.id} className="offer-card min-w-0"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#9b7427]">Session plan</p><h3 className="mt-2 break-words font-serif text-3xl text-[#103c27]">{item.name}</h3><p className="mt-2 text-sm text-[#5b6c63]">{item.therapy_name} · {item.session_count} sessions</p><div className="mt-5 rounded-2xl bg-[#f7f3e9] p-4"><p><s className="text-slate-500">Regular {money(item.regular_total)}</s></p><p className="mt-1 text-2xl font-bold text-[#0b6b3a]">Offer {money(item.selling_price)}</p><p className="mt-1 text-sm font-semibold">Save {money(item.saving)} · {item.discount_percentage}%</p></div>{item.description&&<p className="mt-4 line-clamp-2 text-sm text-[#5b6c63]">{item.description}</p>}<Link href={`/book-appointment?package=${item.id}`} className="button-primary mt-5">Choose plan</Link></article>)}{offers.map(item=><article key={item.id} className="offer-card min-w-0"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#9b7427]">{item.offer_type==="FIXED_BUNDLE"?"Therapy combo":item.offer_type==="FAMILY"?"Family offer":item.offer_type==="FREE_THERAPY"?"Free add-on offer":"Current offer"}</p><h3 className="mt-2 break-words font-serif text-3xl text-[#103c27]">{item.title}</h3><p className="mt-2 break-words text-sm text-[#5b6c63]">{item.promotional_text}</p><p className="mt-4 break-words text-sm font-semibold text-[#294d3a]">{item.eligible_therapy_names.join(" + ")}</p>{item.offer_type==="PERCENTAGE"&&<p className="mt-3 text-xl font-bold text-[#0b6b3a]">Save {item.discount_value}%</p>}{item.offer_type==="FAMILY"&&<p className="mt-3 text-xl font-bold text-[#0b6b3a]">Family booking saves {item.discount_value}%</p>}{item.offer_type==="FIXED_DISCOUNT"&&<p className="mt-3 text-xl font-bold text-[#0b6b3a]">Save {money(item.discount_value)}</p>}{item.offer_type==="FIXED_BUNDLE"&&<p className="mt-3 text-xl font-bold text-[#0b6b3a]">Bundle price {money(item.fixed_price??undefined)}</p>}{item.offer_type==="FREE_THERAPY"&&<p className="mt-3 text-xl font-bold text-[#0b6b3a]">Includes {item.free_quantity} × {item.free_therapy_name}</p>}<Link href={`/book-appointment?offer=${item.id}`} className="button-primary mt-5">Choose offer</Link></article>)}</div>;
}
