"use client";
import Image from "next/image";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { requestJson } from "@/lib/api/client";
import type { CommercialCatalog } from "@/lib/appointments/contracts";

const money=(value:string|undefined)=>`₹${Number(value??0).toLocaleString("en-IN")}`;
export function TherapyGrid({limit}:{limit?:number}){
  const query=useQuery({queryKey:["commercial-public"],queryFn:()=>requestJson<CommercialCatalog>("/api/commercial/public")});
  const therapies=(query.data?.therapies??[]).slice(0,limit);
  return <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{therapies.map((therapy,index)=><article key={therapy.id} id={therapy.slug} className="card group min-w-0 overflow-hidden"><div className="relative aspect-[4/3] overflow-hidden"><Image src={index%3===0?"/images/ayurveda-home-service.png":index%3===1?"/images/ayurveda-essentials.png":"/images/ayurveda-hero.png"} alt={`${therapy.name} home wellness service`} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 33vw"/></div><div className="p-6"><div className="flex items-start justify-between gap-4"><h3 className="font-serif text-2xl text-[#103c27]">{therapy.name}</h3><strong className="shrink-0 text-[#0b6b3a]">{money(therapy.base_price)}</strong></div><p className="mt-3 break-words text-sm leading-6 text-[#5b6c63]">{therapy.short_description||therapy.detailed_description}</p>{!limit&&<><p className="mt-4 text-xs font-bold tracking-widest text-[#9b7427] uppercase">45 min · per session</p><ul className="mt-4 flex flex-wrap gap-2">{therapy.benefits?.map(item=><li key={item} className="rounded-full bg-[#edf7ef] px-3 py-1 text-xs text-[#0b6b3a]">{item}</li>)}</ul></>}<Link href={limit?`/therapies#${therapy.slug}`:`/book-appointment?therapy=${therapy.id}`} className="mt-5 inline-flex font-semibold text-[#0b6b3a]">{limit?"View details →":"Book appointment →"}</Link></div></article>)}{query.isPending&&<p>Loading current therapies…</p>}</div>;
}

export function CommercialOffers(){const query=useQuery({queryKey:["commercial-public"],queryFn:()=>requestJson<CommercialCatalog>("/api/commercial/public")});const catalog=query.data;if(!catalog||(catalog.packages.length===0&&catalog.offers.length===0))return null;return <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{catalog.packages.map(item=><article key={item.id} className="card min-w-0 p-6"><p className="text-xs font-bold uppercase tracking-widest text-[#9b7427]">Session plan</p><h2 className="mt-2 break-words font-serif text-3xl text-[#103c27]">{item.name}</h2><p className="mt-2 text-sm text-[#5b6c63]">{item.therapy_name} · {item.session_count} sessions</p><p className="mt-4"><s className="text-slate-500">{money(item.regular_total)}</s> <strong className="ml-2 text-xl text-[#0b6b3a]">{money(item.selling_price)}</strong></p><p className="text-sm font-semibold">Save {money(item.saving)} ({item.discount_percentage}%)</p><Link href={`/book-appointment?package=${item.id}`} className="button-secondary mt-5">Choose plan</Link></article>)}{catalog.offers.map(item=><article key={item.id} className="card min-w-0 p-6"><p className="text-xs font-bold uppercase tracking-widest text-[#9b7427]">Current offer</p><h2 className="mt-2 break-words font-serif text-3xl text-[#103c27]">{item.title}</h2><p className="mt-2 break-words text-sm text-[#5b6c63]">{item.promotional_text}</p><p className="mt-3 text-sm font-semibold">{item.eligible_therapy_names.join(" + ")}</p>{item.offer_type==="PERCENTAGE"&&<p className="mt-2 text-[#0b6b3a]">Save {item.discount_value}%</p>}{item.offer_type==="FIXED_BUNDLE"&&<p className="mt-2 text-[#0b6b3a]">Bundle price {money(item.fixed_price??undefined)}</p>}{item.offer_type==="FREE_THERAPY"&&<p className="mt-2 text-[#0b6b3a]">Includes {item.free_therapy_name}</p>}<Link href={`/book-appointment?offer=${item.id}`} className="button-secondary mt-5">Choose offer</Link></article>)}</div>}
