# Generated by Django 6.0.7 on 2026-08-06 08:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TherapyOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointment_therapies",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AppointmentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("patient_name", models.CharField(max_length=160)),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ]
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("FEMALE", "Female"),
                            ("MALE", "Male"),
                            ("OTHER", "Other"),
                            ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[6-9]\\d{9}$", "Enter a valid 10-digit Indian mobile number."
                            )
                        ],
                    ),
                ),
                (
                    "alternate_mobile",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[6-9]\\d{9}$", "Enter a valid 10-digit Indian mobile number."
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "session_preference",
                    models.CharField(
                        choices=[("SINGLE", "Single Session"), ("PACKAGE", "Package")],
                        max_length=12,
                    ),
                ),
                ("preferred_date", models.DateField()),
                ("preferred_time", models.TimeField()),
                ("problem_description", models.TextField(max_length=2000)),
                ("pain_area", models.CharField(max_length=160)),
                ("problem_duration", models.CharField(max_length=120)),
                ("doctor_reference", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=120)),
                (
                    "pin_code",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[1-9]\\d{5}$", "Enter a valid 6-digit PIN code."
                            )
                        ],
                    ),
                ),
                ("landmark", models.CharField(max_length=255)),
                ("google_map_link", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("owner_remarks", models.TextField(blank=True, max_length=1000)),
                ("duplicate_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointment_requests",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "therapy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointment_requests",
                        to="appointments.therapyoption",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="therapyoption",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="appt_therapy_org_slug_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentrequest",
            index=models.Index(
                fields=["organization", "status", "created_at"], name="appt_org_status_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentrequest",
            index=models.Index(fields=["creator", "created_at"], name="appt_creator_time_idx"),
        ),
        migrations.AddIndex(
            model_name="appointmentrequest",
            index=models.Index(fields=["mobile_number"], name="appt_mobile_idx"),
        ),
        migrations.AddConstraint(
            model_name="appointmentrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("organization", "duplicate_fingerprint"),
                name="appt_pending_fingerprint_uniq",
            ),
        ),
    ]
