# Generated by Django 6.0.7 on 2026-08-06 10:54

from datetime import time

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def configure_existing_clinics(apps, schema_editor):
    Clinic = apps.get_model("tenancy", "Clinic")
    ClinicOperatingHours = apps.get_model("appointments", "ClinicOperatingHours")
    TherapyOption = apps.get_model("appointments", "TherapyOption")
    TherapyOption.objects.filter(default_duration_minutes__isnull=True).update(
        default_duration_minutes=60
    )
    for clinic in Clinic.objects.filter(is_active=True):
        ClinicOperatingHours.objects.get_or_create(
            clinic=clinic,
            defaults={
                "weekdays": [0, 1, 2, 3, 4, 5, 6],
                "opens_at": time(8, 0),
                "closes_at": time(20, 0),
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_seed_jeevasetu_therapies"),
        ("patients", "0001_initial"),
        ("staff", "0002_seed_staff_options"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="therapyoption",
            name="default_duration_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(180),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_ASSIGNMENT", "Pending assignment"),
                            ("SCHEDULED", "Scheduled"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No show"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("landmark", models.CharField(blank=True, max_length=160)),
                ("city", models.CharField(max_length=120)),
                ("region", models.CharField(max_length=120)),
                (
                    "pin_code",
                    models.CharField(
                        max_length=6,
                        validators=[django.core.validators.RegexValidator("^[1-9]\\d{5}$")],
                    ),
                ),
                ("operational_notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "originating_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_appointment",
                        to="appointments.appointmentrequest",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "physiotherapist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="staff.staffprofile",
                    ),
                ),
                (
                    "therapy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="appointments.therapyoption",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("scheduled_start",),
            },
        ),
        migrations.CreateModel(
            name="AppointmentAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("CONVERTED", "Converted"),
                            ("RESCHEDULED", "Rescheduled"),
                            ("ASSIGNED", "Assigned"),
                            ("REASSIGNED", "Reassigned"),
                            ("STATUS_CHANGED", "Status changed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("previous_status", models.CharField(blank=True, max_length=24)),
                ("new_status", models.CharField(blank=True, max_length=24)),
                ("previous_start", models.DateTimeField(blank=True, null=True)),
                ("new_start", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "new_physiotherapist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="new_assignment_audits",
                        to="staff.staffprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
                (
                    "previous_physiotherapist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="previous_assignment_audits",
                        to="staff.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ClinicOperatingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("weekdays", models.JSONField(default=list)),
                ("opens_at", models.TimeField()),
                ("closes_at", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointment_operating_hours",
                        to="tenancy.clinic",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["organization", "clinic", "scheduled_start"],
                name="appt_sched_org_clinic_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["physiotherapist", "scheduled_start"], name="appt_sched_physio_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["organization", "status"], name="appt_sched_org_status_idx"),
        ),
        migrations.RunPython(configure_existing_clinics, migrations.RunPython.noop),
    ]
