# Generated by Django 6.0.7 on 2026-08-06 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_therapyoption_default_duration_minutes_appointment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancellation_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CUSTOMER_REQUEST", "Customer request"),
                    ("PHYSIOTHERAPIST_UNAVAILABLE", "Physiotherapist unavailable"),
                    ("CLINIC_OPERATIONAL_ISSUE", "Clinic operational issue"),
                    ("SCHEDULING_CONFLICT", "Scheduling conflict"),
                    ("DUPLICATE_APPOINTMENT", "Duplicate appointment"),
                    ("OTHER", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancelled_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reschedule_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="appointmentauditevent",
            name="outcome",
            field=models.CharField(
                choices=[("SUCCEEDED", "Succeeded"), ("REJECTED", "Rejected")],
                default="SUCCEEDED",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="appointmentauditevent",
            name="override_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="appointmentauditevent",
            name="override_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointmentauditevent",
            name="reason_category",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="appointmentauditevent",
            name="rejection_code",
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name="clinicoperatinghours",
            name="cancellation_cutoff_minutes",
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name="clinicoperatinghours",
            name="maximum_reschedules",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="clinicoperatinghours",
            name="rescheduling_cutoff_minutes",
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name="appointmentauditevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("CONVERTED", "Converted"),
                    ("RESCHEDULED", "Rescheduled"),
                    ("ASSIGNED", "Assigned"),
                    ("REASSIGNED", "Reassigned"),
                    ("STATUS_CHANGED", "Status changed"),
                    ("CANCELLED", "Cancelled"),
                    ("RESCHEDULE_REJECTED", "Reschedule rejected"),
                    ("CANCELLATION_REJECTED", "Cancellation rejected"),
                ],
                max_length=24,
            ),
        ),
    ]
