# Generated by Django 6.0.7 on 2026-08-07 07:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_appointment_cancellation_category_and_more"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatched_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="assignment_rejection_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="appointment",
            name="assignment_responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="assignment_status",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("PENDING", "Pending response"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected by Physiotherapist"),
                ],
                default="UNASSIGNED",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="manager_remarks",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="appointmentauditevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("CONVERTED", "Converted"),
                    ("RESCHEDULED", "Rescheduled"),
                    ("ASSIGNED", "Assigned"),
                    ("REASSIGNED", "Reassigned"),
                    ("UNASSIGNED", "Assignment cancelled"),
                    ("ASSIGNMENT_ACCEPTED", "Assignment accepted"),
                    ("ASSIGNMENT_REJECTED", "Assignment rejected"),
                    ("CUSTOMER_CHANGE_REQUESTED", "Customer change requested"),
                    ("STATUS_CHANGED", "Status changed"),
                    ("CANCELLED", "Cancelled"),
                    ("RESCHEDULE_REJECTED", "Reschedule rejected"),
                    ("CANCELLATION_REJECTED", "Cancellation rejected"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AppointmentChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("RESCHEDULE", "Reschedule"), ("CANCELLATION", "Cancellation")],
                        max_length=16,
                    ),
                ),
                ("requested_start", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_requests",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("appointment", "kind"),
                        name="appt_pending_change_kind_uniq",
                    )
                ],
            },
        ),
    ]
