# Generated by Django 6.0.7 on 2026-08-07 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_backfill_assignment_state"),
        ("staff", "0002_seed_staff_options"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AWAITING", "Awaiting verification"),
                            ("VERIFIED", "Verified check-in"),
                            ("EXPIRED", "Expired"),
                            ("LOCKED", "Locked"),
                            ("INVALIDATED", "Invalidated"),
                        ],
                        default="AWAITING",
                        max_length=16,
                    ),
                ),
                ("otp_hash", models.CharField(max_length=255)),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("failed_attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("invalidation_reason", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_verifications",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_visit_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
                (
                    "physiotherapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_verifications",
                        to="staff.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="VisitVerificationAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("ISSUED", "OTP issued"),
                            ("REISSUED", "OTP reissued"),
                            ("ATTEMPTED", "Verification attempted"),
                            ("SUCCEEDED", "Verification succeeded"),
                            ("EXPIRED", "OTP expired"),
                            ("INVALIDATED", "OTP invalidated"),
                            ("LOCKED", "OTP locked"),
                            ("UNAUTHORIZED", "Unauthorized attempt"),
                        ],
                        max_length=16,
                    ),
                ),
                ("outcome", models.CharField(blank=True, max_length=16)),
                ("reason_code", models.CharField(blank=True, max_length=48)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_verification_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="appointments.visitverification",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="visitverification",
            index=models.Index(fields=["appointment", "state"], name="appt_visit_verify_state_idx"),
        ),
        migrations.AddIndex(
            model_name="visitverification",
            index=models.Index(
                fields=["organization", "created_at"], name="appt_visit_verify_org_idx"
            ),
        ),
    ]
