# Generated by Django 6.0.7 on 2026-08-07 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0007_visitverification_visitverificationauditevent_and_more"),
        ("practitioners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentrequest",
            name="preferred_practitioner",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer preference only; never an operational assignment.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preferred_appointment_requests",
                to="practitioners.practitionerprofile",
            ),
        ),
    ]
