# Generated by Django 6.0.7 on 2026-08-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0009_appointmentrating_practitionerpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="arrived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="en_route_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="journey_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not started"),
                    ("EN_ROUTE", "En route"),
                    ("ARRIVED", "Arrived"),
                ],
                default="NOT_STARTED",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="location_shared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="shared_latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="shared_longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="appointmentauditevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("CONVERTED", "Converted"),
                    ("RESCHEDULED", "Rescheduled"),
                    ("ASSIGNED", "Assigned"),
                    ("REASSIGNED", "Reassigned"),
                    ("UNASSIGNED", "Assignment cancelled"),
                    ("ASSIGNMENT_ACCEPTED", "Assignment accepted"),
                    ("ASSIGNMENT_REJECTED", "Assignment rejected"),
                    ("CUSTOMER_CHANGE_REQUESTED", "Customer change requested"),
                    ("STATUS_CHANGED", "Status changed"),
                    ("CANCELLED", "Cancelled"),
                    ("RESCHEDULE_REJECTED", "Reschedule rejected"),
                    ("CANCELLATION_REJECTED", "Cancellation rejected"),
                    ("JOURNEY_STATUS_CHANGED", "Journey status changed"),
                    ("LOCATION_SHARED", "Location shared"),
                    ("RATING_SUBMITTED", "Rating submitted"),
                    ("PAYMENT_STATUS_CHANGED", "Payment status changed"),
                ],
                max_length=32,
            ),
        ),
    ]
