# Generated by Django 6.0.7 on 2026-08-15 10:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_arrived_at_appointment_completed_at_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='requested_therapies',
            field=models.ManyToManyField(blank=True, related_name='multi_therapy_requests', to='appointments.therapyoption'),
        ),
        migrations.CreateModel(
            name='BookingPhoneVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', 'Enter a valid 10-digit Indian mobile number.')])),
                ('otp_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_phone_verifications', to='tenancy.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'mobile_number', 'created_at'], name='appt_booking_otp_lookup_idx')],
            },
        ),
    ]
