# Generated by Django 6.0.7 on 2026-08-22 10:45

import django.core.validators
import django.db.models.deletion
import datetime
from django.db import migrations, models


def set_production_customer_hours(apps, schema_editor):
    hours = apps.get_model("appointments", "ClinicOperatingHours")
    hours.objects.filter(is_active=True).update(
        opens_at=datetime.time(9, 0), closes_at=datetime.time(18, 0)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0011_appointmentrequest_requested_therapies_and_more"),
        ("patients", "0002_customerfamilymember"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentrequest",
            name="family_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointment_requests",
                to="patients.customerfamilymember",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(360),
                ]
            ),
        ),
        migrations.RunPython(set_production_customer_hours, migrations.RunPython.noop),
    ]
