# Generated by Django 6.0.7 on 2026-08-23 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_appointmentrequest_family_member_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrating',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrating',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_appointment_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentrating',
            name='moderation_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='appointmentrating',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('HIDDEN', 'Hidden / Rejected')], default='PENDING', max_length=16),
        ),
        migrations.CreateModel(
            name='AppointmentRatingModerationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(max_length=16)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('HIDDEN', 'Hidden / Rejected')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_events', to='appointments.appointmentrating')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
