# Generated by Django 6.0.7 on 2026-08-23 08:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_appointmentrating_moderated_at_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapyoption',
            options={'ordering': ('display_order', 'name')},
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='commercial_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='regular_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='therapyoption',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='therapyoption',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='therapyoption',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='therapyoption',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='therapyoption',
            name='is_publicly_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='therapyoption',
            name='short_description',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.CreateModel(
            name='CommercialAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_kind', models.CharField(max_length=24)),
                ('object_id', models.UUIDField()),
                ('action', models.CharField(max_length=16)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommercialOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('promotional_text', models.CharField(blank=True, max_length=500)),
                ('offer_type', models.CharField(choices=[('PERCENTAGE', 'Percentage discount'), ('FIXED_DISCOUNT', 'Fixed discount'), ('FIXED_BUNDLE', 'Fixed-price bundle'), ('FREE_THERAPY', 'Free therapy / add-on'), ('FAMILY', 'Family discount')], max_length=24)),
                ('minimum_therapy_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('maximum_therapy_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('family_required', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_publicly_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_therapies', models.ManyToManyField(related_name='commercial_offers', to='appointments.therapyoption')),
                ('free_therapy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='free_addon_offers', to='appointments.therapyoption')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='selected_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_requests', to='appointments.commercialoffer'),
        ),
        migrations.CreateModel(
            name='TherapyPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('session_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(blank=True, max_length=500)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_publicly_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='appointments.therapyoption')),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='qualifying_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_offers', to='appointments.therapypackage'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='selected_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_requests', to='appointments.therapypackage'),
        ),
    ]
