# Generated by Django 6.0.7 on 2026-08-30 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0018_clinicoperatinghours_minimum_advance_notice"),
        ("staff", "0002_seed_staff_options"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentrequest",
            name="rejection_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO_PRACTITIONER", "No practitioner available"),
                    ("SERVICE_UNAVAILABLE", "Service unavailable"),
                    ("OUTSIDE_SERVICE_AREA", "Outside service area"),
                    ("SCHEDULING_CONFLICT", "Scheduling conflict"),
                    ("OTHER", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="rejection_customer_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="rejection_internal_note",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="AppointmentRequestAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED_AND_ASSIGNED", "Approved and assigned"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=32,
                    ),
                ),
                ("previous_status", models.CharField(blank=True, max_length=12)),
                ("new_status", models.CharField(max_length=12)),
                ("reason_category", models.CharField(blank=True, max_length=32)),
                ("customer_reason", models.CharField(blank=True, max_length=255)),
                ("internal_note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "appointment_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="appointments.appointmentrequest",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
                (
                    "physiotherapist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staff.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AppointmentReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("HOURS_24", "24 hours before"), ("HOURS_2", "2 hours before")],
                        max_length=16,
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointment_reminders",
                        to="staff.staffprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "scheduled_for"], name="appt_reminder_due_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("appointment", "kind"), name="appt_reminder_appointment_kind_uniq"
                    )
                ],
            },
        ),
    ]
