# Generated by Django 6.0.7 on 2026-09-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0021_offer_only_free_therapy_addons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentrequestauditevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("ACCEPTED", "Accepted for assignment"),
                    ("APPROVED_AND_ASSIGNED", "Approved and assigned"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=32,
            ),
        ),
    ]
