# Generated by Django 6.0.7 on 2026-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0022_customer_appointment_journey"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="service_latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service_location_accuracy_meters",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service_location_source",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("DEVICE", "Device location")],
                default="MANUAL",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service_longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="location_accuracy_meters",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="location_source",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("DEVICE", "Device location")],
                default="MANUAL",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="region",
            field=models.CharField(default="Uttar Pradesh", max_length=120),
        ),
    ]
