# Generated by Django 6.0.7 on 2026-09-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0025_appointmentrequest_booking_source_and_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentauditevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("CONVERTED", "Converted"),
                    ("RESCHEDULED", "Rescheduled"),
                    ("ASSIGNED", "Assigned"),
                    ("REASSIGNED", "Reassigned"),
                    ("UNASSIGNED", "Assignment cancelled"),
                    ("ASSIGNMENT_ACCEPTED", "Assignment accepted"),
                    ("ASSIGNMENT_REJECTED", "Assignment rejected"),
                    ("CUSTOMER_CHANGE_REQUESTED", "Customer change requested"),
                    ("STATUS_CHANGED", "Status changed"),
                    ("CANCELLED", "Cancelled"),
                    ("RESCHEDULE_REJECTED", "Reschedule rejected"),
                    ("CANCELLATION_REJECTED", "Cancellation rejected"),
                    ("JOURNEY_STATUS_CHANGED", "Journey status changed"),
                    ("LOCATION_SHARED", "Location shared"),
                    ("RATING_SUBMITTED", "Rating submitted"),
                    ("PAYMENT_STATUS_CHANGED", "Payment status changed"),
                    ("REBOOKED", "Booked again"),
                ],
                max_length=32,
            ),
        ),
    ]
