# Generated by Django 6.0.7 on 2026-09-16 05:27

from django.db import migrations, models


def mark_historical_arrivals_reached(apps, schema_editor):
    Appointment = apps.get_model("appointments", "Appointment")
    Appointment.objects.filter(journey_status="ARRIVED").update(journey_status="REACHED")


def restore_historical_arrivals(apps, schema_editor):
    Appointment = apps.get_model("appointments", "Appointment")
    Appointment.objects.filter(journey_status="REACHED").update(journey_status="ARRIVED")


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0026_alter_appointmentauditevent_event"),
    ]

    operations = [
        migrations.RunPython(mark_historical_arrivals_reached, restore_historical_arrivals),
        migrations.AlterField(
            model_name="appointment",
            name="journey_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not started"),
                    ("EN_ROUTE", "En route"),
                    ("REACHED", "Reached"),
                ],
                default="NOT_STARTED",
                max_length=16,
            ),
        ),
    ]
