# Generated by Django 6.0.7 on 2026-08-03 10:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("legal_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        max_length=63,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use lowercase letters, numbers, and single hyphens only.",
                                regex="^[a-z0-9]+(?:-[a-z0-9]+)*$",
                            )
                        ],
                    ),
                ),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("default_currency", models.CharField(blank=True, max_length=3)),
            ],
            options={
                "ordering": ("display_name",),
                "indexes": [
                    models.Index(fields=["is_active", "slug"], name="tenancy_org_active_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_currency", ""),
                            ("default_currency__regex", "^[A-Z]{3}$"),
                            _connector="OR",
                        ),
                        name="tenancy_org_currency_format",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        max_length=63,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use lowercase letters, numbers, and single hyphens only.",
                                regex="^[a-z0-9]+(?:-[a-z0-9]+)*$",
                            )
                        ],
                    ),
                ),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=32)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinics",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClinicMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "organization_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinic_memberships",
                        to="tenancy.organizationmembership",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(
                fields=["organization", "is_active"], name="tenancy_clinic_org_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clinic",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="tenancy_clinic_org_slug_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="clinic",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("country_code", ""), ("country_code__regex", "^[A-Z]{2}$"), _connector="OR"
                ),
                name="tenancy_clinic_country_format",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["organization", "is_active"], name="tenancy_orgmem_org_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(fields=["user", "is_active"], name="tenancy_orgmem_user_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "organization"), name="tenancy_orgmem_user_org_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicmembership",
            index=models.Index(fields=["clinic", "is_active"], name="tenancy_clinicmem_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="clinicmembership",
            constraint=models.UniqueConstraint(
                fields=("organization_membership", "clinic"),
                name="tenancy_clinicmem_member_clinic_uniq",
            ),
        ),
    ]
