# Generated by Django 6.0.7 on 2026-08-06 09:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("pin_codes", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_areas",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "staff_type",
                    models.CharField(
                        choices=[("MANAGER", "Manager"), ("PHYSIOTHERAPIST", "Physiotherapist")],
                        max_length=32,
                    ),
                ),
                (
                    "profile_photo",
                    models.FileField(blank=True, upload_to="staff/profile-photos/%Y/%m/"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("FEMALE", "Female"),
                            ("MALE", "Male"),
                            ("OTHER", "Other"),
                            ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                        ],
                        max_length=24,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("qualification", models.CharField(max_length=255)),
                ("registration_number", models.CharField(blank=True, max_length=120)),
                (
                    "experience_years",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(80)]
                    ),
                ),
                ("languages_known", models.JSONField(default=list)),
                (
                    "alternate_mobile",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[django.core.validators.RegexValidator("^[6-9]\\d{9}$")],
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        max_length=10,
                        validators=[django.core.validators.RegexValidator("^[6-9]\\d{9}$")],
                    ),
                ),
                ("current_address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=120)),
                (
                    "pin_code",
                    models.CharField(
                        max_length=6,
                        validators=[django.core.validators.RegexValidator("^[1-9]\\d{5}$")],
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("BUSY", "Busy"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="UNAVAILABLE",
                        max_length=16,
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                ("joining_date", models.DateField()),
                ("bio", models.TextField(blank=True, max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_profiles",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_profiles",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "service_areas",
                    models.ManyToManyField(
                        blank=True, related_name="staff_profiles", to="staff.servicearea"
                    ),
                ),
                (
                    "specializations",
                    models.ManyToManyField(
                        blank=True, related_name="staff_profiles", to="staff.specialization"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user__first_name", "user__last_name"),
            },
        ),
        migrations.CreateModel(
            name="StaffDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("file", models.FileField(upload_to="staff/documents/%Y/%m/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="staff.staffprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="servicearea",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="staff_area_org_name_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(fields=["organization", "staff_type"], name="staff_org_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="staffprofile",
            constraint=models.UniqueConstraint(
                fields=("user", "organization"), name="staff_user_org_uniq"
            ),
        ),
    ]
