# Generated by Django 6.0.7 on 2026-09-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0006_staffprofile_experience_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="profile_photo_removed",
            field=models.BooleanField(default=False),
        ),
    ]
