"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { requestJson } from "@/lib/api/client";
import type { PractitionerApplication } from "@/lib/practitioners/contracts";

const actionable = new Set(["SUBMITTED", "RESUBMITTED", "UNDER_REVIEW"]);
const human = (value: unknown) => String(value || "Not provided").replaceAll("_", " ");

export function PractitionerReview() {
  const [status,setStatus]=useState(""); const [search,setSearch]=useState("");
  const [pending,setPending]=useState<{id:string;action:"correction"|"reject"}>(); const [reason,setReason]=useState("");
  const client=useQueryClient(); const refresh=()=>client.invalidateQueries({queryKey:["practitioner-review"]});
  const query=useQuery({queryKey:["practitioner-review",status,search],queryFn:()=>requestJson<PractitionerApplication[]>(`/api/practitioners/applications?status=${status}&search=${encodeURIComponent(search)}`)});
  const review=useMutation({mutationFn:({id,action,reason=""}:{id:string;action:string;reason?:string})=>requestJson(`/api/practitioners/applications/${id}/review`,{method:"POST",body:JSON.stringify({action,reason})}),onSuccess:()=>{setPending(undefined);setReason("");void refresh()}});
  const verify=useMutation({mutationFn:({id,verified}:{id:string;verified:boolean})=>requestJson(`/api/practitioners/documents/${id}/verify`,{method:"POST",body:JSON.stringify({verified})}),onSuccess:refresh});
  return <section className="mt-8 min-w-0"><h2 className="text-2xl font-bold">Practitioner applications</h2><p className="mt-1 text-slate-600">Only submitted and actionable applications appear in this queue.</p>
    <div className="mt-5 grid gap-3 sm:grid-cols-2"><input aria-label="Search applications" value={search} onChange={e=>setSearch(e.target.value)} className="min-h-11 min-w-0 rounded-xl border px-3"/><select aria-label="Application status" value={status} onChange={e=>setStatus(e.target.value)} className="min-h-11 min-w-0 rounded-xl border px-3"><option value="">Actionable states</option>{["SUBMITTED","RESUBMITTED","UNDER_REVIEW","CORRECTION_REQUIRED"].map(item=><option key={item}>{item}</option>)}</select></div>
    <div className="mt-5 grid min-w-0 gap-4 xl:grid-cols-2">{query.data?.map(item=><article key={item.id} className="min-w-0 rounded-2xl border bg-white p-4 sm:p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-xl font-bold">{item.full_legal_name}</h3><p className="break-all text-xs text-slate-500">{item.id}</p></div><b>{human(item.status)}</b></div>
      <dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2">{[["Email",item.email],["Mobile",item.mobile_number],["DOB",item.date_of_birth],["Languages",item.languages.join(", ")],["Qualification",item.highest_qualification],["College",item.college_institute],["Awarding body",item.awarding_body],["Passing year",item.passing_year],["Registration",item.registration_number],["Experience",`${item.experience_years}y ${item.experience_months}m`],["Service area",`${item.city}, ${item.state} ${item.pin_code}`],["Availability",item.availability_notes]].map(([term,value])=><div key={String(term)} className="min-w-0 rounded-xl bg-slate-50 p-3"><dt className="font-bold">{term}</dt><dd className="break-words">{human(value)}</dd></div>)}</dl>
      <h4 className="mt-5 font-bold">Documents</h4><ul className="mt-2 grid gap-2">{item.documents.map(doc=><li key={doc.id} className="flex min-w-0 flex-wrap items-center gap-2 rounded-xl border p-3"><span className="min-w-0 flex-1 break-all">{doc.original_name} · {Math.max(1,Math.round(doc.size_bytes/1024))} KB · {human(doc.verification_status)}</span><a href={`/api/practitioners/documents/${doc.id}`} target="_blank" title={`View ${human(doc.kind)}`} aria-label={`View ${human(doc.kind)}`} className="grid min-h-11 min-w-11 place-items-center text-xl">👁</a><button disabled={verify.isPending} onClick={()=>verify.mutate({id:doc.id,verified:true})}>Verify</button><button disabled={verify.isPending} onClick={()=>verify.mutate({id:doc.id,verified:false})}>Needs correction</button></li>)}</ul>
      {actionable.has(item.status)&&<div className="mt-5 flex flex-wrap gap-2"><button disabled={review.isPending||item.status==="UNDER_REVIEW"} onClick={()=>review.mutate({id:item.id,action:"review"})} className="min-h-11 rounded-xl border px-4 font-bold">Start review</button><button disabled={review.isPending} onClick={()=>setPending({id:item.id,action:"correction"})} className="min-h-11 rounded-xl bg-amber-100 px-4 font-bold">Request correction</button><button disabled={review.isPending} onClick={()=>review.mutate({id:item.id,action:"approve"})} className="min-h-11 rounded-xl bg-emerald-700 px-4 font-bold text-white">Approve</button><button disabled={review.isPending} onClick={()=>setPending({id:item.id,action:"reject"})} className="min-h-11 rounded-xl bg-red-100 px-4 font-bold">Reject</button></div>}</article>)}</div>
    {pending&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form onSubmit={e=>{e.preventDefault();review.mutate({...pending,reason})}} className="w-full max-w-lg rounded-2xl bg-white p-5"><h3 className="text-xl font-bold">Reason required</h3><textarea required value={reason} onChange={e=>setReason(e.target.value)} rows={5} className="mt-4 w-full rounded-xl border p-3"/><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={()=>setPending(undefined)} className="min-h-11 rounded-xl border px-4">Cancel</button><button disabled={!reason.trim()||review.isPending} className="min-h-11 rounded-xl bg-emerald-700 px-4 font-bold text-white">Confirm</button></div></form></div>}
  </section>;
}
