"use client";
import Image from "next/image";
import Link from "next/link";
import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {requestJson} from "@/lib/api/client";

type LearningImage={id:string;url:string;caption_en:string;caption_hi:string;alt_text:string;sort_order:number};
type Video={id:string;title:string;youtube_url:string;video_id:string;language:string;description:string;sort_order:number;approved:boolean};
type Guide={id:string;therapy:string;therapy_name:string;title_en:string;title_hi:string;content_en:Record<string,string>;content_hi:Record<string,string>;published:boolean;version:number;updated_at:string;reviewed_at:string|null;learning_minutes:number|null;images:LearningImage[];videos:Video[];sections:string[]};
type Library={guides:Guide[];therapies:{id:string;name:string}[];sections:string[]};
const labels:Record<string,[string,string]>={overview:["Overview","परिचय"],indications:["Indications","कब उपयोग किया जाता है"],contraindications:["When not to perform","कब नहीं करना चाहिए"],patient_preparation:["Patient preparation","रोगी की तैयारी"],practitioner_preparation:["Practitioner preparation","चिकित्सक की तैयारी"],equipment:["Equipment and consumables","उपकरण और सामग्री"],procedure:["Technique / Procedure","तकनीक / प्रक्रिया"],positioning:["Positioning","स्थिति"],duration:["Typical duration","सामान्य अवधि"],precautions:["Safety precautions","सुरक्षा सावधानियाँ"],stop_criteria:["Stop / Escalation criteria","रोकने / सहायता लेने के मानदंड"],aftercare:["After-care guidance","बाद की देखभाल"],common_mistakes:["Common mistakes","सामान्य गलतियाँ"],documentation:["Documentation checklist","दस्तावेज़ जाँच सूची"],key_takeaways:["Key takeaways","मुख्य बातें"]};
const card="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7";
const field="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2";
const note="Follow NuriPain Ease clinical protocols, practitioner scope of practice, patient-specific assessment and applicable medical advice. This learning material does not replace clinical judgment.";
export function LearningCentre({owner=false}:{owner?:boolean}){
 const client=useQueryClient();const [search,setSearch]=useState(""),[mine,setMine]=useState(false);
 const q=useQuery({queryKey:["learning-library",owner],queryFn:()=>requestJson<Library>("/api/learning")});
 const profile=useQuery({queryKey:["learning-competencies"],queryFn:()=>requestJson<{verified_therapy_ids:string[]}>("/api/staff/me"),enabled:!owner});
 const create=useMutation({mutationFn:(therapy:{id:string;name:string})=>requestJson<Guide>("/api/learning",{method:"POST",body:JSON.stringify({therapy:therapy.id,title_en:therapy.name})}),onSuccess:()=>client.invalidateQueries({queryKey:["learning-library"]})});
 if(q.isPending)return <div className={`${card} h-64 animate-pulse`} aria-label="Loading Learning Centre"/>;
 if(!q.data)return <p role="alert">Learning content could not be loaded.</p>;
 const guides=q.data.guides.filter(g=>(g.title_en+g.title_hi+g.therapy_name).toLowerCase().includes(search.toLowerCase())&&(!mine||profile.data?.verified_therapy_ids.includes(g.therapy)));
 const pending=q.data.therapies.filter(t=>!q.data.guides.some(g=>g.therapy===t.id));
 return <div className="mx-auto max-w-6xl space-y-6"><header className={`${card} bg-gradient-to-br from-emerald-50 to-white`}><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">NuriPain Ease · Professional learning</p><h2 className="mt-3 text-3xl font-bold">{owner?"Learning Content":"Therapist Learning Centre"}</h2><p className="mt-3 max-w-2xl text-slate-600">{owner?"Prepare, clinically review and publish your organization’s English and Hindi therapy guides.":"Your organization-approved therapy reference library. Learn at your own pace; work within your verified scope."}</p><div className="mt-5 flex flex-wrap items-center gap-4"><label className="grid flex-1 gap-2 text-sm font-semibold">Search therapy<input className={field} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a learning guide"/></label>{!owner&&<label className="flex gap-2"><input type="checkbox" checked={mine} onChange={e=>setMine(e.target.checked)}/>My verified therapies</label>}</div></header>{create.error&&<p role="alert">{create.error.message}</p>}
 {owner&&pending.length>0&&<section className={card}><h3 className="text-xl font-bold">Create a guide</h3><p className="my-2 text-sm text-slate-600">Active therapies without a guide. New guides start unpublished.</p><div className="flex flex-wrap gap-2">{pending.map(t=><button key={t.id} disabled={create.isPending} className="button-secondary" onClick={()=>create.mutate(t)}>+ {t.name}</button>)}</div></section>}
 <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{guides.map(g=><article key={g.id} className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="relative grid aspect-[16/9] place-items-center bg-emerald-50">{g.images[0]?<Image src={g.images[0].url} alt={g.images[0].alt_text} fill unoptimized className="object-cover"/>:<span className="text-4xl text-emerald-700" aria-hidden="true">▤</span>}</div><div className="p-5"><h3 className="text-xl font-bold">{g.title_en}</h3><p className="mt-2 line-clamp-3 text-sm text-slate-600">{g.content_en.overview||"Clinical content awaiting Owner entry and review."}</p><p className="my-3 text-xs text-slate-500">{g.learning_minutes?`${g.learning_minutes} min · `:""}Version {g.version}{owner?` · ${g.published?"Published":"Draft"}`:""}</p><Link className="button-secondary inline-block" href={`${owner?"/owner/learning":"/physiotherapist/learning"}/${g.id}`}>{owner?"Edit / Preview":"View Learning Guide"}</Link></div></article>)}</div>{guides.length===0&&<p className={`${card} text-slate-600`}>No published learning guides match your search yet.</p>}<p className="text-xs leading-5 text-slate-500">{note}</p></div>
}
export function LearningGuidePage({id,owner=false}:{id:string;owner?:boolean}){
 const q=useQuery({queryKey:["learning-guide",id],queryFn:()=>requestJson<Guide>(`/api/learning/${id}`)});
 const client=useQueryClient();
 const [language,setLanguage]=useState<"en"|"hi">("en"),[preview,setPreview]=useState(!owner),[clinicalApproval,setClinicalApproval]=useState(false),[publicationMessage,setPublicationMessage]=useState("");
 const publication=useMutation({mutationFn:(published:boolean)=>requestJson<Guide>(`/api/learning/${id}`,{method:"PATCH",body:JSON.stringify({published,clinical_approval:published&&clinicalApproval})}),onSuccess:async value=>{setClinicalApproval(false);setPublicationMessage(value.published?"Guide published successfully. It is now visible in the Therapist Learning Centre.":"Guide unpublished successfully. It is hidden from therapists and retained for the Owner.");await Promise.all([client.invalidateQueries({queryKey:["learning-guide",id]}),client.invalidateQueries({queryKey:["learning-library"]})])}});
 if(q.isPending)return <div className={`${card} h-64 animate-pulse`} aria-label="Loading learning guide"/>;
 if(!q.data)return <p role="alert">This guide is not available.</p>;
 const g=q.data;const content=language==="en"?g.content_en:g.content_hi;
 return <div className="mx-auto max-w-5xl space-y-6"><Link className="font-semibold text-emerald-800" href={owner?"/owner/learning":"/physiotherapist/learning"}>← Learning Centre</Link><header className={card}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-slate-500">Version {g.version} · Updated {new Date(g.updated_at).toLocaleDateString()}</p><h2 className="mt-2 text-3xl font-bold">{language==="en"?g.title_en:g.title_hi||"Hindi title awaiting review"}</h2></div><div className="flex gap-2"><button className="button-secondary" aria-pressed={language==="en"} onClick={()=>setLanguage("en")}>English</button><button className="button-secondary" aria-pressed={language==="hi"} onClick={()=>setLanguage("hi")}>हिंदी</button></div></div>{owner&&<button className="button-primary mt-4" onClick={()=>setPreview(!preview)}>{preview?"Edit Content":"Preview as Therapist"}</button>}{!g.published&&<p className="mt-3 text-sm text-amber-800">Unpublished draft — visible only to the Owner.</p>}</header>
 {owner&&<section className={card} aria-labelledby="publication-heading"><h3 id="publication-heading" className="text-xl font-bold">Publication</h3><p className="mt-2 text-sm text-slate-600">Save both languages as a draft, preview the therapist view, then confirm clinical approval before publishing.</p>{publicationMessage&&<p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-emerald-900">{publicationMessage}</p>}{publication.error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-800">{publication.error.message}</p>}<label className="mt-4 flex items-start gap-3 font-semibold"><input type="checkbox" checked={clinicalApproval} onChange={event=>setClinicalApproval(event.target.checked)}/><span>Clinical Approval: I have reviewed the complete English and Hindi guide for clinical accuracy.</span></label><div className="mt-4 flex flex-wrap gap-3">{!g.published?<button className="button-primary" disabled={!clinicalApproval||publication.isPending} onClick={()=>publication.mutate(true)}>Publish Guide</button>:<button className="button-secondary" disabled={publication.isPending} onClick={()=>publication.mutate(false)}>Unpublish Guide</button>}</div></section>}
 {owner&&!preview?<GuideEditor key={g.version} guide={g} language={language}/>:<><div className="grid gap-5">{g.sections.map(key=>{const safety=["contraindications","precautions","stop_criteria"].includes(key);const text=content[key]||"Content awaiting clinical review.";return <section className={`${card} ${safety?"border-amber-200 bg-amber-50":""}`} key={key}><h3 className="text-xl font-bold">{labels[key]?.[language==="en"?0:1]??key}</h3>{["procedure","patient_preparation","practitioner_preparation"].includes(key)?<ol className="mt-3 list-decimal space-y-2 pl-5">{text.split("\n").filter(Boolean).map((line,i)=><li key={i}>{line}</li>)}</ol>:key==="overview"?<p className="mt-3 whitespace-pre-wrap leading-7 text-slate-700">{text}</p>:<ul className="mt-3 list-disc space-y-2 pl-5">{text.split("\n").filter(Boolean).map((line,i)=><li key={i}>{line}</li>)}</ul>}</section>})}</div><section className={card}><h3 className="text-xl font-bold">{language==="en"?"Images and diagrams":"चित्र और आरेख"}</h3><div className="mt-4 grid gap-5 sm:grid-cols-2">{g.images.map(i=><figure key={i.id}><Image src={i.url} alt={i.alt_text} width={640} height={420} unoptimized className="h-auto w-full rounded-xl"/><figcaption className="mt-2 text-sm text-slate-600">{language==="en"?i.caption_en:i.caption_hi}</figcaption></figure>)}</div>{!g.images.length&&<p className="mt-3 text-sm text-slate-500">No approved images added.</p>}</section><section className={card}><h3 className="text-xl font-bold">{language==="en"?"Learning videos":"सीखने के वीडियो"}</h3>{g.videos.filter(v=>v.approved&&v.language===language).map(v=><article className="mt-5" key={v.id}><h4 className="font-semibold">{v.title}</h4><iframe title={v.title} className="mt-3 aspect-video w-full rounded-xl" src={`https://www.youtube-nocookie.com/embed/${v.video_id}`} loading="lazy" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/><p className="my-2 text-sm">{v.description}</p><a href={v.youtube_url} target="_blank" rel="noreferrer" className="font-semibold text-emerald-800 underline">Open on YouTube</a></article>)}</section></>}
 <footer className="text-xs leading-5 text-slate-500">{note}</footer></div>
}
function GuideEditor({guide:g,language}:{guide:Guide;language:"en"|"hi"}){
 const client=useQueryClient();const [message,setMessage]=useState("");
 const refresh=()=>{client.invalidateQueries({queryKey:["learning-guide",g.id]});client.invalidateQueries({queryKey:["learning-library"]})};
 const save=useMutation({mutationFn:({url,method="PATCH",body}:{url:string;method?:string;body?:BodyInit})=>requestJson(url,{method,body}),onSuccess:()=>{setMessage("Learning content saved.");refresh()}});
 const send=(suffix:string,method:string,body?:BodyInit)=>save.mutate({url:`/api/learning/${g.id}${suffix}`,method,body});
 return <div className="space-y-6">{message&&<p role="status">{message}</p>}{save.error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{save.error.message}</p>}<form key={language} className={`${card} space-y-5`} onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);const content=Object.fromEntries(g.sections.map(k=>[k,String(d.get(k)||"")]));send("","PATCH",JSON.stringify({[`title_${language}`]:d.get("title"),[`content_${language}`]:content,learning_minutes:d.get("learning_minutes")?Number(d.get("learning_minutes")):null,published:false}))}}><h3 className="text-xl font-bold">{language==="en"?"English content":"Hindi content"}</h3><label className="grid gap-2">Approved title<input name="title" className={field} required maxLength={200} defaultValue={language==="en"?g.title_en:g.title_hi}/></label>{g.sections.map(k=><label key={k} className="grid gap-2 font-semibold">{labels[k]?.[language==="en"?0:1]}<textarea className={field} name={k} rows={4} maxLength={12000} defaultValue={(language==="en"?g.content_en:g.content_hi)[k]??""}/><span className="text-xs font-normal text-slate-500">One point or procedural step per line. Use only organization-approved guidance.</span></label>)}<label className="grid gap-2">Estimated learning time (minutes, optional)<input className={field} type="number" min={1} max={1000} name="learning_minutes" defaultValue={g.learning_minutes??""}/></label><button disabled={save.isPending} className="button-primary">Save Draft</button></form>
 <section className={card}><h3 className="text-xl font-bold">Images / Diagrams</h3>{g.images.map(i=><form key={i.id} className="my-4 grid gap-2 rounded-xl border p-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();send(`/images/${i.id}`,"PATCH",new FormData(e.currentTarget))}}><Image src={i.url} alt={i.alt_text} width={160} height={100} unoptimized/><label>Replace image<input type="file" name="image" accept="image/jpeg,image/png,image/webp"/></label><label>English caption<input className={field} name="caption_en" defaultValue={i.caption_en}/></label><label>Hindi caption<input className={field} name="caption_hi" defaultValue={i.caption_hi}/></label><label>Alt text<input className={field} name="alt_text" defaultValue={i.alt_text} required/></label><label>Order<input type="number" min={0} className={field} name="sort_order" defaultValue={i.sort_order}/></label><button className="button-secondary">Update image</button><button type="button" className="text-red-700" onClick={()=>send(`/images/${i.id}`,"DELETE")}>Remove image</button></form>)}<form className="mt-4 grid gap-3" onSubmit={e=>{e.preventDefault();send("/images","POST",new FormData(e.currentTarget))}}><label>New image<input className={field} name="image" type="file" accept="image/jpeg,image/png,image/webp" required/></label><label>English caption<input className={field} name="caption_en"/></label><label>Hindi caption<input className={field} name="caption_hi"/></label><label>Alt text<input className={field} name="alt_text" required/></label><label>Order<input className={field} name="sort_order" type="number" min={0} defaultValue={g.images.length}/></label><label><input type="checkbox" name="rights_confirmed" value="true" required/> I confirm NuriPain Ease owns or has a licence to use this image.</label><button className="button-primary" disabled={save.isPending}>Upload Image</button></form></section>
 <section className={card}><h3 className="text-xl font-bold">Curated videos</h3>{g.videos.map(v=><div className="my-4 flex flex-wrap items-center gap-3 rounded-xl border p-3" key={v.id}><a href={v.youtube_url} target="_blank" rel="noreferrer" className="flex-1 font-semibold underline">{v.title}</a><label>Order<input type="number" min={0} className="w-20 rounded border p-2" defaultValue={v.sort_order} onBlur={e=>send(`/videos/${v.id}`,"PATCH",JSON.stringify({sort_order:Number(e.target.value)}))}/></label><button className="button-secondary" onClick={()=>send(`/videos/${v.id}`,"PATCH",JSON.stringify({approved:!v.approved}))}>{v.approved?"Unapprove":"Approve"}</button><button className="text-red-700" onClick={()=>send(`/videos/${v.id}`,"DELETE")}>Remove video</button></div>)}<form className="mt-4 grid gap-3" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);send("/videos","POST",JSON.stringify({title:d.get("title"),youtube_url:d.get("youtube_url"),language:d.get("language"),description:d.get("description"),sort_order:Number(d.get("sort_order")),approved:d.get("approved")==="on"}))}}><label>Video title<input className={field} name="title" required/></label><label>YouTube URL<input className={field} name="youtube_url" type="url" required/></label><label>Language<select className={field} name="language"><option value="en">English</option><option value="hi">Hindi</option></select></label><label>Description<textarea className={field} name="description"/></label><label>Order<input className={field} type="number" min={0} name="sort_order" defaultValue={g.videos.length}/></label><label><input type="checkbox" name="approved"/> I have reviewed and approved this video.</label><button className="button-primary" disabled={save.isPending}>Add Video</button></form></section></div>
}
