"use client";
import {initials} from "@/lib/staff/initials";
import Image from "next/image";
import {useQuery} from "@tanstack/react-query";
import {useEffect,useRef,useState} from "react";
import {requestJson} from "@/lib/api/client";
import type {PublicPractitioner} from "@/lib/practitioners/contracts";
const load=()=>requestJson<PublicPractitioner[]>("/api/practitioners/public");
const experienceLabel=(years:number,months:number)=>[years?`${years} year${years===1?"":"s"}`:"",months?`${months} month${months===1?"":"s"}`:""].filter(Boolean).join(" ")||"0 months";
export function PractitionerCard({item,compact=false}:{item:PublicPractitioner;compact?:boolean}){
 const expertise=item.verified_services;
 const [failedPhoto,setFailedPhoto]=useState<string|null>(null);
 const practitionerType=item.category==="WELLNESS"?"Naturopathy Practitioner":"Physiotherapist";
 return <article className={`card overflow-hidden ${compact?"w-[18rem] shrink-0 snap-start sm:w-[20rem]":""}`}><div className="relative aspect-[4/3] bg-[#edf7ef]">{item.photo_url&&failedPhoto!==item.photo_url?<Image src={item.photo_url} alt={`${item.display_name} professional profile`} fill className="object-cover" unoptimized onError={()=>setFailedPhoto(item.photo_url)}/>:<div className="grid h-full place-items-center text-5xl font-bold text-[#0b6b3a]">{initials(item.display_name)}</div>}</div><div className="p-5"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-900">{item.availability_badge??"Available with NuriPain Ease"}</span><h3 className="mt-4 font-serif text-2xl text-[#103c27]">{item.display_name}</h3>{item.age!=null&&<p className="mt-1 text-sm text-[#5b6c63]">Age: {item.age} years</p>}<p className="mt-1 text-sm font-semibold text-[#0b6b3a]">{practitionerType}</p><p className="mt-2 font-semibold text-[#0b6b3a]">{item.highest_qualification}{item.qualification_specialization?` · ${item.qualification_specialization}`:""}</p><p className="mt-2 text-sm text-[#5b6c63]">{experienceLabel(item.experience_years,item.experience_months??0)} experience · {item.gender}</p><p className="mt-1 text-sm text-[#5b6c63]">{item.average_rating!=null&&item.review_count>0?<><span className="text-amber-500" aria-label={`${item.average_rating.toFixed(1)} out of 5 stars`}>{"★".repeat(Math.round(item.average_rating))}{"☆".repeat(5-Math.round(item.average_rating))}</span> {item.average_rating.toFixed(1)} · {item.review_count} review{item.review_count===1?"":"s"}</>:"No ratings yet"}</p>{item.languages.length>0&&<p className="mt-1 text-sm text-[#5b6c63]">Languages: {item.languages.join(", ")}</p>}{item.service_area&&<p className="mt-1 text-sm text-[#5b6c63]">Service area: {item.service_area}</p>}{expertise.length>0&&<div className="mt-4 flex flex-wrap gap-2">{expertise.slice(0,3).map(x=><span key={x} className="rounded-full border border-[#0b6b3a]/20 px-3 py-1 text-xs">{x}</span>)}{expertise.length>3&&<span className="text-xs">+{expertise.length-3} more</span>}</div>}{item.bio&&<p className="mt-4 line-clamp-3 text-sm leading-6 text-[#5b6c63]">{item.bio}</p>}</div></article>
}
export function PublicPractitionerDirectory(){const q=useQuery({queryKey:["public-practitioners"],queryFn:load});return <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{q.data?.map(x=><PractitionerCard key={x.id} item={x}/>)}{q.isPending&&<p>Loading verified practitioners…</p>}{q.data?.length===0&&<p className="text-[#5b6c63]">Verified practitioner profiles will appear here as they become available.</p>}</div>}
export function PractitionerCarousel(){
 const q=useQuery({queryKey:["public-practitioners"],queryFn:load}),track=useRef<HTMLDivElement>(null),[paused,setPaused]=useState(false);
 const move=(direction:1|-1)=>{const e=track.current;if(!e)return;const distance=Math.min(336,e.clientWidth*.9)*direction,atEnd=e.scrollLeft+e.clientWidth>=e.scrollWidth-8,atStart=e.scrollLeft<=8;e.scrollTo({left:direction>0&&atEnd?0:direction<0&&atStart?e.scrollWidth:e.scrollLeft+distance,behavior:"smooth"})};
 useEffect(()=>{if(paused||(q.data?.length??0)<2)return;const timer=window.setInterval(()=>move(1),5000);return()=>window.clearInterval(timer)},[paused,q.data?.length]);
 return <section aria-labelledby="experienced-practitioners-heading" className="min-w-0 max-w-full rounded-3xl border border-emerald-100 bg-white p-5 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#9b7427]">NuriPain Ease verified</p><h2 id="experienced-practitioners-heading" className="mt-2 text-3xl font-bold text-slate-950">Available Therapists</h2><p className="mt-2 text-slate-600">Meet our verified professionals available with NuriPain Ease.</p></div>{(q.data?.length??0)>1&&<div className="flex gap-2"><button type="button" aria-label="Previous practitioners" onClick={()=>move(-1)} className="min-h-11 rounded-xl border border-emerald-700 px-4 font-bold text-emerald-800">←</button><button type="button" aria-label="Next practitioners" onClick={()=>move(1)} className="min-h-11 rounded-xl border border-emerald-700 px-4 font-bold text-emerald-800">→</button></div>}</div>{q.isPending&&<p className="mt-6 text-slate-600">Loading verified practitioners…</p>}{q.isError&&<p className="mt-6 text-red-700">Practitioner profiles could not be loaded.</p>}{q.data?.length===0&&<p className="mt-6 rounded-2xl border border-dashed p-6 text-center text-slate-600">Verified practitioner profiles will appear here as they become available.</p>}{(q.data?.length??0)>0&&<div ref={track} tabIndex={0} aria-label="Verified practitioner carousel" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocus={()=>setPaused(true)} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setPaused(false)}} className="mt-6 flex max-w-full snap-x snap-mandatory gap-5 overflow-x-auto scroll-smooth pb-3 focus-visible:outline-2 focus-visible:outline-emerald-700">{q.data?.map(x=><PractitionerCard key={x.id} item={x} compact/>)}</div>}</section>
}
