import Link from "next/link";
import {PublicShell} from "@/components/public/public-shell";

const benefits=[
  ["Verified Professional Profile","Present your qualifications and approved expertise through a professional profile."],
  ["Patient Opportunities","Be considered for suitable home visits as patient needs and availability align."],
  ["Flexible Availability","Share the days and hours that work for your practice."],
  ["Skill-Based Matching","Eligible assignments connect patient requirements with the therapies you currently offer."],
  ["Professional Ratings","Build a record of moderated feedback from completed visits."],
  ["Organized Schedule","Keep confirmed visits and your availability in one place."],
  ["Transparent Visit Workflow","Follow a structured process from assignment through visit verification."],
  ["Structured Professional Record","Keep your application, credentials and professional history connected."],
];
const steps=["Enter Personal & Professional Details","Upload Profile Photograph","Verify Mobile Number by OTP","Create Password & Confirm Password","Upload Mandatory Documents","Review Complete Application","Correct Any Issue if Needed","Submit Application","JeevaSetu Reviews & Approves","Start Receiving Eligible Assignments"];

export function RecruitmentPage(){return <PublicShell><main>
  <section className="section bg-[#f5f5eb]"><div className="site-container grid items-center gap-10 lg:grid-cols-[1.2fr_1fr]">
    <div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Open to work with JeevaSetu</p><h1 className="mt-5 max-w-2xl font-serif text-4xl leading-tight text-emerald-950 sm:text-6xl">Grow Your Practice<br/>With JeevaSetu</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Serve patients at home, build professional visibility and work through a structured, verified healthcare platform.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="button-primary" href="/therapist-register">Apply to Join</Link><Link className="button-secondary" href="/therapist-login">Already Registered? Sign In</Link></div><p className="mt-5 text-sm text-slate-500">For Physiotherapists and Naturopathy / Wellness Practitioners.</p></div>
    <aside aria-label="Professional profile preview" className="rounded-[2rem] bg-emerald-950 p-6 shadow-xl sm:p-9"><p className="text-xs uppercase tracking-widest text-emerald-200">Your professional presence</p><div className="mt-5 rounded-2xl bg-white p-6"><div className="flex items-center gap-4"><div aria-hidden="true" className="grid size-16 place-items-center rounded-full bg-emerald-100 text-3xl text-emerald-800">✚</div><div><h2 className="font-serif text-2xl text-emerald-950">Your practitioner profile</h2><p className="mt-1 text-sm text-emerald-700">Verified after approval</p></div></div><p className="mt-6 text-xs font-bold uppercase text-slate-500">Therapy expertise</p><p className="mt-2 text-slate-700">Your approved skills, qualifications and experience</p><div className="mt-5 grid gap-3 border-t pt-5"><p className="text-sm text-slate-600">◷ Availability that fits your schedule</p><p className="text-sm text-slate-600">☆ Ratings from completed visits</p></div></div><p className="mt-5 text-sm leading-6 text-emerald-100">Illustrative profile preview. Your public information reflects your verified professional record.</p></aside>
  </div></section>
  <section className="section"><div className="site-container"><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">Why join JeevaSetu</p><h2 className="mt-3 font-serif text-3xl text-emerald-950 sm:text-4xl">More room to focus on your patients.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{benefits.map(([title,body],i)=><article key={title} className="rounded-2xl border border-emerald-100 bg-white p-6"><span className="text-sm font-bold text-emerald-600">0{i+1}</span><h3 className="mt-4 text-lg font-bold text-emerald-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{body}</p></article>)}</div><p className="mt-5 text-sm text-slate-500">Opportunities depend on patient demand, verified skills, service areas and availability. Assignments and earnings are not guaranteed.</p></div></section>
  <section className="section bg-[#f5f5eb]"><div className="site-container"><h2 className="font-serif text-3xl text-emerald-950">From application to eligible assignments</h2><p className="mt-3 text-slate-600">One complete application. Time to review. A clear approval process.</p><ol className="mt-8 grid gap-4 sm:grid-cols-2">{steps.map((step,i)=><li key={step} className="flex items-center gap-4 rounded-2xl bg-white p-5"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-emerald-100 font-bold text-emerald-800">{i+1}</span><span className="font-semibold text-emerald-950">{step}</span></li>)}</ol></div></section>
  <section className="section"><div className="site-container grid gap-8 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">Trust & privacy</p><h2 className="mt-3 font-serif text-3xl text-emerald-950">Your credentials deserve careful handling.</h2><p className="mt-5 leading-7 text-slate-600">Private documents are available to you and authorized reviewers. Your date of birth, mobile number and government identity proof remain private. Your public profile shows only safe professional information, including derived age.</p></div><div className="rounded-[2rem] bg-emerald-950 p-8 text-white"><h2 className="font-serif text-3xl">Ready to Join JeevaSetu?</h2><p className="mt-4 leading-7 text-emerald-100">Have your photograph, government identity PDF and qualification certificate PDF ready. You can review and correct your details before submitting.</p><div className="mt-6 flex flex-wrap gap-4"><Link href="/therapist-register" className="rounded-xl bg-white px-5 py-3 font-bold text-emerald-950">Start Application</Link><Link href="/therapist-login" className="px-2 py-3 font-semibold underline underline-offset-4">Practitioner Sign In</Link></div></div></div></section>
</main></PublicShell>}
