import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import {beforeEach,expect,it,vi,type MockInstance} from "vitest";
import {PractitionerRegistration} from "./self-registration";
import {RecruitmentPage} from "./recruitment-page";

vi.mock("@/components/public/public-shell",()=>({PublicShell:({children}:{children:React.ReactNode})=><>{children}</>}));
vi.mock("@/lib/auth/msg91-widget",()=>({loadOtpWidgetConfig:async()=>({enabled:false}),sendMsg91Otp:vi.fn(),verifyMsg91Otp:vi.fn()}));
const options={clinics:[{id:"clinic",slug:"meerut"}],therapies:[{id:"therapy",name:"Basti"}],service_areas:[{id:"area",name:"Meerut"}]};
let fetchMock:MockInstance<typeof fetch>;
beforeEach(()=>{
 vi.restoreAllMocks();
 Object.defineProperty(URL,"createObjectURL",{value:vi.fn(()=>"blob:preview"),configurable:true});Object.defineProperty(URL,"revokeObjectURL",{value:vi.fn(),configurable:true});HTMLElement.prototype.scrollIntoView=vi.fn();
 fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(async input=>{
  const url=String(input);return new Response(JSON.stringify(url.includes("registration-options")?options:url.includes("dob-preview")?{age:36}:url.includes("/issue")?{verification_id:"id"}:url.includes("/verify")?{token:"proof"}:{status:"SUBMITTED"}),{status:200});
 });
});
function wrap(){render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><PractitionerRegistration/></QueryClientProvider>)}
async function details(){wrap();await screen.findByLabelText("Full Name *");for(const [label,value] of [["Full Name *","Test Practitioner"],["Email *","test@example.com"],["Mobile Number *","+919876543210"],["Date of Birth *","1990-08-15"],["Highest Qualification *","BPT"],["Experience *","4.6"],["Clinic *","clinic"],["Languages Known *","Hindi, English, hindi"],["Professional Bio","Home care professional"]])fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.click(screen.getByRole("checkbox",{name:"Basti"}));fireEvent.click(screen.getByRole("checkbox",{name:"Meerut"}));}
function uploadPhoto(name="photo.png"){fireEvent.change(screen.getByLabelText("Profile Photo"),{target:{files:[new File(["photo"],name,{type:"image/png"})]}})}
async function review(){await details();uploadPhoto();fireEvent.click(screen.getByRole("button",{name:"Continue to Mobile Verification"}));fireEvent.change(await screen.findByLabelText("Enter OTP"),{target:{value:"123456"}});fireEvent.click(screen.getByRole("button",{name:"Verify OTP"}));await screen.findByLabelText("Password");fireEvent.change(screen.getByLabelText("Password"),{target:{value:"StrongPass1!"}});fireEvent.change(screen.getByLabelText("Confirm Password"),{target:{value:"StrongPass1!"}});fireEvent.click(screen.getByRole("button",{name:"Continue to Documents"}));expect(screen.getByRole("button",{name:"Continue to Review"})).toBeDisabled();for(const label of ["Government Identity Proof *","Qualification Certificate *"])fireEvent.change(screen.getByLabelText(label),{target:{files:[new File(["%PDF-1.4"],"proof.pdf",{type:"application/pdf"})]}});fireEvent.click(screen.getByRole("button",{name:"Continue to Review"}));await screen.findByText("Age: 36 years");}
it("shows recruitment benefits, ten actual stages and correct links",()=>{render(<RecruitmentPage/>);expect(screen.getByText("Why join NuriPain Ease")).toBeInTheDocument();expect(screen.getByText("Structured Professional Record")).toBeInTheDocument();expect(screen.getAllByRole("listitem")).toHaveLength(10);expect(screen.getByRole("link",{name:"Apply to Join"})).toHaveAttribute("href","/therapist-register");expect(screen.getByRole("link",{name:"Practitioner Sign In"})).toHaveAttribute("href","/therapist-login")});
it("requires photo and DOB before OTP and previews/replaces/removes photo",async()=>{await details();expect(screen.getByText("Enter mobile number in +91XXXXXXXXXX format.")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Continue to Mobile Verification"}));expect(await screen.findByRole("alert")).toHaveTextContent("Profile photo is required");uploadPhoto();expect(screen.getByAltText("Profile photo preview")).toBeInTheDocument();uploadPhoto("replacement.png");expect(screen.getByText("replacement.png")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Remove"}));expect(screen.queryByAltText("Profile photo preview")).not.toBeInTheDocument();uploadPhoto();fireEvent.change(screen.getByLabelText("Date of Birth *"),{target:{value:""}});fireEvent.click(screen.getByRole("button",{name:"Continue to Mobile Verification"}));expect(await screen.findByRole("alert")).toHaveTextContent("Date of birth is required");expect(fetchMock.mock.calls.some(([url])=>String(url).includes("/issue"))).toBe(false)});
it("reviews all data, preserves OTP across section edits and submits only at the end",async()=>{await review();expect(screen.getByText("4 years 6 months")).toBeInTheDocument();expect(screen.getByText("Hindi, English")).toBeInTheDocument();expect(screen.getByText("Home care professional")).toBeInTheDocument();expect(fetchMock.mock.calls.some(([url])=>String(url).includes("register-complete"))).toBe(false);for(const section of ["Password","Documents","Details"]){fireEvent.click(screen.getByRole("button",{name:`Edit ${section}`}));if(section==="Details")fireEvent.change(screen.getByLabelText("Professional Bio"),{target:{value:"Updated bio"}});fireEvent.click(screen.getByRole("button",{name:"Continue"}));await screen.findByRole("button",{name:"Submit Application"});}expect(screen.getByText("Updated bio")).toBeInTheDocument();expect(fetchMock.mock.calls.filter(([url])=>String(url).includes("/issue"))).toHaveLength(1);fireEvent.click(screen.getByRole("button",{name:"Submit Application"}));expect(await screen.findByText("PENDING APPROVAL")).toBeInTheDocument();const sent=fetchMock.mock.calls.find(([url])=>String(url).includes("register-complete"))![1]!.body as FormData;expect(sent.get("mobile_verification_token")).toBe("proof");expect(sent.get("working_days")).toBe("[0,1,2,3,4,5]");expect(sent.get("experience_months")).toBe("6");expect(fetchMock.mock.calls.some(([url])=>String(url).includes("availability/rules"))).toBe(false)});
it("invalidates proof when reviewed mobile changes",async()=>{await review();fireEvent.click(screen.getByRole("button",{name:"Edit Details"}));fireEvent.change(screen.getByLabelText("Mobile Number *"),{target:{value:"+919876543211"}});fireEvent.click(screen.getByRole("button",{name:"Continue"}));await screen.findByLabelText("Enter OTP");expect(fetchMock.mock.calls.filter(([url])=>String(url).includes("/issue"))).toHaveLength(2);expect(screen.queryByRole("button",{name:"Submit Application"})).not.toBeInTheDocument()});
it("blocks duplicates before OTP",async()=>{await details();uploadPhoto();fetchMock.mockImplementation(async(input:unknown)=>new Response(JSON.stringify(String(input).includes("dob-preview")?{age:36}:{mobile:["This mobile number is already registered. Please sign in."]}),{status:String(input).includes("dob-preview")?200:400}));fireEvent.click(screen.getByRole("button",{name:"Continue to Mobile Verification"}));await waitFor(()=>expect(screen.getByRole("alert")).toHaveTextContent("already registered"));expect(fetchMock.mock.calls.some(([url])=>String(url).includes("/issue"))).toBe(false)});
