"use client";
import Link from "next/link";
import {useState} from "react";
import {requestJson} from "@/lib/api/client";
import {PasswordCreationFields,isStrongPassword} from "@/components/auth/password-creation-fields";
import {loadOtpWidgetConfig,sendMsg91Otp,verifyMsg91Otp,type OtpWidgetConfig} from "@/lib/auth/msg91-widget";
export function TherapistSecurity({mobile}:{mobile:string}){
 const [mode,setMode]=useState(""),[current,setCurrent]=useState(""),[next,setNext]=useState(""),[confirm,setConfirm]=useState(""),[number,setNumber]=useState(""),[otp,setOtp]=useState(""),[id,setId]=useState(""),[config,setConfig]=useState<OtpWidgetConfig>({enabled:false}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function perform(action:()=>Promise<void>){setBusy(true);setMessage("");try{await action()}catch(e){setMessage(e instanceof Error?e.message:"Please try again.")}finally{setBusy(false)}}
 async function done(){setCurrent("");setNext("");setConfirm("");setOtp("");await requestJson("/api/session/logout",{method:"POST"});window.location.assign("/therapist-login")}
 return <div className="mt-4 space-y-4"><p>Verified mobile: <strong>{mobile}</strong></p><div className="flex flex-wrap gap-3"><button className="button-secondary" onClick={()=>{setMode("mobile");setId("")}}>Change Mobile via OTP</button><button className="button-secondary" onClick={()=>setMode("password")}>Change Password</button><Link className="button-secondary" href="/forgot-password?context=therapist">Forgot Password?</Link></div>{mode&&<div className="max-w-lg space-y-3 rounded-xl bg-slate-50 p-4"><label className="grid gap-2">Current password<input type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} className="min-h-12 rounded-xl border px-3"/></label>{mode==="password"?<form onSubmit={e=>{e.preventDefault();perform(async()=>{await requestJson("/api/session/change-password",{method:"POST",body:JSON.stringify({old_password:current,new_password:next,confirm_password:confirm})});await done()})}}><PasswordCreationFields password={next} confirmPassword={confirm} onPasswordChange={setNext} onConfirmPasswordChange={setConfirm}/><button className="button-primary mt-3" disabled={busy||!current||!isStrongPassword(next)||next!==confirm}>Save Password</button></form>:<><label className="grid gap-2">New registered mobile<input value={number} maxLength={10} inputMode="numeric" onChange={e=>{setNumber(e.target.value.replace(/\D/g,""));setId("");setOtp("")}} className="min-h-12 rounded-xl border px-3"/></label><p className="text-sm">Enter a valid 10-digit Indian mobile number.</p><button className="button-secondary" disabled={busy||!current||!/^[6-9]\d{9}$/.test(number)} onClick={()=>perform(async()=>{const c=await loadOtpWidgetConfig();const issued=await requestJson<{verification_id:string}>("/api/booking-otp/issue",{method:"POST",body:JSON.stringify({mobile_number:number})});if(c.enabled)await sendMsg91Otp(c,number);setConfig(c);setId(issued.verification_id)})}>{id?"Resend OTP":"Send OTP"}</button>{id&&<><label className="grid gap-2">OTP for new mobile<input value={otp} maxLength={6} inputMode="numeric" onChange={e=>setOtp(e.target.value.replace(/\D/g,""))} className="min-h-12 rounded-xl border px-3"/></label><button className="button-primary" disabled={busy||otp.length!==6} onClick={()=>perform(async()=>{const provider=config.enabled?{access_token:await verifyMsg91Otp(config,otp)}:{otp};const proof=await requestJson<{token:string}>("/api/booking-otp/verify",{method:"POST",body:JSON.stringify({verification_id:id,mobile_number:number,...provider})});await requestJson("/api/staff/me/change-mobile",{method:"POST",body:JSON.stringify({mobile_number:number,current_password:current,booking_verification_token:proof.token})});await done()})}>Verify and Change Mobile</button></>}</>}<button className="button-secondary" onClick={()=>{setMode("");setCurrent("");setOtp("");setNext("");setConfirm("")}}>Cancel</button></div>}{message&&<p role="alert" className="text-red-700">{message}</p>}</div>
}
