# Generated by Django 6.0.7 on 2026-08-06 10:26

import apps.patients.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("patient_identifier", models.CharField(editable=False, max_length=16)),
                ("full_name", models.CharField(max_length=160)),
                (
                    "mobile_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[6-9]\\d{9}$", "Enter a valid 10-digit Indian mobile number."
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("FEMALE", "Female"),
                            ("MALE", "Male"),
                            ("OTHER", "Other"),
                            ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                        ],
                        max_length=24,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "profile_photo",
                    models.FileField(
                        blank=True,
                        upload_to="patients/profile-photos/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("jpg", "jpeg", "png", "webp")
                            ),
                            apps.patients.models.validate_photo_size,
                        ],
                    ),
                ),
                ("emergency_contact_name", models.CharField(max_length=160)),
                ("emergency_contact_relationship", models.CharField(max_length=80)),
                (
                    "emergency_contact_mobile",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[6-9]\\d{9}$", "Enter a valid 10-digit Indian mobile number."
                            )
                        ],
                    ),
                ),
                ("guardian_name", models.CharField(blank=True, max_length=160)),
                ("guardian_relationship", models.CharField(blank=True, max_length=80)),
                (
                    "guardian_mobile",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[6-9]\\d{9}$", "Enter a valid 10-digit Indian mobile number."
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_profiles",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_profiles",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("full_name",),
            },
        ),
        migrations.CreateModel(
            name="PatientAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(default="Home", max_length=80)),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("landmark", models.CharField(blank=True, max_length=160)),
                ("city", models.CharField(max_length=120)),
                ("region", models.CharField(max_length=120)),
                (
                    "pin_code",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[1-9]\\d{5}$", "Enter a valid 6-digit PIN code."
                            )
                        ],
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="addresses",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_primary", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="CaregiverRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("full_name", models.CharField(max_length=160)),
                ("relationship", models.CharField(max_length=80)),
                (
                    "mobile_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[6-9]\\d{9}$", "Enter a valid 10-digit Indian mobile number."
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="caregivers",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("next_value", models.PositiveBigIntegerField(default=1)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_sequence",
                        to="tenancy.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientStatusAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("previous_status", models.BooleanField()),
                ("new_status", models.BooleanField()),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_audits",
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="patientprofile",
            index=models.Index(
                fields=["organization", "clinic", "is_active"], name="patient_org_clinic_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientprofile",
            index=models.Index(fields=["organization", "full_name"], name="patient_org_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="patientprofile",
            constraint=models.UniqueConstraint(
                fields=("organization", "patient_identifier"), name="patient_org_identifier_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="patientprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("organization", "user"),
                name="patient_org_user_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("organization", "mobile_number"),
                name="patient_active_org_mobile_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("date_of_birth__isnull", False), ("age__isnull", False), _connector="OR"
                ),
                name="patient_dob_or_age_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientaddress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_primary", True)),
                fields=("patient",),
                name="patient_one_primary_address",
            ),
        ),
    ]
