# Generated by Django 6.0.7 on 2026-08-03 11:38

import apps.accounts.managers
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "Registration"),
                            ("LOGIN", "Login"),
                            ("REFRESH", "Token refresh"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGE", "Password change"),
                            ("PASSWORD_RESET_REQUEST", "Password reset request"),
                            ("PASSWORD_RESET_COMPLETE", "Password reset complete"),
                            ("PROFILE_UPDATE", "Profile update"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILURE", "Failure")], max_length=8
                    ),
                ),
                ("identifier_hash", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PasswordResetRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super administrator"),
                            ("ORGANIZATION_ADMIN", "Organization administrator"),
                            ("CLINIC_ADMIN", "Clinic administrator"),
                            ("RECEPTION", "Reception"),
                            ("THERAPIST", "Therapist"),
                            ("AYURVEDA_DOCTOR", "Ayurveda doctor"),
                            ("YOGA_TRAINER", "Yoga trainer"),
                            ("HOMECARE_EXECUTIVE", "Homecare executive"),
                            ("PATIENT", "Patient"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["mobile_number", "is_active", "is_enabled"],
                name="acct_user_mobile_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "is_active", "is_enabled"], name="acct_user_email_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email", ""), _negated=True),
                name="accounts_user_email_ci_uniq",
            ),
        ),
        migrations.AddField(
            model_name="authenticationauditevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authentication_audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="passwordresetrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="password_reset_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_assignments",
                to="tenancy.clinic",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_assignments",
                to="tenancy.organization",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="authenticationauditevent",
            index=models.Index(
                fields=["event", "outcome", "created_at"], name="acct_audit_event_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authenticationauditevent",
            index=models.Index(fields=["user", "created_at"], name="acct_audit_user_time_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresetrequest",
            index=models.Index(
                fields=["user", "used_at", "expires_at"], name="acct_reset_user_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignment",
            index=models.Index(fields=["user", "is_active"], name="acct_role_user_active_idx"),
        ),
        migrations.AddIndex(
            model_name="roleassignment",
            index=models.Index(
                fields=["organization", "is_active"], name="acct_role_org_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignment",
            index=models.Index(fields=["clinic", "is_active"], name="acct_role_clinic_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("clinic__isnull", True), ("organization__isnull", True)),
                fields=("user", "role"),
                name="acct_role_platform_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("clinic__isnull", True), ("organization__isnull", False)),
                fields=("user", "role", "organization"),
                name="acct_role_org_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("clinic__isnull", False)),
                fields=("user", "role", "clinic"),
                name="acct_role_clinic_uniq",
            ),
        ),
    ]
