# Generated by Django 6.0.7 on 2026-08-05 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_authenticationauditevent_passwordresetrequest_and_more"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("ROLE_ASSIGNED", "Role assigned"),
                            ("ROLE_CHANGED", "Role changed"),
                            ("ROLE_ACTIVATED", "Role activated"),
                            ("ROLE_DISABLED", "Role disabled"),
                            ("PRIVILEGE_ESCALATION", "Privilege escalation attempted"),
                            ("CROSS_TENANT", "Cross-tenant role operation attempted"),
                            ("FINAL_OWNER", "Final-owner protection attempted"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "old_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("PHYSIOTHERAPIST", "Physiotherapist"),
                            ("CUSTOMER", "Customer"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "new_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("PHYSIOTHERAPIST", "Physiotherapist"),
                            ("CUSTOMER", "Customer"),
                        ],
                        max_length=32,
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="roleassignment",
            name="acct_role_platform_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="roleassignment",
            name="acct_role_org_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="roleassignment",
            name="acct_role_clinic_uniq",
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_role_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="clinic_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_assignments",
                to="tenancy.clinicmembership",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="disabled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="disabled_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="organization_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_assignments",
                to="tenancy.organizationmembership",
            ),
        ),
        migrations.AlterField(
            model_name="roleassignment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_assignments",
                to="tenancy.organization",
            ),
        ),
        migrations.AlterField(
            model_name="roleassignment",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("MANAGER", "Manager"),
                    ("PHYSIOTHERAPIST", "Physiotherapist"),
                    ("CUSTOMER", "Customer"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignment",
            index=models.Index(fields=["role", "is_active"], name="acct_role_kind_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("clinic__isnull", True), ("is_active", True)),
                fields=("user", "role", "organization"),
                name="acct_role_active_org_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("clinic__isnull", False), ("is_active", True)),
                fields=("user", "role", "organization", "clinic"),
                name="acct_role_active_clinic_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("disabled_at__isnull", True), ("is_active", True)),
                    ("is_active", False),
                    _connector="OR",
                ),
                name="acct_role_active_not_disabled",
            ),
        ),
        migrations.AddField(
            model_name="roleauditevent",
            name="acting_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_audit_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roleauditevent",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_audit_events",
                to="tenancy.clinic",
            ),
        ),
        migrations.AddField(
            model_name="roleauditevent",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_audit_events",
                to="tenancy.organization",
            ),
        ),
        migrations.AddField(
            model_name="roleauditevent",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_audit_targets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="roleauditevent",
            index=models.Index(
                fields=["organization", "created_at"], name="acct_rbaudit_org_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roleauditevent",
            index=models.Index(fields=["event", "created_at"], name="acct_rbaudit_event_time_idx"),
        ),
    ]
