# Generated by Django 6.0.7 on 2026-08-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_roleauditevent_and_more"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("role", "OWNER"), _negated=True),
                    models.Q(("clinic__isnull", True), ("clinic_membership__isnull", True)),
                    _connector="OR",
                ),
                name="acct_role_owner_org_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("role", "PHYSIOTHERAPIST"), _negated=True),
                    models.Q(("clinic__isnull", False), ("clinic_membership__isnull", False)),
                    _connector="OR",
                ),
                name="acct_role_physio_clinic_scope",
            ),
        ),
    ]
