# Generated by Django 6.0.7 on 2026-08-07 17:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0007_visitverification_visitverificationauditevent_and_more"),
        ("staff", "0002_seed_staff_options"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PractitionerApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("CORRECTION_REQUIRED", "Correction required"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PHYSIOTHERAPIST", "Physiotherapist"),
                            ("WELLNESS", "Naturopathy / Wellness Practitioner"),
                        ],
                        max_length=24,
                    ),
                ),
                ("full_legal_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("FEMALE", "Female"),
                            ("MALE", "Male"),
                            ("OTHER", "Other"),
                            ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                        ],
                        max_length=24,
                    ),
                ),
                ("mobile_number", models.CharField(max_length=16)),
                ("alternate_mobile", models.CharField(blank=True, max_length=16)),
                ("email", models.EmailField(max_length=254)),
                (
                    "profile_photo",
                    models.FileField(blank=True, upload_to="practitioners/private/profile/%Y/%m/"),
                ),
                ("current_address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=120)),
                (
                    "pin_code",
                    models.CharField(
                        max_length=6,
                        validators=[django.core.validators.RegexValidator("^[1-9]\\d{5}$")],
                    ),
                ),
                (
                    "highest_qualification",
                    models.CharField(
                        choices=[
                            ("BPT", "BPT"),
                            ("MPT", "MPT"),
                            ("DPT", "DPT"),
                            ("OTHER_PHYSIOTHERAPY", "Other physiotherapy qualification"),
                            ("WELLNESS_CERTIFICATION", "Wellness qualification/certification"),
                        ],
                        max_length=32,
                    ),
                ),
                ("specialization", models.CharField(blank=True, max_length=160)),
                ("college_institute", models.CharField(max_length=255)),
                ("awarding_body", models.CharField(max_length=255)),
                (
                    "passing_year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1950),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                ("registration_number", models.CharField(blank=True, max_length=120)),
                ("registration_authority", models.CharField(blank=True, max_length=255)),
                ("registration_expiry", models.DateField(blank=True, null=True)),
                (
                    "experience_years",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(80)]
                    ),
                ),
                (
                    "experience_months",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(11)]
                    ),
                ),
                ("recent_organization", models.CharField(blank=True, max_length=255)),
                ("previous_experience", models.CharField(blank=True, max_length=1000)),
                ("has_home_service_experience", models.BooleanField(default=False)),
                ("bio", models.TextField(max_length=1500)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("correction_reason", models.CharField(blank=True, max_length=500)),
                ("rejection_reason", models.CharField(blank=True, max_length=500)),
                ("internal_review_notes", models.TextField(blank=True, max_length=2000)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practitioner_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practitioner_applications",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practitioner_applications",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_practitioner_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PractitionerAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("REVIEW_STARTED", "Review started"),
                            ("CORRECTION_REQUESTED", "Correction requested"),
                            ("RESUBMITTED", "Resubmitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("DOCUMENT_VERIFIED", "Document verified"),
                            ("COMPETENCY_VERIFIED", "Competency verified"),
                            ("OPEN_TO_WORK_CHANGED", "Open to work changed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="practitioners.practitionerapplication",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PractitionerDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("GOVERNMENT_ID", "Government identity proof"),
                            ("QUALIFICATION", "Highest qualification certificate"),
                            ("DEGREE", "Degree or diploma"),
                            ("REGISTRATION", "Registration or licence"),
                            ("EXPERIENCE", "Experience certificate"),
                            ("TRAINING", "Specialization or training certificate"),
                            ("RESUME", "Resume or CV"),
                            ("ADDITIONAL", "Additional certificate"),
                        ],
                        max_length=24,
                    ),
                ),
                ("file", models.FileField(upload_to="practitioners/private/documents/%Y/%m/")),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveIntegerField()),
                ("checksum_sha256", models.CharField(max_length=64)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="practitioners.practitionerapplication",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PractitionerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PHYSIOTHERAPIST", "Physiotherapist"),
                            ("WELLNESS", "Naturopathy / Wellness Practitioner"),
                        ],
                        max_length=24,
                    ),
                ),
                ("qualification_specialization", models.CharField(blank=True, max_length=160)),
                ("is_approved", models.BooleanField(default=True)),
                ("is_publicly_visible", models.BooleanField(default=False)),
                ("is_open_to_work", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practitioner_profiles",
                        to="tenancy.clinic",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practitioner_profiles",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "staff_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practitioner_profile",
                        to="staff.staffprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practitioner_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="practitionerapplication",
            name="approved_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_application",
                to="practitioners.practitionerprofile",
            ),
        ),
        migrations.CreateModel(
            name="PractitionerCompetency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "experience_months",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(960)]
                    ),
                ),
                (
                    "supporting_certificate",
                    models.FileField(
                        blank=True, upload_to="practitioners/private/competencies/%Y/%m/"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competencies",
                        to="practitioners.practitionerapplication",
                    ),
                ),
                (
                    "therapy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practitioner_competencies",
                        to="appointments.therapyoption",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "therapy"), name="pract_app_therapy_uniq"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="practitionerprofile",
            index=models.Index(
                fields=["is_approved", "is_publicly_visible", "is_open_to_work"],
                name="pract_profile_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="practitionerprofile",
            constraint=models.UniqueConstraint(
                fields=("user", "organization"), name="pract_profile_user_org_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="practitionerapplication",
            index=models.Index(
                fields=["organization", "status", "created_at"], name="pract_app_org_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="practitionerapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("DRAFT", "SUBMITTED", "UNDER_REVIEW", "CORRECTION_REQUIRED"))
                ),
                fields=("applicant", "organization"),
                name="pract_one_open_app_uniq",
            ),
        ),
    ]
