# Generated by Django 6.0.7 on 2026-08-10 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practitioners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="practitionerapplication",
            name="availability_notes",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="practitionerapplication",
            name="last_completed_step",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="awarding_body",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="bio",
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="category",
            field=models.CharField(
                choices=[
                    ("PHYSIOTHERAPIST", "Physiotherapist"),
                    ("WELLNESS", "Naturopathy / Wellness Practitioner"),
                ],
                default="PHYSIOTHERAPIST",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="college_institute",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="current_address",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="full_legal_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="gender",
            field=models.CharField(
                choices=[
                    ("FEMALE", "Female"),
                    ("MALE", "Male"),
                    ("OTHER", "Other"),
                    ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                ],
                default="PREFER_NOT_TO_SAY",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="highest_qualification",
            field=models.CharField(
                choices=[
                    ("BPT", "BPT"),
                    ("MPT", "MPT"),
                    ("DPT", "DPT"),
                    ("OTHER_PHYSIOTHERAPY", "Other physiotherapy qualification"),
                    ("WELLNESS_CERTIFICATION", "Wellness qualification/certification"),
                ],
                default="BPT",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="passing_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1950),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="pin_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                validators=[django.core.validators.RegexValidator("^[1-9]\\d{5}$")],
            ),
        ),
        migrations.AlterField(
            model_name="practitionerapplication",
            name="state",
            field=models.CharField(blank=True, default="Uttar Pradesh", max_length=120),
        ),
    ]
