# Generated by Django 6.0.7 on 2026-09-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practitioners", "0003_resubmitted_and_unique_documents"),
        ("staff", "0006_staffprofile_experience_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="practitionerapplication",
            name="qualification_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="practitionerapplication",
            name="service_areas",
            field=models.ManyToManyField(
                blank=True, related_name="practitioner_applications", to="staff.servicearea"
            ),
        ),
        migrations.AddField(
            model_name="practitionerapplication",
            name="working_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="practitionerapplication",
            name="working_hours_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="practitionerapplication",
            name="working_hours_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
