# Generated by Django 6.0.7 on 2026-09-06 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practitioners", "0004_practitionerapplication_qualification_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="practitionerauditevent",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_events",
                to="practitioners.practitionerprofile",
            ),
        ),
        migrations.AddField(
            model_name="practitionerdocument",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credential_documents",
                to="practitioners.practitionerprofile",
            ),
        ),
        migrations.AddField(
            model_name="practitionerprofile",
            name="pending_credentials",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="practitionerauditevent",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_events",
                to="practitioners.practitionerapplication",
            ),
        ),
        migrations.AlterField(
            model_name="practitionerdocument",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="practitioners.practitionerapplication",
            ),
        ),
    ]
