# Generated by Django 6.0.7 on 2026-09-06 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0021_offer_only_free_therapy_addons"),
        ("practitioners", "0005_profile_audit_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TherapyLearningGuide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title_en", models.CharField(max_length=200)),
                ("title_hi", models.CharField(blank=True, max_length=200)),
                ("content_en", models.JSONField(blank=True, default=dict)),
                ("content_hi", models.JSONField(blank=True, default=dict)),
                ("learning_minutes", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("published", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "therapy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_guide",
                        to="appointments.therapyoption",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TherapyLearningImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("image", models.ImageField(upload_to="learning/images/%Y/%m/")),
                ("caption_en", models.CharField(blank=True, max_length=300)),
                ("caption_hi", models.CharField(blank=True, max_length=300)),
                ("alt_text", models.CharField(max_length=300)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("rights_confirmed", models.BooleanField(default=False)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="practitioners.therapylearningguide",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TherapyLearningVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("youtube_url", models.URLField(max_length=500)),
                (
                    "language",
                    models.CharField(choices=[("en", "English"), ("hi", "Hindi")], max_length=2),
                ),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("approved", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="practitioners.therapylearningguide",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
