"use client";
import {DobEditor} from "@/components/practitioners/dob-editor";
import Link from "next/link";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {Fragment,useState} from "react";
import {requestJson} from "@/lib/api/client";
import type {AvailabilityException,AvailabilityRule,Page} from "@/lib/availability/contracts";
import type {CommercialCatalog} from "@/lib/appointments/contracts";
import type {StaffProfile} from "@/lib/staff/contracts";

import {ProfileAvatar,leaveDate} from "@/components/staff/profile-avatar";

const weekdays=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const today=(zone:string)=>new Intl.DateTimeFormat("en-CA",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const time=(value:string)=>{const [h,m]=value.slice(0,5).split(":").map(Number);return new Intl.DateTimeFormat("en-IN",{hour:"numeric",minute:"2-digit"}).format(new Date(2000,0,1,h,m))};

async function allPages<T>(url:string):Promise<Page<T>> {
 const results:T[]=[];let page=1;let next:boolean;
 do {const batch=await requestJson<Page<T>>(`${url}&page=${page++}`);results.push(...batch.results);next=Boolean(batch.next);}while(next);
 return {count:results.length,next:null,previous:null,results};
}

function OwnerTherapies({profile,refresh,setError}:{profile:StaffProfile;refresh:()=>void;setError:(value:string)=>void}) {
 const [adding,setAdding]=useState(false),[selected,setSelected]=useState<string[]>([]),client=useQueryClient();
 const catalog=useQuery({queryKey:["owner-therapy-catalog"],queryFn:()=>requestJson<CommercialCatalog>("/api/commercial/public")});
 const currentIds=profile.therapy_competency_ids??[],current=new Set(currentIds),available=(catalog.data?.therapies??[]).filter(item=>item.is_active!==false&&!item.is_offer_free_addon&&!current.has(item.id));
 const selectedTherapies=currentIds.map((id,index)=>({id,name:catalog.data?.therapies.find(item=>item.id===id)?.name??profile.verified_therapy_names?.[index]??"Selected therapy"}));
 const finish=()=>{setAdding(false);setSelected([]);setError("");client.invalidateQueries({queryKey:["staff"]});refresh()};
 const add=useMutation({mutationFn:async()=>{for(const therapy_id of selected)await requestJson(`/api/staff/profiles/${profile.id}/competencies`,{method:"POST",body:JSON.stringify({therapy_id})})},onSuccess:finish,onError:error=>setError(error.message)});
 const remove=useMutation({mutationFn:(therapy_id:string)=>requestJson(`/api/staff/profiles/${profile.id}/competencies`,{method:"DELETE",body:JSON.stringify({therapy_id})}),onSuccess:finish,onError:error=>setError(error.message)});
 return <section><div className="flex items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">Therapies I Can Perform</h2><p className="text-sm text-slate-600">Used immediately for appointment eligibility.</p></div><button onClick={()=>setAdding(value=>!value)} className="button-primary">+ Add Therapy</button></div><div className="mt-4 space-y-2">{selectedTherapies.map(therapy=><div key={therapy.id} className="flex items-center justify-between rounded-xl border bg-white p-3"><strong>✓ {therapy.name}</strong><button aria-label={`Remove ${therapy.name}`} disabled={remove.isPending} onClick={()=>{if(window.confirm(`Remove ${therapy.name} from this therapist's therapies?`))remove.mutate(therapy.id)}} className="min-h-11 px-3 text-xl text-red-700">×</button></div>)}</div>{adding&&<div className="mt-4 rounded-2xl border bg-white p-4"><p className="font-semibold">Select one or more therapies</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{available.map(item=><label key={item.id} className="flex gap-2"><input type="checkbox" checked={selected.includes(item.id)} onChange={event=>setSelected(values=>event.target.checked?[...values,item.id]:values.filter(id=>id!==item.id))}/>{item.name}</label>)}</div>{!available.length&&<p>All active therapies are already selected.</p>}<div className="mt-4 flex gap-2"><button disabled={!selected.length||add.isPending} onClick={()=>add.mutate()} className="button-primary">Add Selected Therapies</button><button onClick={()=>{setAdding(false);setSelected([])}} className="button-secondary">Cancel</button></div></div>}</section>
}

export function TherapistAvailabilityPage({staffId,self=false}:{staffId:string;self?:boolean}){
 const base=self?"/api/availability/me":"/api/availability";
 const client=useQueryClient();const [editing,setEditing]=useState<number|null>(null),[showLeave,setShowLeave]=useState(false),[error,setError]=useState("");
 const profile=useQuery({queryKey:["therapist-availability-profile",staffId],queryFn:()=>requestJson<StaffProfile>(self?"/api/staff/me":`/api/staff/profiles/${staffId}`)}),rules=useQuery({queryKey:["therapist-availability-rules",staffId],queryFn:()=>allPages<AvailabilityRule>(`${base}/rules?physiotherapist=${staffId}`)}),exceptions=useQuery({queryKey:["therapist-availability-exceptions",staffId],queryFn:()=>allPages<AvailabilityException>(`${base}/exceptions?physiotherapist=${staffId}`)});
 const refresh=()=>{client.invalidateQueries({queryKey:["staff"]});client.invalidateQueries({queryKey:["therapist-availability-rules",staffId]});client.invalidateQueries({queryKey:["therapist-availability-exceptions",staffId]});client.invalidateQueries({queryKey:["therapist-availability-profile",staffId]})};
 const save=useMutation({mutationFn:({weekday,id,starts_at,ends_at}:{weekday:number;id?:string;starts_at:string;ends_at:string})=>requestJson(id?`${base}/rules/${id}`:`${base}/rules`,{method:id?"PATCH":"POST",body:JSON.stringify(id?{starts_at,ends_at}:{clinic:profile.data?.clinic,physiotherapist:staffId,weekday,starts_at,ends_at,effective_from:today(profile.data?.clinic_timezone??"Asia/Kolkata"),effective_until:null})}),onSuccess:()=>{setEditing(null);setError("");refresh()},onError:e=>setError(e.message)});
 const deactivate=useMutation({mutationFn:({kind,id}:{kind:"rules"|"exceptions";id:string})=>requestJson(`${base}/${kind}/${id}/deactivate`,{method:"POST",body:JSON.stringify({reason:self?"Updated by therapist":"Updated by Owner"})}),onSuccess:refresh,onError:e=>setError(e.message)});
 const leave=useMutation({mutationFn:(form:HTMLFormElement)=>{const data=new FormData(form);return requestJson(`${base}/exceptions`,{method:"POST",body:JSON.stringify({clinic:profile.data?.clinic,physiotherapist:staffId,kind:"UNAVAILABLE",from_date:data.get("from_date"),to_date:data.get("to_date"),reason:String(data.get("reason")||"").trim()||"Temporary leave"})})},onSuccess:()=>{setShowLeave(false);setError("");refresh()},onError:e=>setError(e.message)});
 if(profile.isPending)return <p>Loading therapist availability…</p>;if(profile.isError||!profile.data)return <p role="alert">Therapist profile could not be loaded.</p>;const p=profile.data,activeRules=(rules.data?.results??[]).filter(v=>v.is_active&&v.approval_status==="APPROVED"&&(!v.effective_until||v.effective_until>=today(p.clinic_timezone??"Asia/Kolkata"))),futureLeave=(exceptions.data?.results??[]).filter(v=>v.kind==="UNAVAILABLE"&&v.is_active&&v.approval_status==="APPROVED"&&new Date(v.ends_at)>new Date());
 return <div className="space-y-8">{!self&&<><Link href="/owner#staff-management" className="font-bold text-emerald-800">← Back to Physiotherapists</Link><header className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-4"><ProfileAvatar profile={p}/><div><h1 className="text-3xl font-bold">{p.full_name}</h1><p>Therapist management</p></div></div><p className="mt-4">{p.qualification} · {p.experience_years} years {p.experience_months??0} months experience</p><p>{p.specialization_names?.join(", ")||p.verified_therapy_names?.join(", ")}</p><p>{p.email} · {p.mobile}</p><p>{p.clinic_name} · {p.clinic_timezone??"Asia/Kolkata"}</p><p className="mt-2 font-bold">{p.is_active?"Active":"Inactive"} · {p.approval_status==="VERIFIED_APPROVED"?"Approved":p.approval_status?.replaceAll("_"," ")}</p>{p.bio&&<p>{p.bio}</p>}<DobEditor dob={p.date_of_birth} age={p.age} url={self?"/api/staff/me":`/api/staff/profiles/${staffId}`}/></header><OwnerTherapies profile={p} refresh={refresh} setError={setError}/></>}{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
 <section><h2 className="text-2xl font-bold">{self?"My Schedule":"Weekly Schedule"}</h2><p className="text-sm text-slate-600">Working hours stay within your clinic schedule. Changes apply directly; existing visits remain booked.</p><div className="mt-4 overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-left"><thead className="bg-slate-50"><tr><th className="p-4">Day</th><th className="p-4">Hours</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{weekdays.map((day,weekday)=>{const rule=activeRules.find(v=>v.weekday===weekday);const hours=p.operating_days?.find(v=>v.weekday===weekday);return <Fragment key={day}><tr className="border-t"><td className="p-4 font-bold">{day}</td><td className="p-4">{rule?`${time(rule.starts_at)} – ${time(rule.ends_at)}`:"Off"}</td><td className="p-4">{rule?"Active":"Off"}</td><td className="p-4"><button onClick={()=>{setEditing(weekday);setError("")}} className="font-bold text-emerald-800">{rule?"Edit":"Set Working Hours"}</button>{rule&&<button onClick={()=>deactivate.mutate({kind:"rules",id:rule.id})} className="ml-4 font-bold text-red-700">Set Off</button>}</td></tr>{editing===weekday&&<tr aria-label={`${day} editor`}><td colSpan={4}>{hours?.is_open===false?<p className="px-4 text-red-700">Clinic is closed on {day}.</p>:hours&&<p className="px-4 text-slate-600">Clinic hours: {time(hours.opens_at!)} – {time(hours.closes_at!)}</p>}<form aria-label={`Edit ${day}`} onSubmit={e=>{e.preventDefault();if(hours?.is_open===false)return;const data=new FormData(e.currentTarget);save.mutate({weekday,id:rule?.id,starts_at:String(data.get("starts_at")),ends_at:String(data.get("ends_at"))})}} className="mt-4 grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-[1fr_1fr_auto_auto]"><label className="grid gap-1 font-semibold">Start<input name="starts_at" type="time" defaultValue={rule?.starts_at.slice(0,5)??hours?.opens_at?.slice(0,5)??"10:00"} className="min-h-11 rounded-xl border px-3" required/></label><label className="grid gap-1 font-semibold">End<input name="ends_at" type="time" defaultValue={rule?.ends_at.slice(0,5)??hours?.closes_at?.slice(0,5)??"19:00"} className="min-h-11 rounded-xl border px-3" required/></label><button disabled={save.isPending||hours?.is_open===false} className="button-primary self-end">Save {day}</button><button type="button" onClick={()=>setEditing(null)} className="button-secondary self-end">Cancel</button></form></td></tr>}</Fragment>})}</tbody></table></div></section>
 <section><div className="flex items-center justify-between"><h2 className="text-2xl font-bold">{self?"Time Off":"Temporary Leave"}</h2><button onClick={()=>setShowLeave(!showLeave)} className="button-primary">+ Add Leave</button></div>{showLeave&&<form aria-label="Add temporary leave" onSubmit={e=>{e.preventDefault();leave.mutate(e.currentTarget)}} className="mt-4 grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-2"><label className="grid gap-1 font-semibold">From Date<input name="from_date" type="date" className="min-h-11 rounded-xl border px-3" required/></label><label className="grid gap-1 font-semibold">To Date<input name="to_date" type="date" className="min-h-11 rounded-xl border px-3" required/></label><label className="grid gap-1 font-semibold sm:col-span-2">Reason (optional)<input name="reason" className="min-h-11 rounded-xl border px-3"/></label><button disabled={leave.isPending} className="button-primary sm:col-span-2">{leave.isPending?"Saving…":self?"Save Time Off":"Save Leave"}</button><button type="button" onClick={()=>setShowLeave(false)} className="button-secondary">Cancel</button></form>}<div className="mt-4 space-y-2">{futureLeave.map(item=><div key={item.id} className="flex items-center justify-between rounded-xl border bg-white p-4"><div><strong>{leaveDate(new Intl.DateTimeFormat("en-CA",{timeZone:p.clinic_timezone??"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(item.starts_at)))} – {leaveDate(new Intl.DateTimeFormat("en-CA",{timeZone:p.clinic_timezone??"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(new Date(item.ends_at).getTime()-1)))}</strong><p className="text-slate-600">{item.reason||"No reason provided"}</p></div><button onClick={()=>deactivate.mutate({kind:"exceptions",id:item.id})} className="font-bold text-red-700">{self?"Cancel Leave":"Remove"}</button></div>)}{!futureLeave.length&&<p className="rounded-xl border border-dashed p-4 text-slate-600">No future leave recorded.</p>}</div></section></div>
}
