import { QueryClient,QueryClientProvider } from "@tanstack/react-query";
import { fireEvent,render,screen,waitFor } from "@testing-library/react";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { CommercialManagement } from "@/components/appointments/commercial-management";
import { CommercialOffers,TherapyGrid } from "@/components/public/therapy-grid";
const therapy={id:"therapy-1",name:"Kati Basti",slug:"kati-basti",short_description:"Focused lower-back care",benefits:["Comfort"],default_duration_minutes:45,base_price:"1200.00",is_active:true,is_publicly_visible:true,display_order:1};
const catalog={therapies:[therapy],packages:[{id:"package-1",name:"7 Session Plan",therapy:"therapy-1",therapy_name:"Kati Basti",session_count:7,selling_price:"7000.00",regular_total:"8400.00",saving:"1400.00",discount_percentage:16.67,description:"",valid_from:null,valid_until:null,is_active:true,is_publicly_visible:true,display_order:1}],offers:[]};
function renderQuery(ui:React.ReactNode){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}>{ui}</QueryClientProvider>)}
describe("commercial catalog",()=>{beforeEach(()=>vi.restoreAllMocks());it("renders real backend therapy and package prices",async()=>{vi.spyOn(global,"fetch").mockResolvedValue(new Response(JSON.stringify(catalog),{status:200}));renderQuery(<><TherapyGrid/><CommercialOffers/></>);expect(await screen.findByText("Kati Basti")).toBeInTheDocument();expect(screen.getByText("7 Session Plan")).toBeInTheDocument();expect(screen.getByText(/Save ₹1,400/)).toBeInTheDocument()});it("lets operations update a therapy price",async()=>{const fetchMock=vi.spyOn(global,"fetch").mockImplementation(async(input)=>{const url=String(input);if(url.includes("packages" )||url.includes("offers"))return new Response(JSON.stringify([]),{status:200});return new Response(JSON.stringify([therapy]),{status:200})});renderQuery(<CommercialManagement/>);const price=await screen.findByDisplayValue("1200.00");fireEvent.change(price,{target:{value:"1300"}});fireEvent.click(screen.getByRole("button",{name:"Save therapy"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining("therapy-1"),expect.objectContaining({method:"PATCH"})))})});
