"use client";

import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { useSession } from "@/components/auth/session-provider";
import { requestJson } from "@/lib/api/client";
import type { AppointmentRequest, OperationalAppointment } from "@/lib/appointments/contracts";

type Family = { id: string; full_name: string; age: number; gender: string; relationship: string; relevant_details: string };
const friendly = (item: OperationalAppointment) => item.status === "COMPLETED" ? "Completed" : item.status === "CANCELLED" || item.status === "NO_SHOW" ? "Cancelled" : item.status === "IN_PROGRESS" ? "Service Started" : item.journey_status === "ARRIVED" ? "Arrived" : item.journey_status === "EN_ROUTE" ? "Therapist En Route" : item.assignment_status === "ACCEPTED" ? "Therapist Assigned" : item.status === "CONFIRMED" ? "Confirmed" : "Awaiting Confirmation";
const requestFriendly: Record<string, string> = { PENDING: "Request Received", APPROVED: "Awaiting Confirmation", REJECTED: "Cancelled", CANCELLED: "Cancelled" };

export function CustomerDashboard() {
  const session = useSession(); const qc = useQueryClient();
  const requests = useQuery({ queryKey: ["customer-requests"], queryFn: () => requestJson<AppointmentRequest[]>("/api/appointment-requests") });
  const appointments = useQuery({ queryKey: ["customer-operational"], queryFn: () => requestJson<OperationalAppointment[]>("/api/schedule/my-appointments") });
  const family = useQuery({ queryKey: ["customer-family"], queryFn: () => requestJson<Family[]>("/api/customer/family") });
  const [member, setMember] = useState({ full_name: "", age: "", gender: "FEMALE", relationship: "", relevant_details: "" });
  const addFamily = useMutation({ mutationFn: () => requestJson("/api/customer/family", { method: "POST", body: JSON.stringify({ ...member, age: Number(member.age) }) }), onSuccess: () => { setMember({ full_name: "", age: "", gender: "FEMALE", relationship: "", relevant_details: "" }); qc.invalidateQueries({ queryKey: ["customer-family"] }); } });
  const rebook = useMutation({ mutationFn: ({ id, preferred_date, preferred_time }: { id: string; preferred_date: string; preferred_time: string }) => requestJson(`/api/customer/appointments/${id}/rebook`, { method: "POST", body: JSON.stringify({ preferred_date, preferred_time }) }), onSuccess: () => qc.invalidateQueries({ queryKey: ["customer-requests"] }) });
  const [when, setWhen] = useState<Record<string, { date: string; time: string }>>({});
  const user = session.data?.user;
  return <div className="space-y-8 overflow-x-hidden">
    <section className="rounded-3xl bg-gradient-to-br from-emerald-800 to-emerald-600 p-6 text-white sm:p-8"><p className="text-sm font-bold uppercase tracking-widest text-emerald-100">Customer account</p><h2 className="mt-2 text-3xl font-bold">Welcome, {user?.first_name || "Customer"}</h2><p className="mt-2 text-emerald-50">Verified mobile: {user?.mobile_number}</p><Link href="/book-appointment" className="mt-6 inline-flex min-h-12 items-center rounded-xl bg-white px-5 font-bold text-emerald-800">Book Appointment</Link></section>
    <section><h2 className="text-2xl font-bold text-slate-900">Appointments</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{appointments.data?.map((a) => <article key={a.id} className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><strong>{a.patient_name || "Patient"}</strong><span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-bold text-emerald-800">{friendly(a)}</span></div><p className="mt-2 break-all text-xs text-slate-500">Appointment {a.id}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="font-semibold">Schedule</dt><dd>{new Date(a.scheduled_start).toLocaleString()}</dd></div><div><dt className="font-semibold">Duration</dt><dd>{a.duration_minutes} minutes</dd></div><div><dt className="font-semibold">Therapy</dt><dd>{a.therapy_name}</dd></div><div><dt className="font-semibold">Therapist</dt><dd>{a.physiotherapist_name || "Shared after assignment"}</dd></div><div><dt className="font-semibold">Payment</dt><dd>{a.payment_status || "Not available"}</dd></div></dl>{a.status === "COMPLETED" && <div className="mt-5 grid gap-3 sm:grid-cols-3"><input aria-label="New appointment date" type="date" className="min-h-11 rounded-xl border px-3" onChange={(e) => setWhen({ ...when, [a.id]: { ...when[a.id], date: e.target.value } })}/><input aria-label="New appointment time" type="time" min="09:00" max="17:15" step="900" className="min-h-11 rounded-xl border px-3" onChange={(e) => setWhen({ ...when, [a.id]: { ...when[a.id], time: e.target.value } })}/><button className="min-h-11 rounded-xl bg-emerald-700 px-4 font-bold text-white" onClick={() => rebook.mutate({ id: a.id, preferred_date: when[a.id]?.date, preferred_time: when[a.id]?.time })}>Book Again</button></div>}</article>)}</div></section>
    <section><h2 className="text-2xl font-bold">Pending requests</h2><div className="mt-4 grid gap-3">{requests.data?.map((r) => <article key={r.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><strong>{r.patient_name}</strong><span className="font-bold text-emerald-800">{requestFriendly[r.status]}</span></div><p className="mt-2 text-sm">{r.requested_therapy_names?.join(", ") || r.therapy_name} · {r.requested_duration_minutes} minutes</p><p className="text-sm text-slate-600">{r.preferred_date} at {r.preferred_time}</p><p className="mt-1 break-all text-xs text-slate-500">Request {r.id}</p></article>)}</div></section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="text-2xl font-bold">Family members</h2><div className="mt-4 flex flex-wrap gap-2">{family.data?.map((m) => <span key={m.id} className="rounded-full bg-emerald-50 px-3 py-2 text-sm">{m.full_name} · {m.relationship}</span>)}</div><form className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5" onSubmit={(e) => { e.preventDefault(); addFamily.mutate(); }}>{(["full_name", "age", "relationship", "relevant_details"] as const).map((key) => <input key={key} required={key !== "relevant_details"} placeholder={key.replaceAll("_", " ")} value={member[key]} onChange={(e) => setMember({ ...member, [key]: e.target.value })} className="min-h-11 min-w-0 rounded-xl border px-3"/>)}<select value={member.gender} onChange={(e) => setMember({ ...member, gender: e.target.value })} className="min-h-11 rounded-xl border px-3"><option value="FEMALE">Female</option><option value="MALE">Male</option><option value="OTHER">Other</option><option value="PREFER_NOT_TO_SAY">Prefer not to say</option></select><button className="min-h-11 rounded-xl bg-emerald-700 px-4 font-bold text-white">Add family member</button></form></section>
  </div>;
}
