"use client";

import Link from "next/link";
import {useMutation,useQuery} from "@tanstack/react-query";
import {useState} from "react";
import {CustomerRatingPanel} from "@/components/appointments/customer-rating";
import {CommercialOffers} from "@/components/public/therapy-grid";
import {ProfileAvatar} from "@/components/staff/profile-avatar";
import {requestJson} from "@/lib/api/client";
import type {AppointmentRequest,OperationalAppointment} from "@/lib/appointments/contracts";

const customerMessage=(request:AppointmentRequest)=>{const a=request.appointment;if(request.status==="PENDING")return "Your appointment request has been submitted.";if(request.status==="REJECTED")return "Your appointment request was not accepted.";if(request.status==="CANCELLED")return "Your appointment request was cancelled.";if(!a)return "Your request has been accepted. Therapist assignment is in progress.";if(a.assignment_status==="REJECTED")return "We are assigning another therapist to your appointment.";if(a.status==="COMPLETED")return a.payment_status==="PAID"?"Appointment completed successfully · Payment confirmed":"Treatment completed successfully · Payment pending";if(a.status==="IN_PROGRESS")return "Your session is in progress.";if(a.journey_status==="REACHED")return "Your therapist has reached.";if(a.journey_status==="EN_ROUTE")return "Your therapist is on the way.";if(a.assignment_status==="ACCEPTED")return "Your therapist has confirmed the visit.";return "Your appointment is confirmed.";};
const when=(value:string)=>new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
const stars=(value:number|null|undefined)=>value==null?"No ratings yet":`${"★".repeat(Math.round(value))}${"☆".repeat(5-Math.round(value))} ${value.toFixed(1)}`;

export function CustomerDashboard(){const query=useQuery({queryKey:["customer-appointment-history"],queryFn:()=>requestJson<AppointmentRequest[]>("/api/appointment-requests"),refetchInterval:10_000});const items=query.data??[];const groups=[["Pending Requests",items.filter(r=>r.status==="PENDING")],["Accepted / Awaiting Therapist Assignment",items.filter(r=>r.status==="APPROVED"&&!r.appointment)],["Confirmed / Upcoming Appointments",items.filter(r=>r.appointment&&!['COMPLETED','CANCELLED','NO_SHOW'].includes(r.appointment.status))],["Completed",items.filter(r=>r.appointment?.status==="COMPLETED")],["Rejected / Cancelled",items.filter(r=>r.status==="REJECTED"||r.status==="CANCELLED"||r.appointment?.status==="CANCELLED")],["Past Appointment History",items.filter(r=>r.appointment&&['COMPLETED','CANCELLED','NO_SHOW'].includes(r.appointment.status))]] as const;return <div className="space-y-8"><section className="rounded-3xl bg-gradient-to-br from-emerald-800 to-emerald-600 p-6 text-white sm:p-8"><p className="text-sm font-bold uppercase tracking-widest text-emerald-100">Customer care</p><h2 className="mt-2 text-3xl font-bold">My Appointments</h2><p className="mt-2 text-emerald-50">Follow every request from submission through completion.</p><Link href="/book-appointment" className="mt-5 inline-flex min-h-12 items-center rounded-xl bg-white px-5 font-bold text-emerald-800">Book Service</Link></section><CommercialOffers dashboard/>{query.isPending&&<p>Loading your appointment history…</p>}{query.isError&&<p role="alert">Your appointments could not be loaded.</p>}{groups.map(([title,values])=><section key={title}><h2 className="text-2xl font-bold">{title}</h2><div className="mt-4 grid gap-4">{values.map(r=><CustomerAppointmentCard key={r.id} request={r}/>)}</div>{values.length===0&&<p className="mt-3 rounded-xl border border-dashed bg-white p-4 text-slate-500">No appointments in this section.</p>}</section>)}<CustomerRatingPanel/></div>}

export function CustomerAppointmentDetail({requestId}:{requestId:string}){const query=useQuery({queryKey:["customer-appointment",requestId],queryFn:()=>requestJson<AppointmentRequest>(`/api/appointment-requests/${requestId}`),refetchInterval:10_000});if(query.isPending)return <p>Loading appointment…</p>;if(!query.data)return <p role="alert">This appointment could not be loaded.</p>;return <div className="space-y-5"><Link href="/customer" className="font-bold text-emerald-800 underline">← My Appointments</Link><CustomerAppointmentCard request={query.data} detail/></div>}

function CustomerAppointmentCard({request:r,detail=false}:{request:AppointmentRequest;detail?:boolean}){const a=r.appointment;const therapies=r.requested_therapy_names?.length?r.requested_therapy_names:[r.therapy_name];return <article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Booking reference</p><h3 className="break-all font-bold">{r.id}</h3></div><span className="h-fit rounded-full bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-900">{customerMessage(r)}</span></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3"><Info label="Booking submitted" value={when(r.created_at)}/><Info label="Therapies" value={therapies.join(", ")}/><Info label="Requested appointment" value={`${r.preferred_date} at ${r.preferred_time.slice(0,5)}`}/><Info label="Duration" value={`${r.requested_duration_minutes??a?.duration_minutes??0} minutes`}/><Info label="Service address" value={`${r.address}, ${r.city} ${r.pin_code}`}/><Info label="For" value={r.family_member_name||r.patient_name}/><Info label="Last update" value={when(r.updated_at)}/>{r.commercial_snapshot&&<Info label="Commercial snapshot" value={`${r.commercial_snapshot.offer_title||r.commercial_snapshot.package_name||"Standard pricing"} · ₹${r.final_amount??r.commercial_snapshot.final_amount}`}/>}</dl>{r.status==="REJECTED"&&<div className="mt-4 rounded-xl bg-red-50 p-4 text-red-900"><strong>Reason:</strong> {r.rejection_customer_reason||"Please contact JeevaSetu for assistance."}</div>}{a&&<AppointmentSummary appointment={a}/>}<Timeline items={r.timeline??[]}/>{!detail&&<Link href={`/customer/appointments/${r.id}`} className="mt-5 inline-flex min-h-11 items-center font-bold text-emerald-800 underline">Open appointment details</Link>}</article>}
function AppointmentSummary({appointment:a}:{appointment:OperationalAppointment}){const show=a.assignment_status==="PENDING"||a.assignment_status==="ACCEPTED";const paid=a.payment_status==="PAID";return <div className="mt-5 rounded-2xl bg-slate-50 p-4"><h4 className="text-lg font-bold">Confirmed appointment</h4>{a.status==="COMPLETED"&&<div className={`mt-3 rounded-xl border p-4 ${paid?"border-emerald-200 bg-emerald-50 text-emerald-950":"border-amber-200 bg-amber-50 text-amber-950"}`}><p className="font-bold">{paid?"Appointment completed successfully · Payment confirmed":"Treatment completed successfully · Payment pending"}</p></div>}<dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><Info label="Date and time" value={when(a.scheduled_start)}/><Info label="Ends" value={when(a.scheduled_end)}/><Info label="Appointment status" value={a.status==="COMPLETED"?"Appointment completed successfully":a.status.replaceAll("_"," ")}/><Info label="Visit status" value={a.status==="COMPLETED"?"Treatment completed":a.status==="IN_PROGRESS"?"Session in progress":a.journey_status==="REACHED"?"Therapist reached":a.journey_status==="EN_ROUTE"?"Therapist on the way":"Confirmed"}/>{a.status==="COMPLETED"&&<Info label="Amount payable" value={a.payment_amount_due?`₹${a.payment_amount_due}`:"Amount unavailable"}/>}<Info label="Payment" value={paid?"Payment confirmed":"Payment pending confirmation"}/></dl>{show&&a.physiotherapist_name?<div className="mt-5 flex flex-wrap gap-4 rounded-xl border bg-white p-4"><ProfileAvatar large profile={{full_name:a.physiotherapist_name,photo_url:a.physiotherapist_photo_url?`/api/schedule/${a.id}/physiotherapist-photo`:""}}/><div><h5 className="text-xl font-bold">{a.physiotherapist_name}</h5><p>{a.physiotherapist_qualification||"Qualification not provided"}{a.physiotherapist_age!=null?` · Age ${a.physiotherapist_age}`:""}</p><p>{a.physiotherapist_experience_years!=null?`${a.physiotherapist_experience_years} years experience`:"Experience not provided"}</p>{a.physiotherapist_specialization&&<p>{a.physiotherapist_specialization}</p>}{a.physiotherapist_expertise?.length?<p>Relevant expertise: {a.physiotherapist_expertise.join(", ")}</p>:null}<p className="font-bold text-amber-500" aria-label="Therapist rating">{stars(a.physiotherapist_rating)}{a.physiotherapist_review_count?` (${a.physiotherapist_review_count} approved reviews)`:""}</p></div></div>:<p className="mt-4 font-semibold text-slate-700">{a.assignment_status==="REJECTED"?"Therapist reassignment is in progress.":"Therapist assignment is in progress."}</p>}{a.status==="COMPLETED"&&<Rebook appointment={a}/>}</div>}

function Rebook({appointment}:{appointment:OperationalAppointment}){const [message,setMessage]=useState("");const create=useMutation({mutationFn:(payload:{preferred_date:string;preferred_time:string})=>requestJson(`/api/customer/appointments/${appointment.id}/rebook`,{method:"POST",body:JSON.stringify(payload)}),onSuccess:()=>setMessage("A new request was created with current pricing. Therapist assignment will be checked again.")});return <form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);create.mutate({preferred_date:String(data.get("preferred_date")),preferred_time:String(data.get("preferred_time"))})}} className="mt-4 grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-2"><h5 className="font-bold sm:col-span-2">Book Same Therapy Again</h5><p className="text-sm text-slate-600 sm:col-span-2">Your therapies, family member and confirmed primary address will be reused. Choose a new slot; current pricing and eligibility will be recalculated.</p><label className="grid gap-1 font-semibold">New date<input name="preferred_date" type="date" required className="min-h-11 rounded-xl border px-3"/></label><label className="grid gap-1 font-semibold">New time<input name="preferred_time" type="time" required className="min-h-11 rounded-xl border px-3"/></label><button disabled={create.isPending} className="button-primary sm:col-span-2">Book Same Therapy Again</button>{message&&<p role="status" className="text-emerald-800 sm:col-span-2">{message}</p>}{create.isError&&<p role="alert" className="text-red-700 sm:col-span-2">{create.error.message}</p>}</form>}
function Timeline({items}:{items:Array<{key:string;label:string;at:string|null}>}){return <div className="mt-5"><h4 className="font-bold">Status timeline</h4><ol className="mt-3 border-l-2 border-emerald-200 pl-5">{items.map((item,index)=><li key={`${item.key}-${index}`} className="relative pb-4 before:absolute before:-left-[1.7rem] before:top-1 before:size-3 before:rounded-full before:bg-emerald-600"><strong>{item.label}</strong>{item.at&&<span className="block text-xs text-slate-500">{when(item.at)}</span>}</li>)}</ol></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="font-semibold text-slate-600">{label}</dt><dd>{value}</dd></div>}
