import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
import {render,screen,waitFor} from "@testing-library/react";
import {beforeEach,describe,expect,it,vi} from "vitest";
import {CustomerAppointmentDetail,CustomerDashboard} from "./customer-dashboard";

const base={id:"request-1",therapy:"therapy-1",therapy_name:"Kati Basti",requested_therapy_names:["Kati Basti"],requested_duration_minutes:45,family_member:null,family_member_name:"",preferred_practitioner:null,patient_name:"Asha Sharma",age:34,gender:"FEMALE",mobile_number:"9876543210",alternate_mobile:"",email:"",session_preference:"SINGLE",preferred_date:"2026-09-15",preferred_time:"10:00:00",problem_description:"",pain_area:"",problem_duration:"",doctor_reference:"",address:"163 C Block",city:"Meerut",pin_code:"250004",landmark:"",google_map_link:"",status:"PENDING",owner_remarks:"",created_at:"2026-09-01T10:00:00Z",updated_at:"2026-09-01T10:00:00Z",timeline:[{key:"SUBMITTED",label:"Request submitted",at:"2026-09-01T10:00:00Z"}]};
const appointment={id:"appointment-1",originating_request:"request-1",patient_identifier:"PAT-1",patient_name:"Asha Sharma",therapy_name:"Kati Basti",clinic_name:"Main",scheduled_start:"2026-09-15T10:00:00+05:30",scheduled_end:"2026-09-15T10:45:00+05:30",duration_minutes:45,status:"SCHEDULED",journey_status:"NOT_STARTED",physiotherapist_name:"Krishna",assignment_status:"PENDING",physiotherapist_qualification:"MPT",physiotherapist_age:31,physiotherapist_experience_years:2,physiotherapist_specialization:"Orthopaedic care",physiotherapist_expertise:["Kati Basti"],physiotherapist_rating:4.5,physiotherapist_review_count:2,physiotherapist_photo_url:"/photo"};
const offer=(id:string,title:string,overrides:Record<string,unknown>={})=>({id,title,promotional_text:"Save on your next home therapy visit",offer_type:"PERCENTAGE",eligible_therapies:["therapy-1"],eligible_therapy_names:["Kati Basti"],qualifying_package:null,minimum_therapy_count:1,maximum_therapy_count:null,discount_value:"10.00",fixed_price:null,free_therapy:null,free_therapy_name:"",free_quantity:0,family_required:false,minimum_family_members:1,rule_config:{},valid_from:null,valid_until:"2099-01-01T00:00:00Z",is_active:true,is_publicly_visible:true,display_order:0,...overrides});
function show(items:unknown[],offers:unknown[]=[]){vi.spyOn(global,"fetch").mockImplementation(async input=>{const url=String(input);const body=url==="/api/commercial/public"?{therapies:[],packages:[],offers}:url==="/api/schedule/my-appointments"?(items as Array<{appointment?:unknown}>).map(item=>item.appointment).filter(Boolean):items;return new Response(JSON.stringify(body),{status:200})});const client=new QueryClient({defaultOptions:{queries:{retry:false}}});return render(<QueryClientProvider client={client}><CustomerDashboard/></QueryClientProvider>)}
describe("customer appointment history",()=>{beforeEach(()=>{vi.restoreAllMocks();window.history.replaceState(null,"","/")});
 it("shows every required history section and a pending timeline",async()=>{show([base]);expect(await screen.findByText("Your appointment request has been submitted.")).toBeInTheDocument();for(const title of ["Pending Requests","Accepted / Awaiting Therapist Assignment","Confirmed / Upcoming Appointments","Completed","Rejected / Cancelled","Past Appointment History"])expect(screen.getByRole("heading",{name:title})).toBeInTheDocument();expect(screen.getByText("Request submitted")).toBeInTheDocument()});
 it("shows accepted assignment-in-progress without therapist identity",async()=>{show([{...base,status:"APPROVED",timeline:[...base.timeline,{key:"ACCEPTED",label:"Request accepted",at:base.updated_at}]}]);expect(await screen.findByText("Your request has been accepted. Therapist assignment is in progress.")).toBeInTheDocument();expect(screen.queryByText("Krishna")).not.toBeInTheDocument()});
 it("shows canonical confirmed slot and public therapist details after assignment",async()=>{show([{...base,status:"APPROVED",appointment,timeline:[...base.timeline,{key:"ASSIGNED",label:"Therapist assigned",at:base.updated_at}]}]);expect(await screen.findByText("Your appointment is confirmed.")).toBeInTheDocument();expect(screen.getByText("Payment pending confirmation")).toBeInTheDocument();expect(screen.getByText("Krishna")).toBeInTheDocument();expect(screen.getByText(/MPT · Age 31/)).toBeInTheDocument();expect(screen.getByText(/Relevant expertise: Kati Basti/)).toBeInTheDocument();expect(screen.getByLabelText("Therapist rating")).toHaveTextContent("4.5");expect(screen.getByText("Therapist assigned")).toBeInTheDocument()});
 it("synchronizes en-route, in-session, completion, payment and rebook states",async()=>{show([{...base,status:"APPROVED",appointment:{...appointment,status:"COMPLETED",assignment_status:"ACCEPTED",journey_status:"EN_ROUTE",payment_status:"PAID",payment_amount_due:"1777.00"}}]);expect((await screen.findAllByText("Appointment completed successfully · Payment confirmed")).length).toBeGreaterThan(0);expect(screen.getAllByText("₹1777.00").length).toBeGreaterThan(0);expect(screen.getAllByText("Payment confirmed").length).toBeGreaterThan(0);expect(screen.getAllByRole("button",{name:"Book Same Therapy Again"}).length).toBeGreaterThan(0);expect(screen.getByRole("heading",{name:"Rate your therapist"})).toBeInTheDocument()});
 it("shows the completed appointment rating form on details and focuses its deep-link anchor",async()=>{const completed={...appointment,status:"COMPLETED",assignment_status:"ACCEPTED",payment_status:"PAID",payment_amount_due:"1777.00",rating:null};window.history.replaceState(null,"","/customer/appointments/appointment-1#rating");const scroll=vi.fn();Object.defineProperty(HTMLElement.prototype,"scrollIntoView",{configurable:true,value:scroll});vi.spyOn(global,"fetch").mockImplementation(async input=>new Response(JSON.stringify(String(input)==="/api/schedule/my-appointments"?[completed]:{...base,status:"APPROVED",appointment:completed}),{status:200}));const client=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<QueryClientProvider client={client}><CustomerAppointmentDetail requestId="appointment-1"/></QueryClientProvider>);expect(await screen.findByText("Therapist: Krishna")).toBeInTheDocument();const heading=screen.getByRole("heading",{name:"Rate your therapist"});expect(heading.closest("section")).toHaveAttribute("id","rating");expect(screen.getByRole("radio",{name:"5 stars"})).toBeInTheDocument();expect(screen.getByLabelText("Review (optional)")).not.toBeRequired();await waitFor(()=>expect(scroll).toHaveBeenCalled());expect(document.activeElement).toBe(heading.closest("section"))});
 it("shows the exact customer messages for en route and session started",async()=>{const {unmount}=show([{...base,status:"APPROVED",appointment:{...appointment,status:"CONFIRMED",assignment_status:"ACCEPTED",journey_status:"EN_ROUTE"}}]);expect(await screen.findByText("Your therapist is on the way.")).toBeInTheDocument();unmount();vi.restoreAllMocks();show([{...base,status:"APPROVED",appointment:{...appointment,status:"IN_PROGRESS",assignment_status:"ACCEPTED",journey_status:"EN_ROUTE"}}]);expect(await screen.findByText("Your session is in progress.")).toBeInTheDocument()});
 it("retains rejection reason",async()=>{show([{...base,status:"REJECTED",rejection_customer_reason:"The requested slot is unavailable.",timeline:[...base.timeline,{key:"REJECTED",label:"Request not accepted",at:base.updated_at}]}]);expect(await screen.findByText("Your appointment request was not accepted.")).toBeInTheDocument();expect(screen.getByText(/The requested slot is unavailable/)).toBeInTheDocument()});
 it("hides a declined therapist and shows reassignment",async()=>{show([{...base,status:"APPROVED",appointment:{...appointment,assignment_status:"REJECTED",physiotherapist_name:null},timeline:[...base.timeline,{key:"REASSIGNMENT",label:"Therapist reassignment in progress",at:base.updated_at}]}]);expect(await screen.findByText("We are assigning another therapist to your appointment.")).toBeInTheDocument();expect(screen.queryByText("Krishna")).not.toBeInTheDocument();expect(screen.getByText("Therapist reassignment in progress")).toBeInTheDocument()});
 it("shows an active offer above pending requests and keeps the booking CTA first",async()=>{show([base],[offer("offer-1","September care savings")]);const offerHeading=await screen.findByRole("heading",{name:"Current Offers & Packages"});const pendingHeading=screen.getByRole("heading",{name:"Pending Requests"});const bookLink=screen.getByRole("link",{name:"Book Service"});expect(offerHeading.compareDocumentPosition(pendingHeading)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(bookLink.compareDocumentPosition(offerHeading)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(screen.getByRole("link",{name:"View all offers & packages"})).toHaveAttribute("href","/customer/offers")});
 it("renders multiple active offers",async()=>{show([base],[offer("offer-1","September care savings"),offer("offer-2","Family wellness offer")]);expect(await screen.findByText("September care savings")).toBeInTheDocument();expect(screen.getByText("Family wellness offer")).toBeInTheDocument()});
 it("hides the dashboard offer section when no current offer exists",async()=>{show([base]);expect(await screen.findByText("Your appointment request has been submitted.")).toBeInTheDocument();expect(screen.queryByRole("heading",{name:"Current Offers & Packages"})).not.toBeInTheDocument();expect(screen.getByRole("heading",{name:"Pending Requests"})).toBeInTheDocument()});
 it("hides inactive, private, and expired offers while pending requests remain",async()=>{show([base],[offer("inactive","Inactive",{is_active:false}),offer("private","Private",{is_publicly_visible:false}),offer("expired","Expired",{valid_until:"2020-01-01T00:00:00Z"})]);expect(await screen.findByText("Your appointment request has been submitted.")).toBeInTheDocument();expect(screen.queryByRole("heading",{name:"Current Offers & Packages"})).not.toBeInTheDocument();expect(screen.queryByText("Inactive")).not.toBeInTheDocument();expect(screen.queryByText("Private")).not.toBeInTheDocument();expect(screen.queryByText("Expired")).not.toBeInTheDocument();expect(screen.getByRole("heading",{name:"Pending Requests"})).toBeInTheDocument()});
});
