"use client";

/* eslint-disable react-hooks/set-state-in-effect -- query results intentionally hydrate this multi-step operational form */

import {useMutation,useQuery} from "@tanstack/react-query";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {AddressCapture} from "@/components/location/address-capture";
import {requestJson} from "@/lib/api/client";
import type {CommercialQuote,OperationalAppointment,TherapyOption} from "@/lib/appointments/contracts";
import {emptyServiceAddress,type ServiceAddress} from "@/lib/location/contracts";
import type {PatientPage,PatientProfile} from "@/lib/patients/contracts";
import type {StaffPage} from "@/lib/staff/contracts";

type Session={access:{permitted_clinics:Array<{id:string;slug:string}>}};
type AvailableTherapist={id:string;full_name:string};
type StaffOptions={service_areas:Array<{id:string;name:string;pin_codes:string[]}>};
type CreatedAppointment=OperationalAppointment&{patient_reused:boolean;patient_id:string;booking_source:string;payment_status:"PENDING"|"PAID";payment_amount_due:string};
const blankAddress=():ServiceAddress=>({...emptyServiceAddress(),region:"Uttar Pradesh"});

export function OfflineAppointmentBooking(){
 const [mobile,setMobile]=useState("");const [searchedMobile,setSearchedMobile]=useState("");const [clinic,setClinic]=useState("");const [patientName,setPatientName]=useState("");const [age,setAge]=useState("");const [gender,setGender]=useState("");const [address,setAddress]=useState<ServiceAddress>(blankAddress());const [addressConfirmed,setAddressConfirmed]=useState(false);const [therapyIds,setTherapyIds]=useState<string[]>([]);const [date,setDate]=useState("");const [time,setTime]=useState("");const [therapist,setTherapist]=useState("");const [source,setSource]=useState("CALL");const [note,setNote]=useState("");const [paymentStatus,setPaymentStatus]=useState<"PENDING"|"PAID">("PENDING");const [paymentReference,setPaymentReference]=useState("");
 const session=useQuery({queryKey:["owner-create-session"],queryFn:()=>requestJson<Session>("/api/session/me")});
 const therapies=useQuery({queryKey:["owner-create-therapies"],queryFn:()=>requestJson<TherapyOption[]>("/api/appointment-therapies")});
 const staff=useQuery({queryKey:["owner-create-staff"],queryFn:()=>requestJson<StaffPage>("/api/staff/profiles?type=PHYSIOTHERAPIST&status=active&page_size=50")});
 const staffOptions=useQuery({queryKey:["owner-create-staff-options"],queryFn:()=>requestJson<StaffOptions>("/api/staff/options")});
 const patientSearch=useQuery({queryKey:["owner-create-patient-search",searchedMobile],queryFn:()=>requestJson<PatientPage>(`/api/patients?search=${searchedMobile}&status=active&page_size=8`),enabled:/^[6-9]\d{9}$/.test(searchedMobile)});
 const match=patientSearch.data?.results.length===1?patientSearch.data.results[0]:null;
 const patientDetail=useQuery({queryKey:["owner-create-patient",match?.id],queryFn:()=>requestJson<PatientProfile>(`/api/patients/${match?.id}`),enabled:Boolean(match)});
 const duration=therapyIds.reduce((sum,id)=>sum+(therapies.data?.find(item=>item.id===id)?.default_duration_minutes??45),0);
 const start=date&&time?new Date(`${date}T${time}:00+05:30`).toISOString():"";
 const availability=useQuery({queryKey:["owner-create-availability",clinic,start,duration],queryFn:()=>requestJson<AvailableTherapist[]>(`/api/schedule/available-physiotherapists?clinic=${clinic}&scheduled_start=${encodeURIComponent(start)}&duration_minutes=${duration}`),enabled:Boolean(clinic&&start&&duration)});
 const quote=useQuery({queryKey:["owner-create-quote",therapyIds,start],queryFn:()=>requestJson<CommercialQuote>("/api/commercial/quote",{method:"POST",body:JSON.stringify({therapy_ids:therapyIds,package_id:null,offer_id:null,family_member_id:null,service_at:start})}),enabled:Boolean(therapyIds.length&&start)});
 useEffect(()=>{if(!patientDetail.data)return;const patient=patientDetail.data;const primary=patient.addresses.find(item=>item.is_active&&item.is_primary);setPatientName(patient.full_name);setAge(String(patient.age??""));setGender(patient.gender);setClinic(patient.clinic);setAddressConfirmed(false);if(primary)setAddress({...blankAddress(),...primary})},[patientDetail.data]);
 useEffect(()=>{if(!searchedMobile||!patientSearch.data||match)return;setPatientName("");setAge("");setGender("");setAddress(blankAddress());setAddressConfirmed(false)},[searchedMobile,patientSearch.data,match]);
 const eligible=useMemo(()=>{const availableIds=new Set(availability.data?.map(item=>item.id)??[]);const areaIds=new Set((staffOptions.data?.service_areas??[]).filter(area=>area.name.trim().toLowerCase()===address.city.trim().toLowerCase()||area.pin_codes.includes(address.pin_code)).map(area=>area.id));return (staff.data?.results??[]).filter(item=>availableIds.has(item.id)&&therapyIds.every(id=>item.therapy_competency_ids.includes(id))&&(!item.service_area_ids.length||item.service_area_ids.some(id=>areaIds.has(id))))},[availability.data,staff.data,staffOptions.data,therapyIds,address.city,address.pin_code]);
 useEffect(()=>{if(therapist&&!eligible.some(item=>item.id===therapist))setTherapist("")},[eligible,therapist]);
 const create=useMutation({mutationFn:()=>requestJson<CreatedAppointment>("/api/owner/offline-appointments",{method:"POST",body:JSON.stringify({mobile_number:searchedMobile,patient_name:patientName,age:Number(age),gender,clinic,therapies:therapyIds,physiotherapist:therapist,preferred_date:date,preferred_time:time,service_address:address,booking_source:source,operational_note:note,payment_status:paymentStatus,payment_reference:paymentReference})})});
 const existing=Boolean(patientDetail.data);
 return <section className="mx-auto max-w-5xl py-8"><div className="rounded-3xl bg-emerald-800 p-6 text-white"><p className="text-sm font-bold uppercase tracking-widest text-emerald-100">Owner operations</p><h1 className="mt-2 text-3xl font-bold">Book for Customer</h1><p className="mt-2 text-emerald-50">Create Phone / Offline Booking</p></div>
  <form onSubmit={event=>{event.preventDefault();create.mutate()}} className="mt-6 grid gap-6">
   <fieldset className="grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-[1fr_auto]"><legend className="px-2 text-xl font-bold">1. Find customer</legend><label className="grid gap-1 font-semibold">Mobile number<input inputMode="numeric" pattern="[6-9][0-9]{9}" required value={mobile} onChange={event=>setMobile(event.target.value.replace(/\D/g,"").slice(0,10))} className="min-h-12 rounded-xl border px-3"/></label><button type="button" disabled={!/^[6-9]\d{9}$/.test(mobile)} onClick={()=>setSearchedMobile(mobile)} className="button-primary">Search mobile</button>{patientSearch.isFetching&&<p>Searching…</p>}{searchedMobile&&patientSearch.data&&<p role="status" className="sm:col-span-2">{existing?`Existing patient found: ${patientDetail.data?.full_name??match?.full_name}. This canonical record will be reused.`:"No patient found. Enter lightweight patient details below."}</p>}</fieldset>
   {searchedMobile&&patientSearch.data&&<><fieldset className="grid min-w-0 gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-2"><legend className="px-2 text-xl font-bold">2. Patient details</legend><Select label="Clinic" value={clinic} onChange={setClinic} options={session.data?.access.permitted_clinics.map(item=>[item.id,item.slug])}/><Field label="Customer / patient name" value={patientName} onChange={setPatientName} disabled={existing}/><Field label="Age" type="number" value={age} onChange={setAge} disabled={existing}/><Select label="Gender" value={gender} onChange={setGender} disabled={existing} options={[["FEMALE","Female"],["MALE","Male"],["OTHER","Other"],["PREFER_NOT_TO_SAY","Prefer not to say"]]}/></fieldset><AddressCapture value={address} onChange={setAddress} title="2. Service address" onConfirmedChange={setAddressConfirmed}/>{existing&&<p className="text-sm text-slate-600">The saved primary address is prefilled. Editing it changes only this appointment snapshot.</p>}
   <fieldset className="grid gap-4 rounded-2xl border bg-white p-5"><legend className="px-2 text-xl font-bold">3. Service and therapist</legend><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{therapies.data?.filter(item=>item.is_active!==false&&!item.is_offer_free_addon).map(item=><label key={item.id} className="flex items-center gap-2 rounded-xl border p-3"><input type="checkbox" checked={therapyIds.includes(item.id)} onChange={event=>setTherapyIds(event.target.checked?[...therapyIds,item.id]:therapyIds.filter(id=>id!==item.id))}/>{item.name}</label>)}</div><div className="grid gap-4 sm:grid-cols-2"><Field label="Date" type="date" value={date} onChange={setDate}/><Field label="Time" type="time" value={time} onChange={setTime}/></div>{quote.data&&<p className="rounded-xl bg-emerald-50 p-3 font-bold">Current authoritative amount: ₹{quote.data.final_amount} · {quote.data.duration_minutes} minutes</p>}<Select label="Eligible therapist" value={therapist} onChange={setTherapist} options={eligible.map(item=>[item.id,item.full_name])}/>{availability.data&&eligible.length===0&&<p className="text-amber-800">No therapist passes schedule, therapy competency and service-area checks for this selection.</p>}</fieldset>
   <fieldset className="grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-2"><legend className="px-2 text-xl font-bold">4. Source and payment</legend><Select label="Booking source" value={source} onChange={setSource} options={[["CALL","Call"],["ADVERTISEMENT","Advertisement"],["REFERRAL","Referral"],["WALK_IN","Walk-in"],["OTHER","Other"]]}/><Select label="Payment status" value={paymentStatus} onChange={value=>setPaymentStatus(value as "PENDING"|"PAID")} options={[["PENDING","Pending"],["PAID","Paid"]]}/>{paymentStatus==="PAID"&&<Field label="Payment reference (optional)" required={false} value={paymentReference} onChange={setPaymentReference}/>}<label className="grid gap-1 font-semibold sm:col-span-2">Operational note (optional)<textarea value={note} onChange={event=>setNote(event.target.value)} maxLength={500} className="rounded-xl border p-3"/></label></fieldset>
   <button disabled={create.isPending||!existing&&!patientName||!clinic||!therapyIds.length||!therapist||!quote.data||!addressConfirmed} className="button-primary min-h-12">{create.isPending?"Creating appointment…":"Create canonical appointment"}</button>{create.isError&&<p role="alert" className="text-red-700">{create.error.message}</p>}{create.data&&<div role="status" className="rounded-2xl bg-emerald-50 p-5 text-emerald-950"><strong>Appointment created successfully.</strong><p>{create.data.patient_reused?"Existing patient reused":"New lightweight patient created"} · ₹{create.data.payment_amount_due} · Payment {create.data.payment_status}</p><Link href="/owner/appointments" className="mt-3 inline-flex font-bold underline">Open Appointment Schedule</Link></div>}</>}
  </form>
 </section>
}

function Field({label,value,onChange,type="text",required=true,disabled=false}:{label:string;value:string;onChange:(value:string)=>void;type?:string;required?:boolean;disabled?:boolean}){return <label className="grid min-w-0 gap-1 font-semibold">{label}<input type={type} value={value} required={required} disabled={disabled} onChange={event=>onChange(event.target.value)} className="min-h-12 w-full min-w-0 rounded-xl border px-3 disabled:bg-slate-100"/></label>}
function Select({label,value,onChange,options,disabled=false}:{label:string;value:string;onChange:(value:string)=>void;options?:string[][];disabled?:boolean}){return <label className="grid min-w-0 gap-1 font-semibold">{label}<select required value={value} disabled={disabled} onChange={event=>onChange(event.target.value)} className="min-h-12 w-full min-w-0 rounded-xl border px-3 disabled:bg-slate-100"><option value="">Select</option>{options?.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}
