import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";

import { AssignedAppointments, CustomerAppointments, ScheduleOperations } from "@/components/appointments/operational-schedule";

function wrap(ui:React.ReactNode){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}>{ui}</QueryClientProvider>)}
const scheduledStart = new Date(Date.now() + 60 * 60 * 1000);
const appointment={id:"a1",patient_identifier:"PAT-000001",patient_name:"Asha Sharma",therapy_name:"Physiotherapy",clinic_name:"Meerut",scheduled_start:scheduledStart.toISOString(),scheduled_end:new Date(scheduledStart.getTime()+60*60*1000).toISOString(),duration_minutes:60,status:"CONFIRMED",physiotherapist_name:"Dr Physio User",assignment_status:"PENDING",assigned_manager_name:"Manager User",address_line_1:"Shastri Nagar",city:"Meerut",pin_code:"250004",physiotherapist_photo_url:null};

describe("operational scheduling",()=>{
  beforeEach(()=>vi.restoreAllMocks());
  it("provides all operational filters and an explicit appointment form",()=>{vi.spyOn(global,"fetch").mockImplementation(async input=>{const url=String(input);const value=url.includes("appointment-therapies")||url.includes("workload")?[]:url.includes("session/me")?{access:{permitted_clinics:[],roles:[]}}:{count:0,next:null,previous:null,results:[]};return new Response(JSON.stringify(value),{status:200})});wrap(<ScheduleOperations/>);expect(screen.getByLabelText("Search")).toBeInTheDocument();expect(screen.getByLabelText("Queue")).toBeInTheDocument();expect(screen.getByLabelText("Clinic")).toBeInTheDocument();expect(screen.getByLabelText("Date")).toBeInTheDocument();expect(screen.getByLabelText("Status")).toBeInTheDocument();expect(screen.getByLabelText("Therapy")).toBeInTheDocument();expect(screen.getByLabelText("Physiotherapist")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Create appointment"}));expect(screen.getByRole("form",{name:"Create operational appointment"})).toBeInTheDocument();});
  it("offers lifecycle controls only for changeable operational appointments",async()=>{vi.spyOn(global,"fetch").mockImplementation(async input=>{const url=String(input);const value=url.includes("appointment-therapies")||url.includes("workload")?[]:url.includes("session/me")?{access:{permitted_clinics:[],roles:[{role:"OWNER"}]}}:url.includes("operations")?{count:1,next:null,previous:null,results:[appointment]}:{count:0,next:null,previous:null,results:[]};return new Response(JSON.stringify(value),{status:200})});wrap(<ScheduleOperations/>);expect(await screen.findByRole("button",{name:"Reschedule"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Cancel assignment"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Cancel"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Audit"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Cancel"}));expect(screen.getByLabelText("Reason category")).toBeInTheDocument();expect(screen.getByLabelText("Owner policy override")).toBeInTheDocument();});
  it("limits physiotherapist actions to assigned lifecycle controls",async()=>{vi.spyOn(global,"fetch").mockResolvedValue(new Response(JSON.stringify([appointment]),{status:200}));wrap(<AssignedAppointments/>);expect(await screen.findByText("Asha Sharma")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Accept assignment"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Reject assignment"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Start"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"No show"})).toBeInTheDocument();});
  it("shows customers a safe appointment summary and request-only changes",async()=>{vi.spyOn(global,"fetch").mockResolvedValue(new Response(JSON.stringify([appointment]),{status:200}));wrap(<CustomerAppointments/>);expect(await screen.findByText("Physiotherapy")).toBeInTheDocument();expect(screen.getByText(/Dr Physio User/)).toBeInTheDocument();expect(screen.getByRole("button",{name:"Request reschedule"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Request cancellation"})).toBeInTheDocument();expect(screen.queryByText(/mobile/i)).not.toBeInTheDocument();});
});
