"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";

import { requestJson } from "@/lib/api/client";
import type { OperationalAppointment, OperationalAppointmentPage, TherapyOption } from "@/lib/appointments/contracts";
import type { PatientPage } from "@/lib/patients/contracts";
import type { StaffPage } from "@/lib/staff/contracts";

type Session = {access:{permitted_clinics:Array<{id:string;slug:string}>}};

export function ScheduleOperations() {
  const [showForm,setShowForm]=useState(false); const [status,setStatus]=useState(""); const [assignments,setAssignments]=useState<Record<string,string>>({}); const client=useQueryClient();
  const query=useQuery({queryKey:["schedule",status],queryFn:()=>requestJson<OperationalAppointmentPage>(`/api/schedule?status=${status}`)});
  const patients=useQuery({queryKey:["schedule-patients"],queryFn:()=>requestJson<PatientPage>("/api/patients?status=active&page_size=50")});
  const staff=useQuery({queryKey:["schedule-staff"],queryFn:()=>requestJson<StaffPage>("/api/staff/profiles?type=PHYSIOTHERAPIST&status=active&page_size=50")});
  const therapies=useQuery({queryKey:["schedule-therapies"],queryFn:()=>requestJson<TherapyOption[]>("/api/appointment-therapies")});
  const session=useQuery({queryKey:["schedule-session"],queryFn:()=>requestJson<Session>("/api/session/me")});
  const create=useMutation({mutationFn:(value:Record<string,unknown>)=>{const requestId=String(value.request_id??"");const payload={...value};delete payload.request_id;return requestJson(requestId?`/api/schedule/convert/${requestId}`:"/api/schedule",{method:"POST",body:JSON.stringify(payload)})},onSuccess:()=>{setShowForm(false);client.invalidateQueries({queryKey:["schedule"]})}});
  const transition=useMutation({mutationFn:({id,next}:{id:string;next:string})=>requestJson(`/api/schedule/${id}/status`,{method:"POST",body:JSON.stringify({status:next,reason:"Updated by authorized operations staff."})}),onSuccess:()=>client.invalidateQueries({queryKey:["schedule"]})});
  const assign=useMutation({mutationFn:({id,physiotherapist}:{id:string;physiotherapist:string})=>requestJson(`/api/schedule/${id}/assign`,{method:"POST",body:JSON.stringify({physiotherapist,reason:"Assignment updated by authorized operations staff."})}),onSuccess:()=>client.invalidateQueries({queryKey:["schedule"]})});
  function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);create.mutate({request_id:data.get("request_id"),patient:data.get("patient"),therapy:data.get("therapy"),clinic:data.get("clinic"),physiotherapist:data.get("physiotherapist")||null,scheduled_start:data.get("scheduled_start"),status:data.get("status"),address_line_1:data.get("address_line_1"),address_line_2:"",landmark:data.get("landmark"),city:data.get("city"),region:data.get("region"),pin_code:data.get("pin_code"),operational_notes:data.get("operational_notes")});}
  return <section className="mt-8" aria-labelledby="schedule-heading"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="schedule-heading" className="text-2xl font-bold">Appointment schedule</h2><p className="text-slate-600">Clinic-scoped scheduling, assignment and lifecycle control.</p></div><button onClick={()=>setShowForm(v=>!v)} className="min-h-11 rounded-xl bg-emerald-700 px-4 font-bold text-white">{showForm?"Close form":"Create appointment"}</button></div>
  {showForm&&<form aria-label="Create operational appointment" onSubmit={submit} className="mt-5 grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-2"><Field name="request_id" label="Approved request ID (optional conversion)" required={false}/><Select name="patient" label="Patient" options={patients.data?.results.map(p=>[p.id,`${p.patient_identifier} · ${p.full_name}`])}/><Select name="therapy" label="Therapy" options={therapies.data?.map(t=>[t.id,t.name])}/><Select name="clinic" label="Clinic" options={session.data?.access?.permitted_clinics.map(c=>[c.id,c.slug])}/><Select name="physiotherapist" label="Physiotherapist (optional for draft)" required={false} options={staff.data?.results.map(p=>[p.id,p.full_name])}/><Field name="scheduled_start" label="Start date and time" type="datetime-local"/><label className="grid gap-1 font-semibold">Initial status<select name="status" className="min-h-11 rounded-xl border px-3"><option value="DRAFT">Draft</option><option value="PENDING_ASSIGNMENT">Pending assignment</option><option value="SCHEDULED">Scheduled</option></select></label><Field name="address_line_1" label="Service address"/><Field name="landmark" label="Landmark" required={false}/><Field name="city" label="City"/><Field name="region" label="State"/><Field name="pin_code" label="PIN code"/><Field name="operational_notes" label="Short non-clinical operational note" required={false}/><button disabled={create.isPending} className="min-h-11 rounded-xl bg-emerald-700 font-bold text-white sm:col-span-2">{create.isPending?"Creating…":"Create appointment"}</button>{create.isError&&<p role="alert" className="text-red-700 sm:col-span-2">{create.error.message}</p>}</form>}
  <label className="mt-5 grid max-w-sm gap-1 font-semibold">Filter status<select aria-label="Filter appointment status" value={status} onChange={e=>setStatus(e.target.value)} className="min-h-11 rounded-xl border px-3"><option value="">All statuses</option>{["DRAFT","PENDING_ASSIGNMENT","SCHEDULED","CONFIRMED","IN_PROGRESS","COMPLETED","CANCELLED","NO_SHOW"].map(s=><option key={s}>{s}</option>)}</select></label><AppointmentTable items={query.data?.results??[]} onStatus={(id,next)=>transition.mutate({id,next})} staffOptions={staff.data?.results.map(p=>[p.id,p.full_name])} assignments={assignments} onAssignmentChange={(id,value)=>setAssignments(current=>({...current,[id]:value}))} onAssign={(id)=>assignments[id]&&assign.mutate({id,physiotherapist:assignments[id]})}/></section>;
}

export function AssignedAppointments(){const client=useQueryClient();const query=useQuery({queryKey:["assigned-appointments"],queryFn:()=>requestJson<OperationalAppointment[]>("/api/schedule/assigned-to-me")});const transition=useMutation({mutationFn:({id,next}:{id:string;next:string})=>requestJson(`/api/schedule/${id}/status`,{method:"POST",body:JSON.stringify({status:next})}),onSuccess:()=>client.invalidateQueries({queryKey:["assigned-appointments"]})});return <section className="mt-8"><h2 className="text-2xl font-bold">My assigned appointments</h2><AppointmentTable items={query.data??[]} onStatus={(id,next)=>transition.mutate({id,next})} physiotherapist/></section>}

export function CustomerAppointments(){const query=useQuery({queryKey:["customer-appointments"],queryFn:()=>requestJson<OperationalAppointment[]>("/api/schedule/my-appointments")});return <section className="mt-8"><h2 className="text-2xl font-bold">My scheduled appointments</h2><div className="mt-4 grid gap-4">{query.data?.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5">{item.physiotherapist_photo_url&&<img src={`/api/schedule/${item.id}/physiotherapist-photo`} alt={`${item.physiotherapist_name} profile`} className="mb-3 size-16 rounded-full object-cover"/>}<h3 className="font-bold">{item.therapy_name}</h3><p>{new Date(item.scheduled_start).toLocaleString()} · {item.status}</p><p className="text-slate-600">{item.address_line_1}, {item.city} {item.pin_code}</p><p>Physiotherapist: {item.physiotherapist_name??"Pending assignment"}</p></article>)}</div></section>}

function AppointmentTable({items,onStatus,physiotherapist=false,staffOptions,assignments,onAssignmentChange,onAssign}:{items:OperationalAppointment[];onStatus:(id:string,next:string)=>void;physiotherapist?:boolean;staffOptions?:string[][];assignments?:Record<string,string>;onAssignmentChange?:(id:string,value:string)=>void;onAssign?:(id:string)=>void}){return <div className="mt-5 overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-left text-sm"><thead><tr>{["Patient","Therapy","Schedule","Physiotherapist","Status","Actions"].map(h=><th className="p-4" key={h}>{h}</th>)}</tr></thead><tbody>{items.map(item=><tr className="border-t" key={item.id}><td className="p-4">{item.patient_name}<span className="block text-slate-500">{item.patient_identifier}</span></td><td className="p-4">{item.therapy_name}</td><td className="p-4">{new Date(item.scheduled_start).toLocaleString()}</td><td className="p-4">{item.physiotherapist_name??"Unassigned"}{!physiotherapist&&<span className="mt-2 flex gap-2"><select aria-label={`Assign ${item.patient_name}`} value={assignments?.[item.id]??""} onChange={e=>onAssignmentChange?.(item.id,e.target.value)} className="rounded-lg border px-2"><option value="">Select</option>{staffOptions?.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select><button type="button" className="font-bold underline" onClick={()=>onAssign?.(item.id)}>Assign</button></span>}</td><td className="p-4">{item.status}</td><td className="p-4"><div className="flex gap-2">{physiotherapist&&item.status==="CONFIRMED"&&<><button className="font-bold underline" onClick={()=>onStatus(item.id,"IN_PROGRESS")}>Start</button><button className="font-bold underline" onClick={()=>onStatus(item.id,"NO_SHOW")}>No show</button></>}{physiotherapist&&item.status==="IN_PROGRESS"&&<button className="font-bold underline" onClick={()=>onStatus(item.id,"COMPLETED")}>Complete</button>}{!physiotherapist&&item.status==="SCHEDULED"&&<button className="font-bold underline" onClick={()=>onStatus(item.id,"CONFIRMED")}>Confirm</button>}</div></td></tr>)}</tbody></table>{items.length===0&&<p className="p-5 text-slate-600">No appointments found.</p>}</div>}
function Field({name,label,type="text",required=true}:{name:string;label:string;type?:string;required?:boolean}){return <label className="grid gap-1 font-semibold">{label}<input name={name} type={type} required={required} className="min-h-11 rounded-xl border px-3"/></label>}
function Select({name,label,options,required=true}:{name:string;label:string;options?:string[][];required?:boolean}){return <label className="grid gap-1 font-semibold">{label}<select name={name} required={required} className="min-h-11 rounded-xl border px-3"><option value="">Select</option>{options?.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>}
