"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { requestJson } from "@/lib/api/client";
import type { AppointmentRequest } from "@/lib/appointments/contracts";

type Eligible = { id:string; full_name:string; qualification:string; experience_years:number; specialization:string; rating:number|null; review_count:number; has_photo:boolean };
const rejectionCategories = [["NO_PRACTITIONER","No practitioner available"],["SERVICE_UNAVAILABLE","Service unavailable"],["OUTSIDE_SERVICE_AREA","Outside service area"],["SCHEDULING_CONFLICT","Scheduling conflict"],["OTHER","Other"]] as const;

export function OwnerRequests() {
  const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [active,setActive]=useState<string|null>(null);
  const [selected,setSelected]=useState<Record<string,string>>({}); const [category,setCategory]=useState<Record<string,string>>({}); const [reason,setReason]=useState<Record<string,string>>({}); const [note,setNote]=useState<Record<string,string>>({});
  const cache=useQueryClient();
  const query=useQuery({queryKey:["owner-appointments",search,status],queryFn:()=>requestJson<AppointmentRequest[]>(`/api/owner/appointment-requests?search=${encodeURIComponent(search)}&status=${encodeURIComponent(status)}`),refetchInterval:5000});
  const eligible=useQuery({queryKey:["request-eligible",active],queryFn:()=>requestJson<Eligible[]>(`/api/owner/appointment-requests/${active}/eligible-physiotherapists`),enabled:Boolean(active)});
  const decide=useMutation({mutationFn:({id,payload}:{id:string;payload:Record<string,unknown>})=>requestJson(`/api/owner/appointment-requests/${id}/decision`,{method:"POST",body:JSON.stringify(payload)}),onSuccess:()=>{setActive(null);cache.invalidateQueries({queryKey:["owner-appointments"]});cache.invalidateQueries({queryKey:["schedule-operations"]});}});
  return <section aria-labelledby="requests-heading"><div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5"><h2 id="requests-heading" className="text-2xl font-bold text-emerald-950">Appointment Requests</h2><p className="mt-2 text-emerald-900">Review server-priced requests and assign only a practitioner eligible for the exact slot.</p></div><div className="mt-6 grid gap-3 sm:grid-cols-[1fr_14rem]"><label className="grid gap-1 text-sm font-semibold">Search<input value={search} onChange={e=>setSearch(e.target.value)} className="min-h-11 rounded-xl border px-3"/></label><label className="grid gap-1 text-sm font-semibold">Status<select value={status} onChange={e=>setStatus(e.target.value)} className="min-h-11 rounded-xl border px-3"><option value="">All statuses</option>{["PENDING","APPROVED","REJECTED","CANCELLED"].map(v=><option key={v}>{v}</option>)}</select></label></div>
  {query.isPending&&<p className="mt-6">Loading requests…</p>}{query.isError&&<p className="mt-6 text-red-700">Requests could not be loaded.</p>}<div className="mt-6 grid gap-4">{query.data?.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-bold">{item.patient_name}</h3><p className="text-sm text-slate-600">{item.therapy_name} · {item.requested_duration_minutes} minutes</p><p>{item.preferred_date} at {item.preferred_time}</p></div><strong>{item.status}</strong></div><dl className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="font-semibold">Service address</dt><dd>{item.address}, {item.city} {item.pin_code}</dd></div><div><dt className="font-semibold">Validated total</dt><dd>₹{item.final_amount??"—"}{item.commercial_snapshot?.offer_title?` · ${item.commercial_snapshot.offer_title}`:""}</dd></div><div><dt className="font-semibold">Requested</dt><dd>{new Date(item.created_at).toLocaleString()}</dd></div></dl>{item.status==="REJECTED"&&item.rejection_customer_reason&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-red-800">{item.rejection_customer_reason}</p>}
  {item.status==="PENDING"&&<div className="mt-4 grid gap-3"><button onClick={()=>setActive(active===item.id?null:item.id)} className="min-h-11 justify-self-start rounded-xl bg-emerald-700 px-4 font-bold text-white">Accept &amp; assign</button>{active===item.id&&<div className="grid gap-3 rounded-xl bg-emerald-50 p-4"><p className="font-semibold">Eligible for this therapy, clinic, service area and exact slot</p>{eligible.isPending&&<p>Checking current availability…</p>}{eligible.data?.map(person=><label key={person.id} className="flex gap-3 rounded-xl border bg-white p-3"><input type="radio" name={`practitioner-${item.id}`} checked={selected[item.id]===person.id} onChange={()=>setSelected(v=>({...v,[item.id]:person.id}))}/><span><strong>{person.full_name}</strong><span className="block text-sm text-slate-600">{person.qualification} · {person.experience_years} years · {person.specialization||"General physiotherapy"}</span></span></label>)}{eligible.data?.length===0&&<p>No eligible practitioners are available for this slot.</p>}<button disabled={!selected[item.id]||decide.isPending} onClick={()=>decide.mutate({id:item.id,payload:{action:"ACCEPT_ASSIGN",physiotherapist:selected[item.id]}})} className="min-h-11 rounded-xl bg-emerald-800 font-bold text-white disabled:opacity-50">Confirm assignment</button></div>}
  <details className="rounded-xl border border-red-100 p-4"><summary className="cursor-pointer font-bold text-red-700">Reject request</summary><div className="mt-3 grid gap-3"><label className="grid gap-1 font-semibold">Reason category<select value={category[item.id]??""} onChange={e=>setCategory(v=>({...v,[item.id]:e.target.value}))} className="min-h-11 rounded-xl border px-3"><option value="">Select</option>{rejectionCategories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="grid gap-1 font-semibold">Customer-safe reason<textarea value={reason[item.id]??""} onChange={e=>setReason(v=>({...v,[item.id]:e.target.value}))} className="rounded-xl border p-3"/></label><label className="grid gap-1 font-semibold">Internal note (optional)<textarea value={note[item.id]??""} onChange={e=>setNote(v=>({...v,[item.id]:e.target.value}))} className="rounded-xl border p-3"/></label><button disabled={!category[item.id]||(reason[item.id]?.trim().length??0)<3||decide.isPending} onClick={()=>decide.mutate({id:item.id,payload:{action:"REJECT",rejection_category:category[item.id],customer_reason:reason[item.id],internal_note:note[item.id]}})} className="min-h-11 rounded-xl border border-red-300 font-bold text-red-700 disabled:opacity-50">Confirm rejection</button></div></details>{decide.isError&&<p role="alert" className="text-red-700">{decide.error.message}</p>}</div>}</article>)}</div>{query.data?.length===0&&<p className="mt-8 text-slate-600">No appointment requests match these filters.</p>}</section>;
}
