import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import {beforeEach,describe,expect,it,vi} from "vitest";
import {OwnerRequests} from "./owner-requests";

const request={id:"request-1",therapy:"t1",therapy_name:"Kati Basti",requested_therapy_names:["Kati Basti"],requested_duration_minutes:45,patient_name:"Asha",preferred_date:"2026-09-15",preferred_time:"10:00:00",address:"163 C Block",city:"Meerut",pin_code:"250004",status:"PENDING",created_at:"2026-09-07T08:00:00Z",final_amount:"1900.00",commercial_snapshot:{offer_title:"",package_name:"",final_amount:"1900.00"}};
function setup(){let state={...request};const calls:Array<Record<string,unknown>>=[];const fetchMock=vi.spyOn(global,"fetch").mockImplementation(async(input,init)=>{const url=String(input);if(url.includes("eligible-physiotherapists"))return new Response(JSON.stringify([{id:"p0",full_name:"Busy Therapist",qualification:"BPT",age:30,experience_years:3,experience_months:0,specialization:"",expertise:["Kati Basti"],rating:null,review_count:0,has_photo:false,eligible:false,eligibility_reason:"Overlapping appointment"},{id:"p1",full_name:"Krishna",qualification:"MPT",age:31,experience_years:2,experience_months:0,specialization:"Orthopaedic",expertise:["Kati Basti"],rating:4.5,review_count:2,has_photo:false,eligible:true,eligibility_reason:"Available for this requested time"}]),{status:200});if(url.endsWith("/decision")&&init?.method==="POST"){const body=JSON.parse(String(init.body));calls.push(body);if(body.action==="ACCEPT"){state={...state,status:"APPROVED"};return new Response(JSON.stringify(state),{status:200})}return new Response(JSON.stringify({...state,appointment:{id:"a1",physiotherapist_name:"Krishna",scheduled_start:"2026-09-15T10:00:00+05:30"}}),{status:200})}return new Response(JSON.stringify({count:1,next:null,previous:null,results:[state]}),{status:200})});const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return {calls,fetchMock,...render(<QueryClientProvider client={client}><OwnerRequests/></QueryClientProvider>)};}
describe("owner request assignment",()=>{beforeEach(()=>vi.restoreAllMocks());it("accepts first, filters the exact slot, and then confirms one canonical appointment",async()=>{const {calls}=setup();fireEvent.click(await screen.findByRole("button",{name:"Accept Request"}));await waitFor(()=>expect(calls[0]).toMatchObject({action:"ACCEPT"}));fireEvent.click(await screen.findByRole("button",{name:"Assign Therapist / Book Slot"}));const radios=await screen.findAllByRole("radio");expect(radios[0]).toBeDisabled();expect(screen.getByText("Overlapping appointment")).toBeInTheDocument();fireEvent.click(radios[1]);fireEvent.click(screen.getByRole("button",{name:"Confirm Appointment"}));await waitFor(()=>expect(calls[1]).toMatchObject({action:"ASSIGN",physiotherapist:"p1"}));expect(await screen.findByText(/Appointment confirmed with Krishna/)).toBeInTheDocument()});it("requires a customer-safe rejection reason",async()=>{setup();fireEvent.click(await screen.findByText("Reject"));expect(screen.getByRole("button",{name:"Confirm rejection"})).toBeDisabled();fireEvent.change(screen.getByLabelText("Reason category"),{target:{value:"SCHEDULING_CONFLICT"}});fireEvent.change(screen.getByLabelText("Customer-safe reason"),{target:{value:"The slot is unavailable."}});expect(screen.getByRole("button",{name:"Confirm rejection"})).toBeEnabled()})});

it("shows canonical booked history instead of assignment controls",async()=>{vi.spyOn(global,"fetch").mockResolvedValue(new Response(JSON.stringify({count:1,next:null,previous:null,results:[{...request,status:"APPROVED",appointment:{id:"a1",status:"COMPLETED",physiotherapist_name:"Krishna",scheduled_start:"2026-09-15T10:00:00+05:30",duration_minutes:45,payment_status:"PAID",payment_amount_due:"1900.00"}}]}),{status:200}));render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><OwnerRequests/></QueryClientProvider>);expect(await screen.findByText("SESSION COMPLETED")).toBeInTheDocument();expect(screen.getByText(/Assigned therapist: Krishna/)).toBeInTheDocument();expect(screen.queryByRole("button",{name:"Assign Therapist / Book Slot"})).not.toBeInTheDocument();expect(screen.getByText(/Payment: PAID · ₹1900.00/)).toBeInTheDocument()});
