"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { requestJson } from "@/lib/api/client";
import type { AppointmentRequest } from "@/lib/appointments/contracts";

export function OwnerRequests() {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [remarks, setRemarks] = useState<Record<string, string>>({}); const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ["owner-appointments", search, status], queryFn: () => requestJson<AppointmentRequest[]>(`/api/owner/appointment-requests?search=${encodeURIComponent(search)}&status=${encodeURIComponent(status)}`), refetchInterval: 5_000 });
  const update = useMutation({ mutationFn: ({ id, nextStatus }: { id: string; nextStatus: string }) => requestJson(`/api/owner/appointment-requests/${id}`, { method: "PATCH", body: JSON.stringify({ status: nextStatus, owner_remarks: remarks[id] ?? "" }) }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["owner-appointments"] }) });
  return <section aria-labelledby="requests-heading"><div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5"><h2 id="requests-heading" className="text-2xl font-bold text-emerald-950">Appointment Requests</h2><p className="mt-2 text-emerald-900">Review incoming home-service requests. Approval does not assign a therapist or collect payment.</p></div><div className="mt-6 grid gap-3 sm:grid-cols-[1fr_14rem]"><label className="grid gap-1 text-sm font-semibold">Search<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name, mobile, therapy or status" className="min-h-11 rounded-xl border border-slate-300 px-3"/></label><label className="grid gap-1 text-sm font-semibold">Status<select value={status} onChange={(event) => setStatus(event.target.value)} className="min-h-11 rounded-xl border border-slate-300 px-3"><option value="">All statuses</option>{["PENDING", "APPROVED", "REJECTED", "CANCELLED"].map((item) => <option key={item}>{item}</option>)}</select></label></div>{query.isPending && <p className="mt-6">Loading requests…</p>}{query.isError && <p className="mt-6 text-red-700">Requests could not be loaded.</p>}<div className="mt-6 grid gap-4">{query.data?.map((request) => <article key={request.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-bold">{request.patient_name}</h3><p className="text-sm text-slate-600">{request.mobile_number} · {request.therapy_name}</p><p className="mt-1 text-sm">{request.preferred_date} at {request.preferred_time}</p></div><strong className="rounded-full bg-emerald-50 px-3 py-1 text-sm text-emerald-800">{request.status}</strong></div><p className="mt-4 text-sm text-slate-700">{request.problem_description}</p>{request.status === "PENDING" && <div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto_auto]"><label className="grid gap-1 text-sm font-semibold">Remarks<textarea value={remarks[request.id] ?? ""} onChange={(event) => setRemarks((value) => ({ ...value, [request.id]: event.target.value }))} className="rounded-xl border border-slate-300 p-3"/></label><button onClick={() => update.mutate({ id: request.id, nextStatus: "APPROVED" })} className="min-h-11 self-end rounded-xl bg-emerald-700 px-4 font-bold text-white">Approve</button><button onClick={() => update.mutate({ id: request.id, nextStatus: "REJECTED" })} className="min-h-11 self-end rounded-xl border border-red-300 px-4 font-bold text-red-700">Reject</button></div>}</article>)}</div>{query.data?.length === 0 && <p className="mt-8 text-slate-600">No appointment requests match these filters.</p>}</section>;
}
