"use client";

import {useInfiniteQuery,useMutation,useQueryClient} from "@tanstack/react-query";
import {requestJson} from "@/lib/api/client";
import type {OperationalAppointmentPage} from "@/lib/appointments/contracts";

export function PaymentOperations(){
 const client=useQueryClient();
 const query=useInfiniteQuery({queryKey:["payment-operations"],queryFn:({pageParam})=>requestJson<OperationalAppointmentPage>(`/api/schedule/operations?payment_status=VERIFICATION_PENDING&page_size=8&page=${pageParam}`),initialPageParam:1,getNextPageParam:(last,pages)=>last.next?pages.length+1:undefined,refetchInterval:15_000});
 const items=query.data?.pages.flatMap(page=>page.results)??[];
 const received=useMutation({mutationFn:({id,reference,note}:{id:string;reference:string;note:string})=>requestJson(`/api/schedule/${id}/payment`,{method:"POST",body:JSON.stringify({status:"PAID",reference,note})}),onSuccess:()=>{client.invalidateQueries({queryKey:["payment-operations"]});client.invalidateQueries({queryKey:["schedule-operations"]})}});
 return <section><h1 className="text-3xl font-bold">Payment Verification</h1><p className="mt-2 text-slate-600">Only an Owner can verify customer-submitted payments. Verification confirms the booking and unlocks therapist assignment.</p><div className="mt-5 grid gap-4 lg:grid-cols-2">{items.map(item=><form key={item.id} onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);received.mutate({id:item.id,reference:String(data.get("reference")||""),note:String(data.get("note")||"")})}} className="grid gap-3 rounded-2xl border bg-white p-5 sm:grid-cols-2"><div className="sm:col-span-2"><strong>{item.patient_name}</strong><p>{(item.requested_therapy_names?.length?item.requested_therapy_names:[item.therapy_name]).join(", ")} · {new Date(item.scheduled_start).toLocaleString()}</p><p className="mt-2 font-bold">Submitted amount: {item.payment_amount_due?`₹${item.payment_amount_due}`:"Amount unavailable"}</p><p className="font-semibold text-amber-800">Customer marked “I Have Paid” · verification required</p></div><label className="grid gap-1">Payment reference (optional)<input name="reference" className="min-h-12 rounded-xl border px-3"/></label><label className="grid gap-1">Internal note (optional)<input name="note" className="min-h-12 rounded-xl border px-3"/></label><button disabled={received.isPending} className="button-primary sm:col-span-2">{received.isPending?"Verifying…":"Verify Payment & Confirm Booking"}</button></form>)}</div>{items.length===0&&!query.isPending&&<p className="mt-5 rounded-xl border border-dashed bg-white p-5 text-slate-600">No payments are awaiting verification.</p>}{query.hasNextPage&&<button type="button" onClick={()=>query.fetchNextPage()} disabled={query.isFetchingNextPage} className="mt-5 min-h-11 rounded-xl border border-emerald-700 px-5 font-bold text-emerald-800">{query.isFetchingNextPage?"Loading…":"Show More"}</button>}{received.isError&&<p role="alert" className="mt-3 text-red-700">{received.error.message}</p>}</section>;
}
