"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { requestJson } from "@/lib/api/client";
import type { ReviewItem, ReviewSummary } from "@/lib/appointments/contracts";

type ReviewPage = { results:ReviewItem[] };
const Stars=({value}:{value:number})=><span className="text-amber-600" aria-label={`${value} out of 5 stars`}>{"★".repeat(Math.round(value))}{"☆".repeat(5-Math.round(value))}</span>;

export function ReviewModerationPanel(){
  const qc=useQueryClient(); const [filters,setFilters]=useState({status:"",rating:"",date_from:"",date_to:""}); const [reason,setReason]=useState<Record<string,string>>({});
  const query=useQuery({queryKey:["review-operations",filters],queryFn:()=>requestJson<ReviewPage>(`/api/reviews/operations?${new URLSearchParams(filters)}`)});
  const moderate=useMutation({mutationFn:(value:{id:string;moderation_status:"APPROVED"|"HIDDEN";reason?:string})=>requestJson(`/api/reviews/operations/${value.id}/moderate`,{method:"POST",body:JSON.stringify(value)}),onSuccess:()=>qc.invalidateQueries({queryKey:["review-operations"]})});
  return <section className="mt-8"><h2 className="text-2xl font-bold">Customer review queue</h2><div className="mt-3 grid gap-2 rounded-2xl border bg-white p-4 sm:grid-cols-4"><label>Status<select className="block min-h-11 w-full rounded-xl border px-2" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All</option><option value="PENDING">Pending Review</option><option value="APPROVED">Approved</option><option value="HIDDEN">Hidden / Rejected</option></select></label><label>Rating<select className="block min-h-11 w-full rounded-xl border px-2" value={filters.rating} onChange={e=>setFilters({...filters,rating:e.target.value})}><option value="">All</option>{[5,4,3,2,1].map(v=><option key={v}>{v}</option>)}</select></label><label>From<input type="date" className="block min-h-11 w-full rounded-xl border px-2" value={filters.date_from} onChange={e=>setFilters({...filters,date_from:e.target.value})}/></label><label>To<input type="date" className="block min-h-11 w-full rounded-xl border px-2" value={filters.date_to} onChange={e=>setFilters({...filters,date_to:e.target.value})}/></label></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{query.data?.results.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-2"><strong>{item.customer_display_name} · {item.therapy_name}</strong><Stars value={item.stars}/></div><p className="mt-1 text-sm">{item.physiotherapist_name} · {new Date(item.appointment_date).toLocaleDateString()}</p><p className="mt-3 whitespace-pre-wrap">{item.comment}</p><p className="mt-3 text-sm font-bold">Publicly visible: {item.moderation_status==="APPROVED"?"Yes":"No"}</p>{item.moderation_reason&&<p className="text-sm">Reason: {item.moderation_reason}</p>}<div className="mt-4 grid gap-2"><button disabled={item.moderation_status==="APPROVED"||moderate.isPending} onClick={()=>moderate.mutate({id:item.id,moderation_status:"APPROVED"})} className="min-h-11 rounded-xl bg-emerald-700 px-4 font-bold text-white disabled:opacity-50">Make publicly visible</button><label className="text-sm font-semibold">Reason to hide<input minLength={3} maxLength={500} className="mt-1 min-h-11 w-full rounded-xl border px-3" value={reason[item.id]??""} onChange={e=>setReason({...reason,[item.id]:e.target.value})}/></label><button disabled={item.moderation_status==="HIDDEN"||(reason[item.id]??"").trim().length<3||moderate.isPending} onClick={()=>moderate.mutate({id:item.id,moderation_status:"HIDDEN",reason:reason[item.id]})} className="min-h-11 rounded-xl border px-4 font-bold text-red-700 disabled:opacity-50">Keep private</button></div></article>)}</div></section>;
}

export function PractitionerReviews(){const query=useQuery({queryKey:["practitioner-reviews"],queryFn:()=>requestJson<ReviewSummary>("/api/reviews/mine")});return <section className="mt-8"><h2 className="text-2xl font-bold">Your customer reviews</h2>{query.data&&<div className="mt-2"><Stars value={query.data.review_count?query.data.average_rating??0:0}/><strong className="ml-2">{query.data.review_count?query.data.average_rating?.toFixed(1):""}</strong><p className="text-sm text-slate-600">{query.data.review_count?`Based on ${query.data.review_count} approved reviews`:"No ratings yet"}</p>{query.data.review_count>0&&<a href="/profile#customer-reviews" className="font-semibold text-emerald-800 underline">View Reviews</a>}</div>}<div className="mt-4 grid gap-3 lg:grid-cols-2">{query.data?.reviews.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5"><Stars value={item.stars}/><p className="mt-2 whitespace-pre-wrap">{item.comment}</p><p className="mt-2 text-sm">{new Date(item.created_at).toLocaleDateString()} · {item.moderation_status.replaceAll("_"," ")}</p></article>)}</div></section>}

export function PublicReviews(){const query=useQuery({queryKey:["public-reviews"],queryFn:()=>requestJson<ReviewSummary>("/api/reviews/public")});return <section className="section bg-[#f7f3e9]" aria-labelledby="customer-reviews-title"><div className="site-container"><p className="eyebrow">Approved customer reviews</p><h2 id="customer-reviews-title" className="mt-3 font-serif text-4xl text-[#103c27]">Real experiences, shared by customers</h2>{query.isPending&&<p className="mt-6 text-[#5b6c63]">Loading approved reviews…</p>}{query.isError&&<p className="mt-6 text-red-700">Approved reviews could not be loaded.</p>}{query.data&&query.data.review_count===0&&<div className="mt-8 rounded-3xl border border-dashed border-[#0b6b3a]/25 bg-white/70 p-8 text-center"><p className="font-serif text-2xl text-[#103c27]">No approved reviews to display yet.</p><p className="mt-2 text-sm text-[#5b6c63]">Completed-service reviews appear here only after moderation approval.</p></div>}{query.data&&query.data.review_count>0&&<><p className="mt-2 text-[#5b6c63]">{query.data.average_rating?.toFixed(1)} out of 5 from {query.data.review_count} approved reviews</p><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{query.data.reviews.slice(0,6).map((item,index)=><article key={`${item.created_at}-${index}`} className="review-card"><Stars value={item.stars}/><p className="mt-4 line-clamp-5 whitespace-pre-wrap break-words text-[#405f4f]">{item.comment||"Rating shared without a written comment."}</p><p className="mt-5 text-sm font-bold text-[#103c27]">{item.customer_display_name}</p><p className="mt-1 text-xs text-[#68786f]">{item.physiotherapist_name} · <time>{new Date(item.created_at).toLocaleDateString(undefined,{month:"long",year:"numeric"})}</time></p></article>)}</div></>}</div></section>}
