"use client";

import Link from "next/link";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useState} from "react";
import {PasswordCreationFields,isStrongPassword} from "@/components/auth/password-creation-fields";
import {ProfileAvatar} from "@/components/staff/profile-avatar";
import {requestJson} from "@/lib/api/client";
import {loadOtpWidgetConfig,sendMsg91Otp,verifyMsg91Otp,type OtpWidgetConfig} from "@/lib/auth/msg91-widget";

export type CustomerProfile={id:string;first_name:string;last_name:string;full_name:string;email:string;mobile_number:string;gender:string;date_of_birth:string|null;age:number|null;photo_url:string;updated_at:string;address:{address_line_1:string;address_line_2:string;landmark:string;city:string;region:string;pin_code:string}|null};

export function CustomerProfilePage(){
 const qc=useQueryClient();const query=useQuery({queryKey:["customer-profile"],queryFn:()=>requestJson<CustomerProfile>("/api/customer/profile")});
 const [editing,setEditing]=useState(false);const [message,setMessage]=useState("");const [security,setSecurity]=useState<""|"mobile"|"password">("");
 const [current,setCurrent]=useState("");const [next,setNext]=useState("");const [confirm,setConfirm]=useState("");const [number,setNumber]=useState("");const [verificationId,setVerificationId]=useState("");const [otp,setOtp]=useState("");const [config,setConfig]=useState<OtpWidgetConfig>({enabled:false});
 const refresh=()=>{qc.invalidateQueries({queryKey:["customer-profile"]});qc.invalidateQueries({queryKey:["session"]})};
 const photo=useMutation({mutationFn:(file:File|null)=>{const body=new FormData();if(file)body.append("profile_photo",file);return requestJson("/api/customer/profile/photo",{method:file?"POST":"DELETE",...(file?{body}:{})})},onSuccess:()=>{setMessage("Profile photo updated.");refresh()}});
 const save=useMutation({mutationFn:(payload:Record<string,string>)=>requestJson<CustomerProfile>("/api/customer/profile",{method:"PATCH",body:JSON.stringify(payload)}),onSuccess:()=>{setEditing(false);setMessage("Profile updated.");refresh()}});
 const password=useMutation({mutationFn:()=>requestJson("/api/session/change-password",{method:"POST",body:JSON.stringify({old_password:current,new_password:next,confirm_password:confirm})}),onSuccess:()=>{setSecurity("");setMessage("Password updated.")}});
 const mobile=useMutation({mutationFn:async()=>{const provider=config.enabled?{access_token:await verifyMsg91Otp(config,otp)}:{otp};const proof=await requestJson<{token:string}>("/api/booking-otp/verify",{method:"POST",body:JSON.stringify({verification_id:verificationId,mobile_number:number,...provider})});return requestJson("/api/customer/profile/change-mobile",{method:"POST",body:JSON.stringify({mobile_number:number,current_password:current,booking_verification_token:proof.token})})},onSuccess:()=>{setSecurity("");setMessage("Verified mobile updated.");refresh()}});
 if(query.isPending)return <p>Loading profile…</p>;if(!query.data)return <p role="alert">Your customer profile could not be loaded.</p>;const p=query.data;
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);save.mutate(Object.fromEntries(f.entries()) as Record<string,string>)}
 async function sendOtp(){setMessage("");try{const c=await loadOtpWidgetConfig();const issued=await requestJson<{verification_id:string}>("/api/booking-otp/issue",{method:"POST",body:JSON.stringify({mobile_number:number})});if(c.enabled)await sendMsg91Otp(c,number);setConfig(c);setVerificationId(issued.verification_id)}catch(e){setMessage(e instanceof Error?e.message:"OTP could not be sent.")}}
 return <div className="space-y-6"><section className="flex flex-wrap items-center gap-5 rounded-3xl border bg-white p-6 shadow-sm"><ProfileAvatar profile={{full_name:p.full_name,photo_url:p.photo_url}}/><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Customer profile</p><h2 className="text-3xl font-bold">{p.full_name}</h2><p className="text-slate-600">Verified mobile: {p.mobile_number}</p></div><button className="button-primary" onClick={()=>setEditing(v=>!v)}>{editing?"Cancel":"Edit Profile"}</button><div className="w-full flex flex-wrap gap-3"><label className="button-secondary cursor-pointer">{p.photo_url?"Change Photo":"Upload Photo"}<input aria-label="Upload profile photo" type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)photo.mutate(file)}}/></label>{p.photo_url&&<button className="button-secondary text-red-700" onClick={()=>photo.mutate(null)}>Remove Photo</button>}</div></section>{message&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-900">{message}</p>}
 {editing?<form onSubmit={submit} className="grid gap-4 rounded-2xl border bg-white p-6 sm:grid-cols-2"><Field name="first_name" label="First name" value={p.first_name}/><Field name="last_name" label="Last name" value={p.last_name}/><Field name="email" label="Email" value={p.email} type="email"/><label className="grid gap-1 font-semibold">Gender<select name="gender" defaultValue={p.gender} className="min-h-11 rounded-xl border px-3"><option value="FEMALE">Female</option><option value="MALE">Male</option><option value="OTHER">Other</option><option value="PREFER_NOT_TO_SAY">Prefer not to say</option></select></label><Field name="date_of_birth" label="Date of birth" value={p.date_of_birth??""} type="date"/><Field name="address_line_1" label="Primary address" value={p.address?.address_line_1??""}/><Field name="address_line_2" label="Address line 2" value={p.address?.address_line_2??""}/><Field name="landmark" label="Landmark" value={p.address?.landmark??""}/><Field name="city" label="City" value={p.address?.city??""}/><Field name="region" label="State / region" value={p.address?.region??""}/><Field name="pin_code" label="PIN" value={p.address?.pin_code??""}/><button disabled={save.isPending} className="button-primary sm:col-span-2">{save.isPending?"Saving…":"Save Profile"}</button></form>:<><section className="rounded-2xl border bg-white p-6"><h3 className="text-xl font-bold">Personal Information</h3><dl className="mt-4 grid gap-4 sm:grid-cols-2"><Item label="First name" value={p.first_name}/><Item label="Last name" value={p.last_name||"Not provided"}/><Item label="Gender" value={p.gender.replaceAll("_"," ")}/><Item label="Date of birth" value={p.date_of_birth?new Date(`${p.date_of_birth}T00:00:00`).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"}):"Not provided"}/><Item label="Age" value={p.age==null?"Not available":`${p.age} years`}/><Item label="Email" value={p.email||"Not provided"}/><Item label="Verified mobile" value={p.mobile_number}/></dl></section><section className="rounded-2xl border bg-white p-6"><h3 className="text-xl font-bold">Address Information</h3><p className="mt-3">{p.address?`${p.address.address_line_1}${p.address.address_line_2?`, ${p.address.address_line_2}`:""}${p.address.landmark?`, ${p.address.landmark}`:""}, ${p.address.city}, ${p.address.region} ${p.address.pin_code}`:"No primary address available."}</p></section></>}
 <section className="rounded-2xl border bg-white p-6"><h3 className="text-xl font-bold">Security</h3><p className="mt-2">Verified mobile: <strong>{p.mobile_number}</strong></p><div className="mt-4 flex flex-wrap gap-3"><button className="button-secondary" onClick={()=>setSecurity("mobile")}>Change Mobile via OTP</button><button className="button-secondary" onClick={()=>setSecurity("password")}>Change Password</button><Link className="button-secondary" href="/customer-forgot-password">Forgot / Reset Password</Link></div>{security&&<div className="mt-4 max-w-xl space-y-3 rounded-xl bg-slate-50 p-4"><label className="grid gap-1 font-semibold">Current password<input type="password" value={current} onChange={e=>setCurrent(e.target.value)} className="min-h-11 rounded-xl border px-3"/></label>{security==="password"?<><PasswordCreationFields password={next} confirmPassword={confirm} onPasswordChange={setNext} onConfirmPasswordChange={setConfirm}/><button className="button-primary" disabled={!current||!isStrongPassword(next)||next!==confirm||password.isPending} onClick={()=>password.mutate()}>Save Password</button></>:<><label className="grid gap-1 font-semibold">New mobile number<input value={number} maxLength={10} inputMode="numeric" onChange={e=>{setNumber(e.target.value.replace(/\D/g,""));setVerificationId("")}} className="min-h-11 rounded-xl border px-3"/></label><p className="text-sm text-slate-600">Enter the exact 10-digit Indian mobile number that will receive the OTP.</p><button className="button-secondary" disabled={!current||!/^[6-9]\d{9}$/.test(number)} onClick={sendOtp}>{verificationId?"Resend OTP":"Send OTP"}</button>{verificationId&&<><label className="grid gap-1 font-semibold">OTP for new mobile<input value={otp} maxLength={6} inputMode="numeric" onChange={e=>setOtp(e.target.value.replace(/\D/g,""))} className="min-h-11 rounded-xl border px-3"/></label><button className="button-primary" disabled={otp.length!==6||mobile.isPending} onClick={()=>mobile.mutate()}>Verify and Change Mobile</button></>}</>}<button className="button-secondary" onClick={()=>setSecurity("")}>Cancel</button></div>}</section></div>
}
function Field({name,label,value,type="text"}:{name:string;label:string;value:string;type?:string}){return <label className="grid gap-1 font-semibold">{label}<input name={name} type={type} defaultValue={value} className="min-h-11 rounded-xl border px-3"/></label>}
function Item({label,value}:{label:string;value:string}){return <div><dt className="font-semibold text-slate-600">{label}</dt><dd>{value}</dd></div>}
