import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import {beforeEach,describe,expect,it,vi} from "vitest";
import {CustomerProfilePage} from "./customer-profile";

const profile={id:"p1",first_name:"Asha",last_name:"Sharma",full_name:"Asha Sharma",email:"asha@example.com",mobile_number:"+919876543210",gender:"FEMALE",date_of_birth:"1992-09-07",age:34,photo_url:"",updated_at:"2026-09-07T10:00:00Z",address:{address_line_1:"163 C Block",address_line_2:"",landmark:"Park",city:"Meerut",region:"Uttar Pradesh",pin_code:"250004"}};
function setup(){const fetchMock=vi.spyOn(global,"fetch").mockImplementation(async(input,init)=>{const url=String(input);if(url==="/api/customer/profile"&&init?.method==="PATCH")return new Response(JSON.stringify({...profile,...JSON.parse(String(init.body))}),{status:200});if(url==="/api/customer/profile/photo")return new Response(JSON.stringify({...profile,photo_url:"/api/customer/profile/photo"}),{status:init?.method==="DELETE"?204:200});return new Response(JSON.stringify(profile),{status:200})});const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return {fetchMock,...render(<QueryClientProvider client={client}><CustomerProfilePage/></QueryClientProvider>)};}
describe("customer profile",()=>{beforeEach(()=>vi.restoreAllMocks());
 it("shows a friendly profile with initials, DOB-derived age and no backend metadata",async()=>{setup();expect(await screen.findByRole("heading",{name:"Asha Sharma"})).toBeInTheDocument();expect(screen.getByLabelText("Asha Sharma avatar")).toHaveTextContent("AS");expect(screen.getByText("34 years")).toBeInTheDocument();expect(screen.queryByText(/organization|clinic scope|backend validated|active role/i)).not.toBeInTheDocument()});
 it("edits supported fields without exposing direct mobile editing",async()=>{const {fetchMock}=setup();await screen.findByRole("heading",{name:"Asha Sharma"});fireEvent.click(screen.getByRole("button",{name:"Edit Profile"}));expect(screen.queryByLabelText(/mobile/i)).not.toBeInTheDocument();fireEvent.change(screen.getByLabelText("First name"),{target:{value:"Anita"}});fireEvent.click(screen.getByRole("button",{name:"Save Profile"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith("/api/customer/profile",expect.objectContaining({method:"PATCH"})));const call=fetchMock.mock.calls.find(([u,i])=>String(u)==="/api/customer/profile"&&i?.method==="PATCH");expect(JSON.parse(String(call?.[1]?.body))).not.toHaveProperty("mobile_number")});
 it("uploads and removes the optional profile photo",async()=>{const {fetchMock}=setup();await screen.findByRole("heading",{name:"Asha Sharma"});fireEvent.change(screen.getByLabelText("Upload profile photo"),{target:{files:[new File(["image"],"asha.png",{type:"image/png"})]}});await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith("/api/customer/profile/photo",expect.objectContaining({method:"POST"})));});
 it("keeps verified mobile behind the OTP security action",async()=>{setup();await screen.findByRole("heading",{name:"Asha Sharma"});fireEvent.click(screen.getByRole("button",{name:"Change Mobile via OTP"}));expect(screen.getByText(/exact 10-digit Indian mobile number/i)).toBeInTheDocument();expect(screen.getByLabelText("Current password")).toHaveAttribute("type","password")});
});
