"use client";
import {ProfileAvatar,leaveDate} from "./profile-avatar";
import {useRouter} from "next/navigation";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useState} from "react";
import {StaffCreationWizard,formatExperience} from "@/components/staff/staff-creation-wizard";
import {requestJson} from "@/lib/api/client";
import type {CommercialCatalog} from "@/lib/appointments/contracts";
import type {StaffPage,StaffProfile} from "@/lib/staff/contracts";

function Credentials({p}:{p:StaffProfile}){const values=p.specialization_names?.length?p.specialization_names:p.verified_therapy_names??[],summary=values.length>3?`${values.slice(0,3).join(", ")} +${values.length-3} more`:values.join(", ");return <><strong>{p.qualification||"Qualification not listed"}</strong><span className="block">{p.age!=null?`Age: ${p.age} years`:"DOB required"}</span><span className="block">{formatExperience(p.experience_years,p.experience_months??0)}</span><span className="block text-slate-600">{summary||"Specialization not listed"}</span></>}

export function StaffDirectory({allowManagers=false}:{allowManagers?:boolean}){
 const router=useRouter(),client=useQueryClient();const [search,setSearch]=useState(""),[type]=useState("PHYSIOTHERAPIST"),[status,setStatus]=useState(""),[showWizard,setShowWizard]=useState(false),[openMenu,setOpenMenu]=useState<string|null>(null),[deleteTarget,setDeleteTarget]=useState<StaffProfile|null>(null),[confirmation,setConfirmation]=useState(""),[deleteError,setDeleteError]=useState("");
 const query=useQuery({queryKey:["staff",search,type,status],queryFn:()=>requestJson<StaffPage>(`/api/staff/profiles?search=${encodeURIComponent(search)}&type=${type}&status=${status}`)}),session=useQuery({queryKey:["session-staff"],queryFn:()=>requestJson<{access:{permitted_clinics:Array<{id:string;slug:string}>}}>('/api/session/me')}),catalog=useQuery({queryKey:["staff-therapy-catalog"],queryFn:()=>requestJson<CommercialCatalog>("/api/commercial/public")}),options=useQuery({queryKey:["staff-options"],queryFn:()=>requestJson<{service_areas:Array<{id:string;name:string}>}>("/api/staff/options")});
 const toggle=useMutation({mutationFn:({id,is_active}:{id:string;is_active:boolean})=>requestJson(`/api/staff/profiles/${id}/status`,{method:"POST",body:JSON.stringify({is_active,reason:"Staff status updated by authorized manager."})}),onSuccess:()=>{setOpenMenu(null);client.invalidateQueries({queryKey:["staff"]})}}),remove=useMutation({mutationFn:(p:StaffProfile)=>requestJson(`/api/staff/profiles/${p.id}`,{method:"DELETE"}),onSuccess:()=>{setDeleteTarget(null);setConfirmation("");setDeleteError("");client.invalidateQueries({queryKey:["staff"]})},onError:e=>setDeleteError(e.message)});
 return <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">Physiotherapists</h2><p className="text-slate-600">Professional staff profiles, access and scheduling coverage.</p></div><div className="flex gap-3"><button onClick={()=>setShowWizard(true)} className="button-primary">+ Add Therapist</button>{showWizard&&<button onClick={()=>setShowWizard(false)} className="button-secondary">Close</button>}</div></div>
 {showWizard&&<StaffCreationWizard role="PHYSIOTHERAPIST" clinics={session.data?.access.permitted_clinics??[]} therapies={(catalog.data?.therapies??[]).filter(v=>v.is_active!==false&&!v.is_offer_free_addon).map(v=>({id:v.id,name:v.name}))} serviceAreas={options.data?.service_areas??[]} onCreated={()=>{client.invalidateQueries({queryKey:["staff"]});setShowWizard(false)}}/>}
 <div className="mt-5 grid gap-3 sm:grid-cols-3"><input aria-label="Search staff" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search staff" className="min-h-11 rounded-xl border px-3"/><select aria-label="Filter status" value={status} onChange={e=>setStatus(e.target.value)} className="min-h-11 rounded-xl border px-3"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>
 <div className="mt-5 overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50"><tr>{["Professional","Role","Credentials","Schedule","Account","Actions"].map(v=><th className="p-4" key={v}>{v}</th>)}</tr></thead><tbody>{query.data?.results.map(item=><tr className="border-t align-top" key={item.id}><td className="p-4"><div className="flex items-center gap-3"><ProfileAvatar profile={item}/><span><strong>{item.full_name}</strong><small className="block text-slate-500">{item.profile_source==="PRACTITIONER_APPLICATION"?"Self-applied":"Owner-created"}</small></span></div></td><td className="p-4">{item.staff_type==="MANAGER"?"Manager":"Physiotherapist"}</td><td className="p-4"><Credentials p={item}/></td><td className="p-4"><span className="block text-slate-600">{item.approved_weekly_rule_count?`${item.approved_weekly_rule_count} days/week`:"Not configured"}</span>{item.upcoming_leave?.[0]&&<span className="block text-red-700">Leave: {leaveDate(item.upcoming_leave[0].from_date)} – {leaveDate(item.upcoming_leave[0].to_date)}{item.upcoming_leave.length>1&&<small className="block">+{item.upcoming_leave.length-1} upcoming</small>}</span>}</td><td className="p-4"><strong>{item.approval_status==="VERIFIED_APPROVED"?"Approved":item.approval_status?.replaceAll("_"," ")??"Pending"}</strong><span className="block">{item.is_active?"Active":"Inactive"}</span>{item.activation_status==="ACTIVATION_PENDING"&&<span className="block text-amber-700">Activation Pending</span>}</td><td className="relative p-4"><button type="button" aria-label={`Actions for ${item.full_name}`} aria-expanded={openMenu===item.id} aria-haspopup="menu" onClick={()=>setOpenMenu(openMenu===item.id?null:item.id)} className="min-h-10 rounded-lg border px-3 font-bold">⋮</button>{openMenu===item.id&&<div role="menu" className="absolute right-4 z-20 mt-1 grid min-w-52 rounded-xl border bg-white p-2 shadow-xl"><button role="menuitem" onClick={()=>router.push(`/owner/therapists/${item.id}/availability`)} className="rounded-lg px-3 py-2 text-left hover:bg-slate-50">View / Manage</button><button role="menuitem" onClick={()=>toggle.mutate({id:item.id,is_active:!item.is_active})} className="rounded-lg px-3 py-2 text-left hover:bg-slate-50">{item.is_active?"Deactivate Therapist":"Activate Therapist"}</button>{allowManagers&&item.staff_type==="PHYSIOTHERAPIST"&&<button role="menuitem" onClick={()=>{setOpenMenu(null);setDeleteTarget(item);setConfirmation("");setDeleteError("")}} className="rounded-lg px-3 py-2 text-left text-red-700 hover:bg-red-50">Delete Therapist</button>}</div>}</td></tr>)}</tbody></table>{query.isPending&&<p className="p-5">Loading staff…</p>}{query.data?.results.length===0&&<p className="p-5">No staff match these filters.</p>}</div>
 {deleteTarget&&<div role="dialog" aria-modal="true" aria-labelledby="delete-therapist-title" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h3 id="delete-therapist-title" className="text-xl font-bold">Delete Therapist Permanently</h3><p className="mt-3">This action permanently removes this therapist account and cannot be undone.</p><p className="mt-2 font-bold">{deleteTarget.full_name}</p><label className="mt-5 grid gap-2 font-semibold">Type DELETE to confirm<input value={confirmation} onChange={e=>setConfirmation(e.target.value)} className="min-h-11 rounded-xl border px-3"/></label>{deleteError&&<p role="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-red-700">{deleteError}</p>}<div className="mt-5 flex justify-end gap-3"><button type="button" onClick={()=>setDeleteTarget(null)} className="button-secondary">Cancel</button><button type="button" disabled={confirmation!=="DELETE"||remove.isPending} onClick={()=>remove.mutate(deleteTarget)} className="min-h-11 rounded-xl bg-red-700 px-5 font-bold text-white disabled:opacity-50">{remove.isPending?"Deleting…":"Delete Permanently"}</button></div></div></div>}</section>
}

export function ManagerDashboard(){const query=useQuery({queryKey:["manager-staff"],queryFn:()=>requestJson<StaffPage>("/api/staff/profiles?type=PHYSIOTHERAPIST&page_size=50")});const items=query.data?.results??[];return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total Physiotherapists",items.length],["Active",items.filter(v=>v.is_active).length],["Inactive",items.filter(v=>!v.is_active).length],["Available",items.filter(v=>v.availability==="AVAILABLE").length]].map(([label,value])=><article className="rounded-2xl border bg-white p-5" key={label}><p>{label}</p><strong className="text-3xl">{value}</strong></article>)}</div><StaffDirectory/></>}
export {PractitionerIdentity as PhysiotherapistProfile} from "@/components/practitioners/my-profile";
