"use client";

import Image from "next/image";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useState} from "react";
import {StaffCreationWizard} from "@/components/staff/staff-creation-wizard";
import {requestJson} from "@/lib/api/client";
import type {CommercialCatalog} from "@/lib/appointments/contracts";
import type {StaffPage,StaffProfile} from "@/lib/staff/contracts";

export function StaffDirectory({allowManagers=false}:{allowManagers?:boolean}){
 const [search,setSearch]=useState("");const [type,setType]=useState(allowManagers?"":"PHYSIOTHERAPIST");const [status,setStatus]=useState("");const [wizardRole,setWizardRole]=useState<"MANAGER"|"PHYSIOTHERAPIST"|null>(null);const client=useQueryClient();
 const query=useQuery({queryKey:["staff",search,type,status],queryFn:()=>requestJson<StaffPage>(`/api/staff/profiles?search=${encodeURIComponent(search)}&type=${type}&status=${status}`)});
 const session=useQuery({queryKey:["session-staff"],queryFn:()=>requestJson<{access:{permitted_clinics:Array<{id:string;slug:string}>}}>("/api/session/me")});
 const catalog=useQuery({queryKey:["staff-therapy-catalog"],queryFn:()=>requestJson<CommercialCatalog>("/api/commercial/public")});
 const options=useQuery({queryKey:["staff-options"],queryFn:()=>requestJson<{service_areas:Array<{id:string;name:string}>}>("/api/staff/options")});
 const toggle=useMutation({mutationFn:({id,is_active}:{id:string;is_active:boolean})=>requestJson(`/api/staff/profiles/${id}/status`,{method:"POST",body:JSON.stringify({is_active,reason:"Staff status updated by authorized manager."})}),onSuccess:()=>client.invalidateQueries({queryKey:["staff"]})});
 function availability(item:StaffProfile){window.dispatchEvent(new CustomEvent("manage-practitioner-availability",{detail:item.id}));document.getElementById("availability-management")?.scrollIntoView({behavior:"smooth",block:"start"})}
 return <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">{allowManagers?"Managers & Physiotherapists":"Physiotherapists"}</h2><p className="text-slate-600">Professional staff profiles, access and scheduling coverage.</p></div><div className="flex gap-3">{allowManagers&&<button onClick={()=>setWizardRole("MANAGER")} className="button-primary">+ Add Manager</button>}<button onClick={()=>setWizardRole("PHYSIOTHERAPIST")} className="button-primary">+ Add Therapist</button>{wizardRole&&<button onClick={()=>setWizardRole(null)} className="button-secondary">Close</button>}</div></div>
 {wizardRole&&<StaffCreationWizard key={wizardRole} role={wizardRole} clinics={session.data?.access.permitted_clinics??[]} therapies={(catalog.data?.therapies??[]).filter(v=>v.is_active!==false&&!v.is_offer_free_addon).map(v=>({id:v.id,name:v.name}))} serviceAreas={options.data?.service_areas??[]} onCreated={()=>{client.invalidateQueries({queryKey:["staff"]});setWizardRole(null)}}/>}<div className="mt-5 grid gap-3 sm:grid-cols-3"><input aria-label="Search staff" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search staff" className="min-h-11 rounded-xl border px-3"/><select aria-label="Filter role" value={type} onChange={e=>setType(e.target.value)} className="min-h-11 rounded-xl border px-3">{allowManagers&&<option value="">All roles</option>}<option value="MANAGER">Managers</option><option value="PHYSIOTHERAPIST">Physiotherapists</option></select><select aria-label="Filter status" value={status} onChange={e=>setStatus(e.target.value)} className="min-h-11 rounded-xl border px-3"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>
 <div className="mt-5 overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-left text-sm"><thead><tr>{["Professional","Role","Clinic","Credentials","Scheduling","Account","Actions"].map(v=><th className="p-4" key={v}>{v}</th>)}</tr></thead><tbody>{query.data?.results.map(item=><tr className="border-t align-top" key={item.id}><td className="p-4"><div className="flex items-center gap-3">{item.profile_photo?<Image src={item.profile_photo} alt="" width={48} height={48} unoptimized className="size-12 rounded-full object-cover"/>:<span className="grid size-12 place-items-center rounded-full bg-emerald-100 font-bold">{item.full_name.charAt(0)}</span>}<span><strong>{item.full_name}</strong><small className="block text-slate-500">{item.profile_source==="PRACTITIONER_APPLICATION"?"Practitioner application":"Owner-created staff"}</small></span></div></td><td className="p-4">{item.staff_type==="MANAGER"?"Manager":"Physiotherapist"}</td><td className="p-4">{item.clinic_name??"Organization scope"}</td><td className="p-4"><strong>{item.qualification}</strong><span className="block">{item.experience_years} years experience</span><span className="block">{item.specialization_names?.join(", ")||item.verified_therapy_names?.join(", ")||"Specialization not listed"}</span></td><td className="p-4"><strong>{item.approved_weekly_rule_count?`${item.approved_weekly_rule_count} approved weekly rules`:"Weekly hours not configured"}</strong><span className="block">{item.availability} · {item.is_online?"Online":"Offline"}</span></td><td className="p-4"><strong>{item.is_active?"Active":"Inactive"}</strong>{item.staff_type==="PHYSIOTHERAPIST"&&<><span className="block">{item.approval_status==="VERIFIED_APPROVED"?"Verified / Approved":item.approval_status?.replaceAll("_"," ")??"Pending"}</span><span className="block">{item.activation_status==="ACTIVATION_PENDING"?"Activation Pending":"Account Activated"}</span></>}</td><td className="p-4">{item.staff_type==="PHYSIOTHERAPIST"&&<button onClick={()=>availability(item)} className="block font-bold underline">Manage Availability</button>}<button onClick={()=>toggle.mutate({id:item.id,is_active:!item.is_active})} className="font-bold underline">{item.is_active?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table>{query.isPending&&<p className="p-5">Loading staff…</p>}{query.data?.results.length===0&&<p className="p-5">No staff match these filters.</p>}</div></section>
}

export function ManagerDashboard(){const query=useQuery({queryKey:["manager-staff"],queryFn:()=>requestJson<StaffPage>("/api/staff/profiles?type=PHYSIOTHERAPIST&page_size=50")});const items=query.data?.results??[];return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total Physiotherapists",items.length],["Active",items.filter(v=>v.is_active).length],["Inactive",items.filter(v=>!v.is_active).length],["Available",items.filter(v=>v.availability==="AVAILABLE").length]].map(([label,value])=><article className="rounded-2xl border bg-white p-5" key={label}><p>{label}</p><strong className="text-3xl">{value}</strong></article>)}</div><StaffDirectory/></>}

export function PhysiotherapistProfile(){const client=useQueryClient();const query=useQuery({queryKey:["staff-me"],queryFn:()=>requestJson<StaffProfile>("/api/staff/me")});const update=useMutation({mutationFn:(value:Partial<StaffProfile>)=>requestJson("/api/staff/me/availability",{method:"PATCH",body:JSON.stringify(value)}),onSuccess:()=>client.invalidateQueries({queryKey:["staff-me"]})});if(query.isPending)return <p>Loading professional profile…</p>;if(!query.data)return <p>Professional profile is unavailable.</p>;const p=query.data;return <section className="grid gap-6 lg:grid-cols-[18rem_1fr]"><aside className="rounded-2xl border bg-white p-5 text-center"><h2 className="text-xl font-bold">{p.full_name}</h2><p>{p.qualification}</p><p>{p.experience_years} years experience</p></aside><div className="rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Professional profile</h2><p>Assigned clinic: {p.clinic_name??"Not assigned"}</p><p>Service areas: {p.service_area_ids.length}</p><div className="mt-4 flex gap-3"><select aria-label="Availability" value={p.availability} onChange={e=>update.mutate({availability:e.target.value as StaffProfile["availability"]})}><option value="AVAILABLE">Available</option><option value="BUSY">Busy</option><option value="UNAVAILABLE">Unavailable</option></select><button onClick={()=>update.mutate({is_online:!p.is_online})} className="button-primary">Go {p.is_online?"offline":"online"}</button></div></div></section>}
