"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";

import { requestJson } from "@/lib/api/client";
import type { StaffPage, StaffProfile } from "@/lib/staff/contracts";

export function StaffDirectory({ allowManagers = false }: { allowManagers?: boolean }) {
  const [search, setSearch] = useState(""); const [type, setType] = useState(allowManagers ? "" : "PHYSIOTHERAPIST"); const [status, setStatus] = useState(""); const [ordering, setOrdering] = useState("user__first_name"); const [showForm, setShowForm] = useState(false); const [photo, setPhoto] = useState<File | null>(null); const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ["staff", search, type, status, ordering], queryFn: () => requestJson<StaffPage>(`/api/staff/profiles?search=${encodeURIComponent(search)}&type=${type}&status=${status}&ordering=${ordering}`) });
  const session = useQuery({ queryKey: ["session-staff"], queryFn: () => requestJson<{access:{permitted_clinics:Array<{id:string;slug:string}>}}>("/api/session/me") });
  const save = useMutation({ mutationFn: (data: FormData) => fetch("/api/staff/profiles", { method:"POST", body:data }).then(async response => { if(!response.ok) throw new Error((await response.json()).detail ?? "Staff profile could not be created."); return response.json(); }), onSuccess:()=>{setShowForm(false);setPhoto(null);queryClient.invalidateQueries({queryKey:["staff"]});} });
  const toggle = useMutation({ mutationFn: ({id,is_active}:{id:string;is_active:boolean})=>requestJson(`/api/staff/profiles/${id}/status`,{method:"POST",body:JSON.stringify({is_active,reason:"Staff status updated by authorized manager."})}), onSuccess:()=>queryClient.invalidateQueries({queryKey:["staff"]}) });
  function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data=new FormData(event.currentTarget); if(photo)data.set("profile_photo",photo); save.mutate(data); }
  const preview = useMemo(()=>photo ? URL.createObjectURL(photo) : "",[photo]);
  return <section className="mt-8" aria-labelledby="staff-heading"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 id="staff-heading" className="text-2xl font-bold text-slate-950">{allowManagers?"Managers & Physiotherapists":"Physiotherapists"}</h2><p className="mt-1 text-slate-600">Secure staff profiles, clinic scope, availability and status.</p></div><button onClick={()=>setShowForm(value=>!value)} className="min-h-11 rounded-xl bg-emerald-700 px-4 font-bold text-white">{showForm?"Close form":"Add staff member"}</button></div>
  {showForm&&<form onSubmit={create} className="mt-5 grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-2" aria-label="Create staff profile"><h3 className="text-xl font-bold sm:col-span-2">New staff profile</h3><Field name="full_name" label="Full name"/><Field name="email" label="Email" type="email"/><Field name="mobile" label="Mobile (E.164, e.g. +919876543210)"/><label className="grid gap-1 font-semibold">Role<select name="staff_type" className="min-h-11 rounded-xl border px-3">{allowManagers&&<option value="MANAGER">Manager</option>}<option value="PHYSIOTHERAPIST">Physiotherapist</option></select></label><Field name="date_of_birth" label="Date of birth" type="date"/><label className="grid gap-1 font-semibold">Gender<select name="gender" className="min-h-11 rounded-xl border px-3"><option value="FEMALE">Female</option><option value="MALE">Male</option><option value="OTHER">Other</option><option value="PREFER_NOT_TO_SAY">Prefer not to say</option></select></label><Field name="qualification" label="Qualification"/><Field name="registration_number" label="Registration number (optional)" required={false}/><Field name="experience_years" label="Experience (years)" type="number"/><Field name="languages_known" label="Languages known (JSON list)" value='["Hindi","English"]'/><Field name="alternate_mobile" label="Alternate mobile" required={false}/><Field name="emergency_contact" label="Emergency contact"/><Field name="current_address" label="Current address"/><Field name="city" label="City"/><Field name="pin_code" label="PIN code"/><label className="grid gap-1 font-semibold">Clinic<select name="clinic" className="min-h-11 rounded-xl border px-3"><option value="">Organization scope</option>{session.data?.access.permitted_clinics.map(c=><option value={c.id} key={c.id}>{c.slug}</option>)}</select></label><Field name="joining_date" label="Joining date" type="date"/><Field name="bio" label="Professional bio" required={false}/><label className="grid gap-1 font-semibold">Profile photo<input name="profile_photo" type="file" accept="image/*" onChange={e=>setPhoto(e.target.files?.[0]??null)} className="min-h-11 rounded-xl border p-2"/>{preview&&<span className="flex items-center gap-3"><img src={preview} alt="Profile preview" className="size-16 rounded-full object-cover"/><button type="button" onClick={()=>setPhoto(null)} className="text-sm text-red-700 underline">Delete selected photo</button></span>}</label><input type="hidden" name="availability" value="UNAVAILABLE"/><input type="hidden" name="is_online" value="false"/><button className="min-h-11 rounded-xl bg-emerald-700 px-4 font-bold text-white sm:col-span-2" disabled={save.isPending}>{save.isPending?"Creating…":"Create staff profile"}</button>{save.isError&&<p role="alert" className="text-red-700 sm:col-span-2">{save.error.message}</p>}</form>}
  <div className="mt-5 grid gap-3 sm:grid-cols-4"><input aria-label="Search staff" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email, mobile" className="min-h-11 rounded-xl border px-3"/><select aria-label="Filter role" value={type} onChange={e=>setType(e.target.value)} className="min-h-11 rounded-xl border px-3">{allowManagers&&<option value="">All roles</option>}<option value="MANAGER">Managers</option><option value="PHYSIOTHERAPIST">Physiotherapists</option></select><select aria-label="Filter status" value={status} onChange={e=>setStatus(e.target.value)} className="min-h-11 rounded-xl border px-3"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select><select aria-label="Sort staff" value={ordering} onChange={e=>setOrdering(e.target.value)} className="min-h-11 rounded-xl border px-3"><option value="user__first_name">Name</option><option value="-joining_date">Newest joining</option><option value="-experience_years">Experience</option></select></div>
  <div className="mt-5 overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50"><tr>{["Profile","Role","Clinic","Availability","Status","Actions"].map(h=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody>{query.data?.results.map(item=><tr key={item.id} className="border-t"><td className="p-4"><strong>{item.full_name}</strong><span className="block text-slate-500">{item.email} · {item.mobile}</span></td><td className="p-4">{item.staff_type}</td><td className="p-4">{item.clinic??"Organization"}</td><td className="p-4">{item.availability} · {item.is_online?"Online":"Offline"}</td><td className="p-4">{item.is_active?"Active":"Inactive"}</td><td className="p-4"><button onClick={()=>toggle.mutate({id:item.id,is_active:!item.is_active})} className="font-bold text-emerald-800 underline">{item.is_active?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table>{query.isPending&&<p className="p-5">Loading staff…</p>}{query.data?.results.length===0&&<p className="p-5">No staff match these filters.</p>}</div></section>;
}

function Field({name,label,type="text",required=true,value}:{name:string;label:string;type?:string;required?:boolean;value?:string}) { return <label className="grid gap-1 font-semibold">{label}<input name={name} type={type} required={required} defaultValue={value} className="min-h-11 rounded-xl border px-3"/></label>; }

export function ManagerDashboard() { const query=useQuery({queryKey:["manager-staff"],queryFn:()=>requestJson<StaffPage>("/api/staff/profiles?type=PHYSIOTHERAPIST&page_size=50")}); const items=query.data?.results??[]; const cards=[["Total Physiotherapists",items.length],["Active",items.filter(x=>x.is_active).length],["Inactive",items.filter(x=>!x.is_active).length],["Available",items.filter(x=>x.availability==="AVAILABLE").length],["Offline",items.filter(x=>!x.is_online).length],["Today's appointments","—"],["Pending appointments","—"]]; return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value])=><article className="rounded-2xl border bg-white p-5" key={label}><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block text-3xl">{value}</strong></article>)}</div><StaffDirectory/></>; }

export function PhysiotherapistProfile() { const client=useQueryClient(); const query=useQuery({queryKey:["staff-me"],queryFn:()=>requestJson<StaffProfile>("/api/staff/me")}); const update=useMutation({mutationFn:(value:Partial<StaffProfile>)=>requestJson("/api/staff/me/availability",{method:"PATCH",body:JSON.stringify(value)}),onSuccess:()=>client.invalidateQueries({queryKey:["staff-me"]})}); if(query.isPending)return <p>Loading professional profile…</p>; if(!query.data)return <p className="text-red-700">Professional profile is unavailable.</p>; const p=query.data; return <section className="grid gap-6 lg:grid-cols-[18rem_1fr]"><aside className="rounded-2xl border bg-white p-5 text-center">{p.profile_photo?<img src={p.profile_photo} alt={`${p.full_name} profile`} className="mx-auto size-32 rounded-full object-cover"/>:<div className="mx-auto grid size-32 place-items-center rounded-full bg-emerald-100 text-4xl font-bold text-emerald-800">{p.full_name.charAt(0)}</div>}<h2 className="mt-4 text-xl font-bold">{p.full_name}</h2><p>{p.qualification}</p><p className="mt-2 text-sm text-slate-500">{p.experience_years} years experience</p></aside><div className="rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Professional profile</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="font-semibold">Assigned clinic</dt><dd>{p.clinic??"Not assigned"}</dd></div><div><dt className="font-semibold">Service area</dt><dd>{p.service_area_ids.length?`${p.service_area_ids.length} assigned`:"Not assigned"}</dd></div><div><dt className="font-semibold">Availability</dt><dd>{p.availability}</dd></div><div><dt className="font-semibold">Status</dt><dd>{p.is_online?"Online":"Offline"}</dd></div></dl><div className="mt-6 flex flex-wrap gap-3"><select aria-label="Availability" value={p.availability} onChange={e=>update.mutate({availability:e.target.value as StaffProfile["availability"]})} className="min-h-11 rounded-xl border px-3"><option value="AVAILABLE">Available</option><option value="BUSY">Busy</option><option value="UNAVAILABLE">Unavailable</option></select><button onClick={()=>update.mutate({is_online:!p.is_online})} className="min-h-11 rounded-xl bg-emerald-700 px-4 font-bold text-white">Go {p.is_online?"offline":"online"}</button></div><p className="mt-8 rounded-xl bg-slate-50 p-4 text-slate-600">No appointments are assigned in this phase.</p></div></section>; }
