"use client";
import {useEffect,useMemo,useState} from "react";
import {isStrongPassword,PasswordCreationFields} from "@/components/auth/password-creation-fields";
import {requestJson} from "@/lib/api/client";
import {loadOtpWidgetConfig,sendMsg91Otp,verifyMsg91Otp,type OtpWidgetConfig} from "@/lib/auth/msg91-widget";
type Option={id:string;name:string}; type Clinic={id:string;slug:string}; type Role="MANAGER"|"PHYSIOTHERAPIST"; type Stage="details"|"otp"|"credentials"|"documents"|"review"|"success"; type EditMode="details"|"password"|"documents"|null;
type Values={full_name:string;email:string;mobile:string;gender:string;qualification:string;experience_years:string;practitioner_type:"PHYSIOTHERAPIST"|"WELLNESS";specialization:string;languages:string[];languages_text:string;clinic:string;service_areas:string[];competencies:string[];working_days:number[];starts_at:string;ends_at:string;joining_date:string;bio:string;is_active:boolean;is_publicly_visible:boolean};
const field="min-h-11 rounded-xl border border-slate-300 px-3",days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const docLabels:Record<string,string>={government_id_document:"Government Identity Proof",qualification_document:"Qualification Certificate",experience_document:"Experience Certificate",other_document:"Other Practitioner Certificate"};
const fresh=():Values=>({full_name:"",email:"",mobile:"",gender:"PREFER_NOT_TO_SAY",qualification:"",experience_years:"",practitioner_type:"PHYSIOTHERAPIST",specialization:"",languages:[],languages_text:"",clinic:"",service_areas:[],competencies:[],working_days:[0,1,2,3,4,5],starts_at:"10:00",ends_at:"19:00",joining_date:new Date().toISOString().slice(0,10),bio:"",is_active:true,is_publicly_visible:false});
function message(body:unknown):string{if(typeof body==="string")return body;if(Array.isArray(body))return body.map(message).join(" ");if(body&&typeof body==="object")return Object.entries(body).map(([k,v])=>`${k.replaceAll("_"," ")}: ${message(v)}`).join(" ");return "Staff profile could not be created."}
function safeError(error:unknown){if(!(error instanceof Error))return "Please try again.";const fields=(error as Error&{fieldErrors?:Record<string,string>}).fieldErrors;return fields&&Object.keys(fields).length?Object.values(fields).join(" "):error.message}
export function parseExperience(value:string){const match=/^(\d{1,2})(?:\.(\d{1,2}))?$/.exec(value.trim());if(!match)return null;const years=Number(match[1]),months=Number(match[2]??0);return years<=60&&months<=11?{years,months}:null}
export function formatExperience(years:number,months:number){return [years?`${years} year${years===1?"":"s"}`:"",months?`${months} month${months===1?"":"s"}`:""].filter(Boolean).join(" ")||"0 months"}
function useUrl(file:File|null){const url=useMemo(()=>file?URL.createObjectURL(file):"",[file]);useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);return url}

export function StaffCreationWizard({role,clinics,therapies,serviceAreas,onCreated}:{role:Role;clinics:Clinic[];therapies:Option[];serviceAreas:Option[];onCreated:()=>void}){
 const [stage,setStage]=useState<Stage>("details"),[editMode,setEditMode]=useState<EditMode>(null),[v,setV]=useState<Values>(fresh),[search,setSearch]=useState(""),[photo,setPhoto]=useState<File|null>(null),[docs,setDocs]=useState<Record<string,File|null>>({}),[verificationId,setVerificationId]=useState(""),[verificationToken,setVerificationToken]=useState(""),[verifiedMobile,setVerifiedMobile]=useState(""),[otp,setOtp]=useState(""),[otpConfig,setOtpConfig]=useState<OtpWidgetConfig>({enabled:false}),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const therapist=role==="PHYSIOTHERAPIST",roleName=therapist?"Therapist":"Manager",photoUrl=useUrl(photo),filtered=useMemo(()=>therapies.filter(x=>x.name.toLowerCase().includes(search.toLowerCase())),[therapies,search]),selected=therapies.filter(x=>v.competencies.includes(x.id));
 const strong=isStrongPassword(password),docsValid=!therapist||!!(docs.government_id_document&&docs.qualification_document);
 function set<K extends keyof Values>(k:K,value:Values[K]){setV(x=>({...x,[k]:value}))} function toggle(k:"competencies"|"service_areas",id:string){set(k,v[k].includes(id)?v[k].filter(x=>x!==id):[...v[k],id])}
 function fail(text:string,id?:string){setError(text);if(id)requestAnimationFrame(()=>{const target=document.getElementById(id);target?.scrollIntoView({behavior:"smooth",block:"center"});target?.focus();const control=target instanceof HTMLInputElement||target instanceof HTMLSelectElement?target:target?.querySelector("input,select");if(control instanceof HTMLInputElement||control instanceof HTMLSelectElement){control.setCustomValidity(text);control.reportValidity();control.addEventListener("input",()=>control.setCustomValidity(""),{once:true})}})}
 function validate(){if(!v.full_name.trim())return["Full name is required.","full-name"];if(!/^\S+@\S+\.\S+$/.test(v.email))return["Enter a valid email address.","email"];if(!/^\+91[6-9]\d{9}$/.test(v.mobile.trim()))return["Enter mobile number in +91XXXXXXXXXX format.","mobile"];if(!v.qualification.trim())return["Qualification is required.","qualification"];if(!parseExperience(v.experience_years))return["Enter experience in Years.Months format. Months must be between 0 and 11.","experience"];if(!v.clinic)return["Please select a clinic.","clinic"];if(!v.languages.length)return["Please enter at least one language.","language"];if(!photo)return["Profile photo is required.","photo"];if(therapist&&!v.competencies.length)return["Please select at least one therapy competency.","therapy-search"];if(therapist&&!v.service_areas.length)return["Please select at least one service area.","service-areas"];if(therapist&&!v.working_days.length)return["Please select working days.","working-days"];return null}
 async function beginOtp(){const p=validate();if(p){fail(p[0],p[1]);return}const normalized=v.mobile.trim();if(verificationToken&&verifiedMobile===normalized){setError("");if(editMode==="details"){setEditMode(null);setStage("review")}else setStage("credentials");return}setBusy(true);setError("");try{set("mobile",normalized);await requestJson("/api/staff/mobile-availability",{method:"POST",body:JSON.stringify({mobile:normalized})});const widget=await loadOtpWidgetConfig(),mobile=normalized.slice(-10),issued=await requestJson<{verification_id:string}>("/api/booking-otp/issue",{method:"POST",body:JSON.stringify({mobile_number:mobile})});if(widget.enabled)await sendMsg91Otp(widget,mobile);setOtpConfig(widget);setVerificationId(issued.verification_id);setStage("otp")}catch(e){fail(`OTP could not be sent. ${safeError(e)}`)}finally{setBusy(false)}}
 async function verify(){setBusy(true);setError("");try{const proof=otpConfig.enabled?{access_token:await verifyMsg91Otp(otpConfig,otp)}:{otp},result=await requestJson<{token:string}>("/api/booking-otp/verify",{method:"POST",body:JSON.stringify({verification_id:verificationId,mobile_number:v.mobile.slice(-10),...proof})});setVerificationToken(result.token);setVerifiedMobile(v.mobile.trim());setOtp("");if(editMode==="details"){setEditMode(null);setStage("review")}else setStage("credentials")}catch(e){fail(e instanceof Error?e.message:"Mobile verification failed.")}finally{setBusy(false)}}
 function pickPhoto(file:File|null){if(file&&(!file.type.startsWith("image/")||file.size>10*1024*1024)){fail("Profile photo must be an image no larger than 10 MB.","photo");return}setError("");setPhoto(file)}
 function pickDoc(name:string,file:File|null){if(file&&(!file.name.toLowerCase().endsWith(".pdf")||file.type!=="application/pdf"||file.size>25*1024*1024)){fail(`${docLabels[name]} must be a PDF no larger than 25 MB.`);return}setError("");setDocs(x=>({...x,[name]:file}))}
 function reset(){setV(fresh());setSearch("");setPhoto(null);setDocs({});setVerificationId("");setVerificationToken("");setVerifiedMobile("");setOtp("");setPassword("");setConfirm("");setEditMode(null);setError("");setStage("details")}
 async function create(){if(!verificationToken||!strong||password!==confirm||!docsValid){fail("Complete all required verification, password, and document steps.");return}const experience=parseExperience(v.experience_years);if(!experience){fail("Enter experience in Years.Months format. Months must be between 0 and 11.","experience");return}setBusy(true);setError("");try{const data=new FormData();Object.entries({staff_type:role,full_name:v.full_name,email:v.email,mobile:v.mobile,gender:v.gender,qualification:v.qualification,experience_years:String(experience.years),experience_months:String(experience.months),languages_known:JSON.stringify(v.languages),clinic:v.clinic,joining_date:v.joining_date,bio:v.specialization?`${v.specialization}${v.bio?` — ${v.bio}`:""}`:v.bio,availability:"UNAVAILABLE",is_online:"false",is_publicly_visible:String(therapist&&v.is_publicly_visible),operationally_active:String(v.is_active),practitioner_type:v.practitioner_type,mobile_verification_token:verificationToken,password,confirm_password:confirm}).forEach(([k,value])=>data.set(k,value));v.competencies.forEach(id=>data.append("therapy_competency_ids",id));v.service_areas.forEach(id=>data.append("service_area_ids",id));if(photo)data.set("profile_photo",photo);Object.entries(docs).forEach(([k,file])=>{if(file)data.set(k,file)});const response=await fetch("/api/staff/profiles",{method:"POST",body:data}),body=await response.json();if(!response.ok)throw new Error(message(body));if(therapist)for(const weekday of v.working_days)await requestJson("/api/availability/rules",{method:"POST",body:JSON.stringify({clinic:body.clinic,physiotherapist:body.id,weekday,starts_at:v.starts_at,ends_at:v.ends_at,effective_from:v.joining_date})});setPassword("");setConfirm("");setOtp("");setVerificationToken("");setStage("success");window.setTimeout(()=>{reset();onCreated()},3000)}catch(e){fail(e instanceof Error?e.message:"Staff profile could not be created.")}finally{setBusy(false)}}
 if(stage==="success")return <div className="mt-5 rounded-2xl border bg-white p-6 text-center"><p role="status" className="text-xl font-bold text-emerald-800">✓ REGISTERED SUCCESSFULLY</p><p>{roleName} has been added to JeevaSetu.</p></div>;
 return <section className="mt-5 rounded-2xl border bg-white p-5" aria-label={`Create ${roleName.toLowerCase()} profile`}><ol className="mb-6 grid grid-cols-5 gap-2 text-center text-xs font-bold">{["Details","Verify mobile","Password","Documents","Review"].map((x,i)=><li key={x} className={`rounded-lg p-2 ${i===["details","otp","credentials","documents","review"].indexOf(stage)?"bg-emerald-700 text-white":"bg-slate-100"}`}>{i+1}. {x}</li>)}</ol>{error&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}
 {stage==="details"&&<div className="grid gap-4 sm:grid-cols-2"><Field id="full-name" label="Full Name *" value={v.full_name} set={x=>set("full_name",x)}/><Field id="email" label="Email *" type="email" value={v.email} set={x=>set("email",x)}/><Mobile value={v.mobile} set={x=>{set("mobile",x);if(verifiedMobile&&x.trim()!==verifiedMobile){setVerificationToken("");setVerifiedMobile("");setError("Mobile number changed. Please verify the new mobile number.")}}}/><Select label="Gender" value={v.gender} set={x=>set("gender",x)} options={[["PREFER_NOT_TO_SAY","Prefer not to say"],["FEMALE","Female"],["MALE","Male"],["OTHER","Other"]]}/><Field id="qualification" label="Highest Qualification *" value={v.qualification} set={x=>set("qualification",x)}/><Experience value={v.experience_years} set={x=>set("experience_years",x)}/><Select id="clinic" label="Clinic *" value={v.clinic} set={x=>set("clinic",x)} options={[["","Select clinic"],...clinics.map(x=>[x.id,x.slug])]}/><Languages value={v.languages_text} set={x=>setV(current=>({...current,languages_text:x,languages:parseLanguages(x)}))}/><Photo file={photo} url={photoUrl} set={pickPhoto}/>
 {therapist&&<><Select label="Practitioner Type *" value={v.practitioner_type} set={x=>set("practitioner_type",x as Values["practitioner_type"])} options={[["PHYSIOTHERAPIST","Physiotherapist"],["WELLNESS","Naturopathy Practitioner"]]}/><Field label="Specialization / Expertise" value={v.specialization} set={x=>set("specialization",x)}/><div className="sm:col-span-2"><label className="grid gap-1 font-semibold">Verified Therapy Competencies<input id="therapy-search" aria-label="Search therapies" value={search} onChange={e=>setSearch(e.target.value)} className={field}/></label><div className="mt-2 flex flex-wrap gap-2">{selected.map(x=><button type="button" key={x.id} onClick={()=>toggle("competencies",x.id)} className="rounded-full bg-emerald-100 px-3 py-1">✓ {x.name} ×</button>)}</div><div className="mt-2 grid max-h-40 gap-1 overflow-auto rounded-xl border p-2">{filtered.map(x=><label key={x.id}><input type="checkbox" checked={v.competencies.includes(x.id)} onChange={()=>toggle("competencies",x.id)} className="mr-2"/>{x.name}</label>)}</div></div><Checks id="service-areas" title="Service Areas *" options={serviceAreas} selected={v.service_areas} toggle={id=>toggle("service_areas",id)}/><fieldset id="working-days" tabIndex={-1} className="sm:col-span-2"><legend className="font-semibold">Working Days *</legend>{days.map((x,i)=><label key={x} className="mr-3"><input type="checkbox" checked={v.working_days.includes(i)} onChange={()=>set("working_days",v.working_days.includes(i)?v.working_days.filter(y=>y!==i):[...v.working_days,i])}/> {x}</label>)}</fieldset><Field label="Working Hours Start" type="time" value={v.starts_at} set={x=>set("starts_at",x)}/><Field label="Working Hours End" type="time" value={v.ends_at} set={x=>set("ends_at",x)}/><Field label="Professional Bio" value={v.bio} set={x=>set("bio",x)}/><Check label="Public Profile Visible" value={v.is_publicly_visible} set={x=>set("is_publicly_visible",x)}/></>}<Field label="Joining Date" type="date" value={v.joining_date} set={x=>set("joining_date",x)}/><Check label="Active" value={v.is_active} set={x=>set("is_active",x)}/><button type="button" onClick={beginOtp} disabled={busy} className="button-primary sm:col-span-2">{busy?"Checking and sending OTP…":editMode==="details"?"Continue":"Continue to Mobile Verification"}</button></div>}
 {stage==="otp"&&<div className="mx-auto max-w-md space-y-4"><h3 className="text-xl font-bold">STEP 2 — VERIFY MOBILE NUMBER</h3><p className="rounded-xl bg-emerald-50 p-3">OTP has been sent to your registered mobile number.</p><p>Mobile: <strong>{v.mobile}</strong></p><input aria-label="Enter OTP" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,""))} maxLength={6} className={`${field} w-full`}/><button type="button" onClick={verify} disabled={busy||otp.length!==6} className="button-primary w-full">Verify OTP</button><button type="button" onClick={beginOtp} className="button-secondary w-full">Resend OTP</button><button type="button" onClick={()=>setStage("details")} className="button-secondary w-full">Change Mobile Number</button></div>}
 {stage==="credentials"&&<div className="mx-auto max-w-md space-y-4"><h3 className="text-xl font-bold">STEP 3 — CREATE PASSWORD</h3><p className="rounded-xl bg-emerald-50 p-3">✓ PHONE NUMBER VERIFIED</p><PasswordCreationFields password={password} confirmPassword={confirm} onPasswordChange={setPassword} onConfirmPasswordChange={setConfirm} passwordLabel="Password" confirmLabel="Confirm Password"/><button type="button" disabled={!strong||password!==confirm} onClick={()=>{if(editMode==="password"){setEditMode(null);setStage("review")}else setStage("documents")}} className="button-primary w-full">{editMode==="password"?"Continue":"Continue to Documents"}</button><Back set={()=>setStage("otp")}/></div>}
 {stage==="documents"&&<div className="grid gap-4 sm:grid-cols-2"><h3 className="text-xl font-bold sm:col-span-2">STEP 4 — DOCUMENTS</h3><p className="sm:col-span-2">Private PDF documents only, maximum 25 MB per PDF.</p>{Object.entries(docLabels).map(([name,label])=><Document key={name} label={`${label}${therapist&&["government_id_document","qualification_document"].includes(name)?" *":""}`} name={name} file={docs[name]||null} set={f=>pickDoc(name,f)}/>) }<Back set={()=>setStage("credentials")}/><button type="button" onClick={()=>{if(!docsValid){fail("Government Identity Proof and Qualification Certificate are required.");return}setEditMode(null);setStage("review")}} className="button-primary">{editMode==="documents"?"Continue":"Continue to Review"}</button></div>}
 {stage==="review"&&<div className="space-y-5"><h3 className="text-xl font-bold">STEP 5 — REVIEW {roleName.toUpperCase()}</h3>{photoUrl&&<img src={photoUrl} alt="Profile photo" className="h-24 w-24 rounded-xl object-cover"/>}<dl className="grid gap-3 sm:grid-cols-2">{[["Name",v.full_name],["Email",v.email],["Verified Mobile",`${v.mobile} — VERIFIED`],["Gender",v.gender],["Qualification",v.qualification],["Experience",formatExperience(parseExperience(v.experience_years)?.years??0,parseExperience(v.experience_years)?.months??0)],["Languages",v.languages.join(", ")],...(therapist?[["Practitioner Type",v.practitioner_type==="WELLNESS"?"Naturopathy Practitioner":"Physiotherapist"],["Specialization / Expertise",v.specialization],["Therapy Competencies",selected.map(x=>x.name).join(", ")],["Service Areas",serviceAreas.filter(x=>v.service_areas.includes(x.id)).map(x=>x.name).join(", ")],["Working Days",v.working_days.map(x=>days[x]).join(", ")],["Working Hours",`${v.starts_at}–${v.ends_at}`],["Professional Bio",v.bio],["Public Profile Visible",v.is_publicly_visible?"Yes":"No"]]:[]),["Joining Date",v.joining_date],["Active",v.is_active?"Yes":"No"],["Uploaded Documents",Object.entries(docs).filter(([,f])=>f).map(([k,f])=>`${docLabels[k]}: ${f?.name}`).join(", ")]].map(([label,value])=><div key={label}><dt className="font-semibold">{label}</dt><dd>{value||"Not provided"}</dd></div>)}</dl><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>{setEditMode("details");setStage("details")}} className="button-secondary">Edit Details</button><button type="button" onClick={()=>{setEditMode("password");setStage("credentials")}} className="button-secondary">Edit Password</button><button type="button" onClick={()=>{setEditMode("documents");setStage("documents")}} className="button-secondary">Edit Documents</button></div><button type="button" onClick={create} disabled={busy} className="button-primary">{busy?"Creating…":`CREATE ${roleName.toUpperCase()} PROFILE`}</button></div>}</section>
}
function Field({id,label,value,set,type="text"}:{id?:string;label:string;value:string;set:(x:string)=>void;type?:string}){return <label className="grid gap-1 font-semibold">{label}<input id={id} aria-label={label} type={type} value={value} onChange={e=>set(e.target.value)} className={field}/></label>}
function Experience({value,set}:{value:string;set:(x:string)=>void}){return <label className="grid gap-1 font-semibold">Experience *<input id="experience" aria-label="Experience *" inputMode="decimal" value={value} onChange={e=>set(e.target.value)} placeholder="4.6" className={field}/><span className="text-sm font-normal text-slate-600">Enter experience as Years.Months — e.g. 4.6 = 4 years 6 months, 3.2 = 3 years 2 months.</span></label>}
function Select({id,label,value,set,options}:{id?:string;label:string;value:string;set:(x:string)=>void;options:string[][]}){return <label className="grid gap-1 font-semibold">{label}<select id={id} aria-label={label} value={value} onChange={e=>set(e.target.value)} className={field}>{options.map(([x,y])=><option value={x} key={x}>{y}</option>)}</select></label>}
function Check({label,value,set}:{label:string;value:boolean;set:(x:boolean)=>void}){return <label className="flex items-center gap-2 font-semibold"><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/>{label}</label>}
function Checks({id,title,options,selected,toggle}:{id:string;title:string;options:Option[];selected:string[];toggle:(x:string)=>void}){return <fieldset id={id} tabIndex={-1} className="sm:col-span-2"><legend className="font-semibold">{title}</legend>{options.length?options.map(x=><label key={x.id} className="mr-3"><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>toggle(x.id)}/> {x.name}</label>):<p role="alert" className="mt-2 text-sm font-semibold text-red-700">No service areas are configured. Ask an administrator to configure one before continuing.</p>}</fieldset>}
function parseLanguages(value:string){const seen=new Set<string>();return value.split(",").map(x=>x.trim()).filter(x=>{const key=x.toLowerCase();if(!key||seen.has(key))return false;seen.add(key);return true})}
function Mobile({value,set}:{value:string;set:(x:string)=>void}){return <label className="grid gap-1 font-semibold">Mobile Number *<input id="mobile" aria-label="Mobile Number *" value={value} onChange={e=>set(e.target.value)} placeholder="+919286199103" inputMode="tel" className={field}/><span className="text-sm font-normal text-slate-600">Phone number must be in this format: +91XXXXXXXXXX</span></label>}
function Languages({value,set}:{value:string;set:(x:string)=>void}){return <label className="grid gap-1 font-semibold sm:col-span-2">Languages Known *<input id="language" aria-label="Languages Known *" value={value} onChange={e=>set(e.target.value)} placeholder="Hindi, English, Punjabi" className={field}/></label>}
function Photo({file,url,set}:{file:File|null;url:string;set:(f:File|null)=>void}){return <div className="sm:col-span-2"><p className="font-semibold">Profile Photo *</p><input id="photo" aria-label="Profile Photo" type="file" accept="image/*" onChange={e=>set(e.target.files?.[0]||null)} className={`${field} w-full`}/>{file&&<div className="mt-2 flex items-center gap-3"><img src={url} alt="Profile photo preview" className="h-20 w-20 rounded-xl object-cover"/><div><p>{file.name}</p><label className="cursor-pointer font-semibold text-emerald-800">Change Photo<input type="file" accept="image/*" className="sr-only" onChange={e=>set(e.target.files?.[0]||null)}/></label><button type="button" onClick={()=>set(null)} className="ml-3 font-semibold text-red-700">Remove</button></div></div>}</div>}
function Document({label,name,file,set}:{label:string;name:string;file:File|null;set:(f:File|null)=>void}){const url=useUrl(file);return <div><p className="font-semibold">{label}</p><input aria-label={label} name={name} type="file" accept="application/pdf,.pdf" onChange={e=>set(e.target.files?.[0]||null)} className={`${field} w-full`}/>{file&&<p className="text-sm">✓ {file.name} <a href={url} target="_blank" rel="noreferrer" className="font-semibold text-emerald-800">Preview</a><label className="ml-3 cursor-pointer font-semibold text-emerald-800">Replace<input type="file" accept="application/pdf,.pdf" className="sr-only" onChange={e=>set(e.target.files?.[0]||null)}/></label><button type="button" onClick={()=>set(null)} className="ml-3 font-semibold text-red-700">Remove</button></p>}</div>}
function Back({set}:{set:()=>void}){return <button type="button" onClick={set} className="button-secondary">EDIT / Back</button>}
